defmodule LemonSim.Examples.IntelNetwork.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Intel Briefing Phase --

  @spec briefing_received(String.t(), String.t()) :: Event.t()
  def briefing_received(player_id, fragment_id) do
    Event.new("briefing_received", %{
      "player_id" => player_id,
      "fragment_id" => fragment_id
    })
  end

  # -- Communication Phase --

  @spec send_message(String.t(), String.t(), String.t()) :: Event.t()
  def send_message(sender_id, recipient_id, content) do
    Event.new("send_message", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "content" => content
    })
  end

  @spec message_delivered(String.t(), String.t(), String.t()) :: Event.t()
  def message_delivered(sender_id, recipient_id, content) do
    Event.new("message_delivered", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "content" => content
    })
  end

  @spec end_communication(String.t()) :: Event.t()
  def end_communication(player_id) do
    Event.new("end_communication", %{"player_id" => player_id})
  end

  @spec communication_ended(String.t()) :: Event.t()
  def communication_ended(player_id) do
    Event.new("communication_ended", %{"player_id" => player_id})
  end

  # -- Analysis Phase --

  @spec submit_analysis(String.t(), String.t()) :: Event.t()
  def submit_analysis(player_id, notes) do
    Event.new("submit_analysis", %{
      "player_id" => player_id,
      "notes" => notes
    })
  end

  @spec analysis_submitted(String.t()) :: Event.t()
  def analysis_submitted(player_id) do
    Event.new("analysis_submitted", %{"player_id" => player_id})
  end

  # -- Operation Phase --

  @spec propose_operation(String.t(), String.t(), String.t() | nil) :: Event.t()
  def propose_operation(player_id, operation_type, target_id) do
    Event.new("propose_operation", %{
      "player_id" => player_id,
      "operation_type" => operation_type,
      "target_id" => target_id
    })
  end

  @spec operation_completed(String.t(), String.t(), String.t() | nil, String.t()) :: Event.t()
  def operation_completed(player_id, operation_type, target_id, result) do
    Event.new("operation_completed", %{
      "player_id" => player_id,
      "operation_type" => operation_type,
      "target_id" => target_id,
      "result" => result
    })
  end

  @spec end_operations(String.t()) :: Event.t()
  def end_operations(player_id) do
    Event.new("end_operations", %{"player_id" => player_id})
  end

  # -- Mole Action Phase (hidden) --

  @spec mole_action(String.t(), String.t(), String.t() | nil) :: Event.t()
  def mole_action(player_id, action_type, target_id) do
    Event.new("mole_action", %{
      "player_id" => player_id,
      "action_type" => action_type,
      "target_id" => target_id
    })
  end

  @spec intel_leaked(String.t(), String.t()) :: Event.t()
  def intel_leaked(mole_id, fragment_id) do
    Event.new("intel_leaked", %{
      "mole_id" => mole_id,
      "fragment_id" => fragment_id
    })
  end

  @spec agent_framed(String.t(), String.t()) :: Event.t()
  def agent_framed(mole_id, target_id) do
    Event.new("agent_framed", %{
      "mole_id" => mole_id,
      "target_id" => target_id
    })
  end

  @spec mole_passed(String.t()) :: Event.t()
  def mole_passed(mole_id) do
    Event.new("mole_passed", %{"mole_id" => mole_id})
  end

  # -- System events (generated by updater) --

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec round_advanced(pos_integer()) :: Event.t()
  def round_advanced(round) do
    Event.new("round_advanced", %{"round" => round})
  end

  @spec trust_updated(String.t(), String.t(), number()) :: Event.t()
  def trust_updated(observer_id, subject_id, new_level) do
    Event.new("trust_updated", %{
      "observer_id" => observer_id,
      "subject_id" => subject_id,
      "new_level" => new_level
    })
  end

  @spec suspicion_flagged(String.t(), String.t()) :: Event.t()
  def suspicion_flagged(reporter_id, suspect_id) do
    Event.new("suspicion_flagged", %{
      "reporter_id" => reporter_id,
      "suspect_id" => suspect_id
    })
  end

  @spec game_over(String.t(), String.t() | nil) :: Event.t()
  def game_over(reason, winner) do
    Event.new("game_over", %{
      "reason" => reason,
      "winner" => winner,
      "message" => game_over_message(reason, winner)
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, player_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "player_id" => player_id,
      "reason" => reason
    })
  end

  # -- Private --

  defp game_over_message("mole_survived", mole_id),
    do: "The mole (#{mole_id}) survived undetected — network compromised!"

  defp game_over_message("mole_leaked_enough", mole_id),
    do: "The mole (#{mole_id}) leaked 5+ intel fragments — adversary wins!"

  defp game_over_message("mole_identified", winner),
    do: "Loyal operatives correctly identified the mole! #{winner} network stands!"

  defp game_over_message(reason, winner),
    do: "Game over (#{reason}): #{winner}"
end
