defmodule LemonControlPlane.Methods.MediaStatus do
  @moduledoc """
  Handler for `media.status`.

  Returns redacted generated-media job and artifact metadata without prompts,
  raw artifact paths, generated bytes, provider responses, or channel message
  bodies.
  """

  @behaviour LemonControlPlane.Method

  @provider_specs [
    %{
      providers: ["openai_image", "vertex_imagen"],
      label: "image",
      script: "scripts/live_media_image_smoke.exs",
      proof_path: ".lemon/proofs/media-image-smoke-latest.json"
    },
    %{
      providers: ["openai_tts", "elevenlabs_tts", "google_tts"],
      label: "TTS",
      script: "scripts/live_media_speech_smoke.exs",
      proof_path: ".lemon/proofs/media-speech-smoke-latest.json"
    },
    %{
      providers: ["openai_transcribe", "deepgram_transcribe"],
      label: "STT",
      script: "scripts/live_media_transcription_smoke.exs",
      proof_path: ".lemon/proofs/media-transcription-smoke-latest.json"
    },
    %{
      providers: ["openai_vision"],
      label: "vision",
      script: "scripts/live_media_vision_smoke.exs",
      proof_path: ".lemon/proofs/media-vision-smoke-latest.json"
    },
    %{
      providers: ["openai_video", "vertex_veo"],
      label: "video",
      script: "scripts/live_media_video_smoke.exs",
      proof_path: ".lemon/proofs/media-video-smoke-latest.json"
    }
  ]

  @impl true
  def name, do: "media.status"

  @impl true
  def scopes, do: [:read]

  @impl true
  def handle(params, _ctx) do
    params = params || %{}
    project_dir = params["projectDir"] || params["project_dir"] || File.cwd!()

    jobs_dir =
      params["jobsDir"] || params["jobs_dir"] || LemonMedia.MediaJobs.default_dir(project_dir)

    artifacts_dir =
      params["artifactsDir"] ||
        params["artifacts_dir"] ||
        LemonMedia.MediaJobs.default_artifacts_dir(project_dir)

    limit = params["limit"] || 20

    {:ok,
     %{
       "jobsDir" => jobs_dir,
       "artifactsDir" => artifacts_dir,
       "workerStatus" => LemonMedia.MediaJobSupervisor.status() |> stringify_keys(),
       "summary" =>
         LemonMedia.MediaJobs.summary(
           project_dir: project_dir,
           dir: jobs_dir,
           artifacts_dir: artifacts_dir
         )
         |> stringify_keys(),
       "providerProofs" =>
         project_dir
         |> provider_proofs()
         |> stringify_keys(),
       "recentJobs" =>
         LemonMedia.MediaJobs.recent(project_dir: project_dir, dir: jobs_dir, limit: limit)
         |> Enum.map(&stringify_keys/1)
     }}
  rescue
    error ->
      {:error,
       {
         :internal_error,
         "Failed to build media status",
         Exception.message(error)
       }}
  end

  defp provider_proofs(project_dir) do
    proofs =
      LemonCore.Doctor.ProofDiagnostics.status(project_dir: project_dir, limit: 1_000)
      |> Map.get(:recent_proofs, [])

    providers = Enum.map(@provider_specs, &provider_proof_summary(&1, proofs))
    completed_count = Enum.count(providers, &(&1.status == :proven))

    %{
      status: if(completed_count == length(@provider_specs), do: :proven, else: :incomplete),
      completed_count: completed_count,
      required_count: length(@provider_specs),
      providers: providers,
      next_action: provider_next_action(providers),
      cleanup: provider_proofs_cleanup()
    }
  rescue
    error ->
      unavailable_provider_proofs(Exception.message(error))
  catch
    kind, reason ->
      unavailable_provider_proofs(inspect({kind, reason}))
  end

  defp unavailable_provider_proofs(error) do
    %{
      status: :unknown,
      completed_count: 0,
      required_count: length(@provider_specs),
      providers: Enum.map(@provider_specs, &unavailable_provider_summary/1),
      next_action: "run provider-backed media smoke scripts",
      cleanup: provider_proofs_cleanup(),
      error: error
    }
  end

  defp unavailable_provider_summary(spec) do
    %{
      provider: provider_primary(spec),
      providers: spec.providers,
      label: spec.label,
      command: provider_command(spec.script, spec.proof_path),
      secret_command: provider_secret_command(spec.script, spec.proof_path),
      provider_commands: provider_commands(spec),
      proof_path: spec.proof_path,
      status: :unknown,
      proof_status: nil,
      reason_kind: nil,
      model: nil,
      modified_at: nil,
      proof_hash: nil,
      next_action: "run #{spec.script}"
    }
  end

  defp provider_proof_summary(spec, proofs) do
    proof =
      proofs
      |> Enum.filter(&(get_in(&1, [:media_proof, :provider]) in spec.providers))
      |> Enum.sort_by(
        fn proof ->
          {provider_proof_rank(Map.get(proof, :status)), Map.get(proof, :modified_at) || ""}
        end,
        fn {rank_a, modified_a}, {rank_b, modified_b} ->
          rank_a < rank_b or (rank_a == rank_b and modified_a >= modified_b)
        end
      )
      |> List.first()

    proof_status = Map.get(proof || %{}, :status)

    %{
      provider: get_in(proof || %{}, [:media_proof, :provider]) || provider_primary(spec),
      providers: spec.providers,
      label: spec.label,
      command: provider_command(spec.script, spec.proof_path),
      secret_command: provider_secret_command(spec.script, spec.proof_path),
      provider_commands: provider_commands(spec),
      proof_path: spec.proof_path,
      status: provider_proof_status(proof_status),
      proof_status: proof_status,
      reason_kind: Map.get(proof || %{}, :reason_kind),
      model: get_in(proof || %{}, [:media_proof, :model]),
      modified_at: Map.get(proof || %{}, :modified_at),
      proof_hash: Map.get(proof || %{}, :proof_hash),
      next_action:
        provider_next_action(
          proof_status,
          spec.script,
          Map.get(proof || %{}, :reason_kind),
          spec.label
        )
    }
  end

  defp provider_primary(%{providers: [provider | _]}), do: provider

  defp provider_commands(%{providers: [_provider]}), do: []

  defp provider_commands(spec) do
    Enum.map(spec.providers, fn provider ->
      %{
        provider: provider,
        command: provider_command(spec.script, spec.proof_path, provider),
        secret_command: provider_secret_command(spec.script, spec.proof_path, provider)
      }
    end)
  end

  defp provider_command(script, proof_path) do
    "LEMON_TEST_ALLOW_LIVE_CREDENTIALS=1 MIX_ENV=test mix run --no-start #{script} --proof-path #{proof_path}"
  end

  defp provider_secret_command(script, proof_path) do
    "#{provider_command(script, proof_path)} --api-key-secret SECRET_NAME"
  end

  defp provider_command(script, proof_path, provider) do
    "#{provider_command(script, proof_path)} --provider #{provider}"
  end

  defp provider_secret_command(script, proof_path, provider) do
    "#{provider_command(script, proof_path, provider)} --api-key-secret SECRET_NAME"
  end

  defp provider_proof_rank("completed"), do: 0
  defp provider_proof_rank("failed"), do: 1
  defp provider_proof_rank("skipped"), do: 2
  defp provider_proof_rank(_), do: 3

  defp provider_proof_status("completed"), do: :proven
  defp provider_proof_status("failed"), do: :blocked
  defp provider_proof_status("skipped"), do: :missing
  defp provider_proof_status(_), do: :missing

  defp provider_next_action(providers) when is_list(providers) do
    providers
    |> Enum.reject(&(&1.status == :proven))
    |> List.first()
    |> case do
      nil -> "keep provider-backed media proofs current"
      provider -> provider.next_action
    end
  end

  defp provider_next_action("completed", _script, _reason, _label), do: "keep proof current"

  defp provider_next_action("failed", script, reason, label) do
    case provider_reason_action(reason, label) do
      nil -> "inspect provider diagnostics and rerun #{script}"
      action -> "#{action}; rerun #{script}"
    end
  end

  defp provider_next_action("skipped", script, _reason, _label),
    do: "enable live credentials and rerun #{script}"

  defp provider_next_action(_status, script, _reason, _label), do: "run #{script}"

  defp provider_reason_action(reason, label) when is_binary(reason) do
    cond do
      String.contains?(reason, "permission_denied") ->
        "#{label}: enable provider API/IAM/billing permissions for the configured account"

      String.contains?(reason, "billing_limit") ->
        "#{label}: use a funded provider account or raise quota"

      String.contains?(reason, "payment_required") ->
        "#{label}: fund or upgrade the provider account"

      String.contains?(reason, "invalid_request_error") ->
        "#{label}: verify model, voice, output format, and provider options"

      String.contains?(reason, "provider_http_error") ->
        "#{label}: inspect the sanitized provider HTTP reason"

      true ->
        nil
    end
  end

  defp provider_reason_action(_reason, _label), do: nil

  defp provider_proofs_cleanup do
    %{
      includes_raw_api_keys: false,
      includes_raw_prompts: false,
      includes_provider_answers: false,
      includes_artifact_bytes: false
    }
  end

  defp stringify_keys(map) when is_map(map) do
    Map.new(map, fn {key, value} -> {to_string(key), stringify_keys(value)} end)
  end

  defp stringify_keys(list) when is_list(list), do: Enum.map(list, &stringify_keys/1)
  defp stringify_keys(value) when is_boolean(value), do: value
  defp stringify_keys(value) when is_atom(value), do: to_string(value)
  defp stringify_keys(value), do: value
end
