defmodule LemonSim.Examples.Courtroom.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Opening / Closing Statements --

  @spec make_statement(String.t(), String.t()) :: Event.t()
  def make_statement(player_id, statement) do
    Event.new("make_statement", %{
      "player_id" => player_id,
      "statement" => statement
    })
  end

  # -- Prosecution / Defense Case --

  @spec call_witness(String.t(), String.t()) :: Event.t()
  def call_witness(caller_id, witness_id) do
    Event.new("call_witness", %{
      "caller_id" => caller_id,
      "witness_id" => witness_id
    })
  end

  @spec ask_question(String.t(), String.t(), String.t()) :: Event.t()
  def ask_question(asker_id, target_id, question) do
    Event.new("ask_question", %{
      "asker_id" => asker_id,
      "target_id" => target_id,
      "question" => question
    })
  end

  @spec present_evidence(String.t(), String.t()) :: Event.t()
  def present_evidence(player_id, evidence_id) do
    Event.new("present_evidence", %{
      "player_id" => player_id,
      "evidence_id" => evidence_id
    })
  end

  @spec object(String.t(), String.t()) :: Event.t()
  def object(player_id, reason) do
    Event.new("object", %{
      "player_id" => player_id,
      "reason" => reason
    })
  end

  # -- Cross Examination --

  @spec challenge_testimony(String.t(), String.t(), String.t()) :: Event.t()
  def challenge_testimony(player_id, witness_id, challenge) do
    Event.new("challenge_testimony", %{
      "player_id" => player_id,
      "witness_id" => witness_id,
      "challenge" => challenge
    })
  end

  # -- Deliberation --

  @spec jury_discuss(String.t(), String.t()) :: Event.t()
  def jury_discuss(juror_id, argument) do
    Event.new("jury_discuss", %{
      "juror_id" => juror_id,
      "argument" => argument
    })
  end

  @spec take_note(String.t(), String.t()) :: Event.t()
  def take_note(juror_id, note) do
    Event.new("take_note", %{
      "juror_id" => juror_id,
      "note" => note
    })
  end

  # -- Verdict --

  @spec cast_verdict(String.t(), String.t()) :: Event.t()
  def cast_verdict(juror_id, vote) do
    Event.new("cast_verdict", %{
      "juror_id" => juror_id,
      "vote" => vote
    })
  end

  # -- System / resolution events (generated by updater) --

  @spec statement_recorded(String.t(), String.t(), String.t()) :: Event.t()
  def statement_recorded(player_id, phase, statement) do
    Event.new("statement_recorded", %{
      "player_id" => player_id,
      "phase" => phase,
      "statement" => statement
    })
  end

  @spec witness_called(String.t(), String.t()) :: Event.t()
  def witness_called(caller_id, witness_id) do
    Event.new("witness_called", %{
      "caller_id" => caller_id,
      "witness_id" => witness_id
    })
  end

  @spec question_answered(String.t(), String.t(), String.t()) :: Event.t()
  def question_answered(asker_id, target_id, question) do
    Event.new("question_answered", %{
      "asker_id" => asker_id,
      "target_id" => target_id,
      "question" => question
    })
  end

  @spec evidence_admitted(String.t(), String.t()) :: Event.t()
  def evidence_admitted(player_id, evidence_id) do
    Event.new("evidence_admitted", %{
      "player_id" => player_id,
      "evidence_id" => evidence_id
    })
  end

  @spec objection_ruled(String.t(), String.t(), String.t()) :: Event.t()
  def objection_ruled(player_id, reason, ruling) do
    Event.new("objection_ruled", %{
      "player_id" => player_id,
      "reason" => reason,
      "ruling" => ruling
    })
  end

  @spec testimony_challenged(String.t(), String.t()) :: Event.t()
  def testimony_challenged(player_id, witness_id) do
    Event.new("testimony_challenged", %{
      "player_id" => player_id,
      "witness_id" => witness_id
    })
  end

  @spec juror_noted(String.t(), String.t()) :: Event.t()
  def juror_noted(juror_id, note) do
    Event.new("juror_noted", %{
      "juror_id" => juror_id,
      "note" => note
    })
  end

  @spec juror_discussed(String.t(), String.t()) :: Event.t()
  def juror_discussed(juror_id, argument) do
    Event.new("juror_discussed", %{
      "juror_id" => juror_id,
      "argument" => argument
    })
  end

  @spec verdict_cast(String.t(), String.t()) :: Event.t()
  def verdict_cast(juror_id, vote) do
    Event.new("verdict_cast", %{
      "juror_id" => juror_id,
      "vote" => vote
    })
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec verdict_reached(String.t(), map()) :: Event.t()
  def verdict_reached(outcome, votes) do
    Event.new("verdict_reached", %{
      "outcome" => outcome,
      "votes" => votes
    })
  end

  @spec game_over(String.t(), String.t() | nil) :: Event.t()
  def game_over(outcome, winner) do
    Event.new("game_over", %{
      "outcome" => outcome,
      "winner" => winner,
      "message" => "Trial concluded: #{outcome}"
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, player_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "player_id" => player_id,
      "reason" => reason
    })
  end
end
