defmodule LemonAutomation.SynthesisRunner do
  @moduledoc """
  Scheduled driver for the skill-synthesis draft pipeline.

  `LemonSkills.Synthesis.Pipeline` closes the learning loop (memory documents →
  linted, audited skill drafts) but nothing invoked it outside
  `mix lemon.skill draft generate`. This module is the automation caller:
  `LemonAutomation.SynthesisRunnerManager` ticks it, it invokes the pipeline,
  advances a durable ingest watermark so each pass only looks at documents
  that arrived since the last one, and records the result in
  `LemonAutomation.SynthesisMetrics` for the doctor check.

  ## Configuration

      config :lemon_automation, :synthesis_runner,
        enabled: true,
        agent_id: "default",
        interval_hours: 6,
        max_docs: 50,
        global: true,
        cwd: nil

  Kill switches, in order of bluntness: `LEMON_FEATURE_SKILL_SYNTHESIS_DRAFTS=off`
  disables the pipeline globally (drafts stop being generated by any caller);
  `enabled: false` here stops only the scheduled passes.

  Generated drafts are inert — they live in the draft store until an operator
  promotes them with `mix lemon.skill draft promote`.

  ## Durable state

  `LemonCore.Store` table `:synthesis_runner_state`, key `"agent:<agent_id>"`,
  value `%{watermark_ms: ms | nil, last_run_at_ms: ms | nil}`. The watermark
  advances to the newest `ingested_at_ms` the pass observed; the run timestamp
  advances on every attempt (including a raise or exit out of the pipeline) so
  a broken pipeline cannot hot-loop, and it survives restarts so a bounce does
  not re-run early.

  The pipeline pushes the watermark into the store query and drains
  oldest-first, so a backlog larger than `max_docs` is consumed one window per
  pass rather than skipped. A document that reliably crashes the pipeline is
  retried once per interval forever (the watermark cannot advance past it);
  bounding the retry to the interval is the guarantee here, not eventual
  progress past a poisoned document.
  """

  alias LemonAutomation.SynthesisMetrics
  alias LemonCore.Store

  require Logger

  @state_table :synthesis_runner_state

  @default_agent_id "default"
  @default_interval_hours 6
  @default_max_docs 50

  @type state :: %{watermark_ms: integer() | nil, last_run_at_ms: integer() | nil}

  @doc """
  Run one synthesis pass.

  Returns `{:ok, result}` with the pipeline run result plus the new
  `:watermark_ms`, `{:skip, reason}` when the pass was gated off, or
  `{:error, reason}` when the pipeline itself failed.

  ## Options

  Any recognised config key (see the moduledoc) overrides app env. Test seams:
  `:pipeline_mod`, `:now_ms`.
  """
  @spec run_once(keyword()) :: {:ok, map()} | {:skip, atom()} | {:error, term()}
  def run_once(opts \\ []) do
    cfg = config(opts)
    pipeline_mod = Keyword.get(opts, :pipeline_mod, LemonSkills.Synthesis.Pipeline)

    cond do
      not enabled?(cfg) ->
        {:skip, :disabled}

      not Code.ensure_loaded?(pipeline_mod) ->
        {:skip, :pipeline_unavailable}

      true ->
        run_guarded(cfg, pipeline_mod, opts)
    end
  rescue
    e -> {:error, Exception.message(e)}
  catch
    :exit, reason -> {:error, {:exit, reason}}
  end

  @doc """
  Return true when the configured interval has elapsed since the last pass.
  """
  @spec should_run_now?(keyword()) :: boolean()
  def should_run_now?(opts \\ []) do
    cfg = config(opts)

    if enabled?(cfg) do
      now_ms = now_ms(opts)
      state = get_state(agent_id(cfg))

      case state.last_run_at_ms do
        nil -> true
        last when is_integer(last) -> now_ms - last >= interval_ms(cfg)
        _ -> true
      end
    else
      false
    end
  rescue
    _ -> false
  end

  @doc """
  Return true when the router reports active sessions (defer synthesis work).
  """
  @spec active_sessions?(keyword()) :: boolean()
  def active_sessions?(opts \\ []) do
    sessions_fun = Keyword.get(opts, :active_sessions_fun)

    sessions =
      cond do
        is_function(sessions_fun, 0) ->
          sessions_fun.()

        router_mod = Keyword.get(opts, :active_sessions_mod, LemonRouter.Router) ->
          router_mod.list_active_sessions()
      end

    match?([_ | _], sessions) or match?({:error, _reason}, sessions)
  rescue
    _ -> true
  catch
    _kind, _reason -> true
  end

  @doc false
  @spec config(keyword()) :: keyword()
  def config(opts \\ []) do
    app_cfg =
      :lemon_automation
      |> Application.get_env(:synthesis_runner, [])
      |> normalize_config()

    Keyword.merge(default_config(), Keyword.merge(app_cfg, opts))
  end

  @doc """
  Read the persisted runner state for an agent.
  """
  @spec get_state(String.t()) :: state()
  def get_state(agent_id) do
    case Store.get(@state_table, state_key(agent_id)) do
      map when is_map(map) ->
        %{
          watermark_ms: optional_integer(map, :watermark_ms),
          last_run_at_ms: optional_integer(map, :last_run_at_ms)
        }

      _ ->
        %{watermark_ms: nil, last_run_at_ms: nil}
    end
  rescue
    _ -> %{watermark_ms: nil, last_run_at_ms: nil}
  catch
    :exit, _ -> %{watermark_ms: nil, last_run_at_ms: nil}
  end

  @doc """
  Overwrite the persisted runner state for an agent.
  """
  @spec put_state(String.t(), state()) :: :ok
  def put_state(agent_id, %{} = state) do
    Store.put(@state_table, state_key(agent_id), %{
      watermark_ms: Map.get(state, :watermark_ms),
      last_run_at_ms: Map.get(state, :last_run_at_ms)
    })

    :ok
  rescue
    _ -> :ok
  catch
    :exit, _ -> :ok
  end

  @doc """
  Delete the persisted runner state for an agent. Intended for tests/operators.
  """
  @spec delete_state(String.t()) :: :ok
  def delete_state(agent_id) do
    Store.delete(@state_table, state_key(agent_id))
    :ok
  rescue
    _ -> :ok
  catch
    :exit, _ -> :ok
  end

  # ── Private helpers ─────────────────────────────────────────────────────────

  # A pipeline that raises or exits must still advance the run timestamp: the
  # manager ticks once a minute and gates only on `last_run_at_ms`, so without
  # a stamp a crashing pipeline is re-invoked every tick forever. The watermark
  # is deliberately left alone so nothing is skipped once it is healthy again.
  defp run_guarded(cfg, pipeline_mod, opts) do
    do_run(cfg, pipeline_mod, opts)
  rescue
    e ->
      stamp_attempt(cfg, opts)
      Logger.warning("[SynthesisRunner] Pipeline raised: #{Exception.message(e)}")
      {:error, Exception.message(e)}
  catch
    :exit, reason ->
      stamp_attempt(cfg, opts)
      Logger.warning("[SynthesisRunner] Pipeline exited: #{inspect(reason)}")
      {:error, {:exit, reason}}
  end

  defp stamp_attempt(cfg, opts) do
    agent_id = agent_id(cfg)
    state = get_state(agent_id)
    put_state(agent_id, %{watermark_ms: state.watermark_ms, last_run_at_ms: now_ms(opts)})
  end

  defp do_run(cfg, pipeline_mod, opts) do
    agent_id = agent_id(cfg)
    now = now_ms(opts)
    state = get_state(agent_id)

    run_opts = [
      # `opt_in: true` keeps scheduled passes running for configs that still
      # pin the flag to "opt-in"; with the shipped "default-on" default it is a
      # no-op. "off" remains a kill switch either way.
      opt_in: true,
      max_docs: Keyword.get(cfg, :max_docs, @default_max_docs),
      global: Keyword.get(cfg, :global, true),
      cwd: Keyword.get(cfg, :cwd),
      # 0, not nil: `since_ms: nil` means "no watermark, take the newest
      # window" (the manual-invocation shape). A scheduled pass is always
      # watermark-driven, so the very first pass on an existing install must
      # start draining at the OLDEST document rather than jumping the watermark
      # to the newest and skipping all prior history.
      since_ms: state.watermark_ms || 0
    ]

    case pipeline_mod.run(:agent, agent_id, run_opts) do
      {:ok, result} ->
        new_watermark = max_non_nil(state.watermark_ms, Map.get(result, :latest_doc_ms))
        put_state(agent_id, %{watermark_ms: new_watermark, last_run_at_ms: now})

        if Map.get(result, :total_candidates, 0) > 0 do
          SynthesisMetrics.record_run(agent_id, result)
        end

        {:ok, Map.put(result, :watermark_ms, new_watermark)}

      {:error, :feature_disabled} ->
        # Stamp the attempt so the manager does not tick the pipeline every
        # minute while the flag is off; leave the watermark alone so nothing is
        # skipped once the flag comes back.
        put_state(agent_id, %{watermark_ms: state.watermark_ms, last_run_at_ms: now})
        {:skip, :feature_disabled}

      {:error, reason} ->
        put_state(agent_id, %{watermark_ms: state.watermark_ms, last_run_at_ms: now})
        Logger.warning("[SynthesisRunner] Pipeline failed: #{inspect(reason)}")
        {:error, reason}

      other ->
        put_state(agent_id, %{watermark_ms: state.watermark_ms, last_run_at_ms: now})
        {:error, {:unexpected_pipeline_result, other}}
    end
  end

  defp max_non_nil(nil, nil), do: nil
  defp max_non_nil(nil, b) when is_integer(b), do: b
  defp max_non_nil(a, nil) when is_integer(a), do: a
  defp max_non_nil(a, b) when is_integer(a) and is_integer(b), do: max(a, b)
  defp max_non_nil(a, _b), do: a

  defp enabled?(cfg), do: Keyword.get(cfg, :enabled, true) == true

  defp agent_id(cfg), do: to_string(Keyword.get(cfg, :agent_id, @default_agent_id))

  defp state_key(agent_id), do: "agent:" <> to_string(agent_id)

  defp now_ms(opts), do: Keyword.get(opts, :now_ms) || LemonCore.Clock.now_ms()

  defp interval_ms(cfg) do
    positive_integer(cfg, :interval_hours, @default_interval_hours) * 3_600_000
  end

  defp default_config do
    [
      enabled: true,
      agent_id: @default_agent_id,
      interval_hours: @default_interval_hours,
      max_docs: @default_max_docs,
      global: true,
      cwd: nil
    ]
  end

  defp normalize_config(config) when is_map(config) do
    Enum.flat_map(config, fn {key, value} ->
      case normalize_key(key) do
        key when is_atom(key) -> [{key, value}]
        _ -> []
      end
    end)
  end

  defp normalize_config(config) when is_list(config), do: config
  defp normalize_config(_), do: []

  defp normalize_key(key) when is_atom(key), do: key

  defp normalize_key(key) when is_binary(key) do
    case key do
      "enabled" -> :enabled
      "agent_id" -> :agent_id
      "interval_hours" -> :interval_hours
      "max_docs" -> :max_docs
      "global" -> :global
      "cwd" -> :cwd
      _ -> key
    end
  end

  defp positive_integer(cfg, key, default) do
    case Keyword.get(cfg, key, default) do
      value when is_integer(value) and value > 0 -> value
      value when is_binary(value) -> parse_positive_integer(value, default)
      _ -> default
    end
  end

  defp parse_positive_integer(value, default) do
    case Integer.parse(value) do
      {parsed, ""} when parsed > 0 -> parsed
      _ -> default
    end
  end

  defp optional_integer(map, key) do
    case Map.get(map, key) || Map.get(map, Atom.to_string(key)) do
      value when is_integer(value) -> value
      _ -> nil
    end
  end
end
