defmodule CodingAgent.Tools.ExecuteCode.PythonShim do
  @moduledoc """
  Renders the stdlib-only python shim (`lemon_tools.py`) a script imports to
  reach the Lemon tool layer, plus the one-line import prelude prepended to
  the submitted script.

  Pure functions — no I/O — so the generated text is fully testable and, given
  the same configuration and tool list, byte-identical between runs.

  The shim speaks the file-RPC protocol: a request is written to
  `req-<id>.json.tmp` and atomically `os.replace`d onto `req-<id>.json`; the
  response appears the same way at `res-<id>.json`. Every request carries the
  per-cell bearer token configured by `_configure/2`. Only `json`, `os`,
  `threading`, `time`, and `concurrent.futures` are used, so the shim works on
  any stock python3.

  Besides the per-tool stubs the module always defines three helpers:

    * `text(s)` — the result channel. Each call atomically flushes a numbered
      `text-<n>.json` block into the rpc dir (write-through, never at exit, so
      blocks survive a timeout or kill) under a shared lock, within a baked-in
      byte budget; an over-budget call raises `ToolError` and leaves the
      previously flushed blocks intact.
    * `notify(msg)` — the streaming side channel. Fire-and-forget numbered
      `notify-<n>.json` frames; the Elixir pump consumes and forwards them as
      partial updates, never as responses.
    * `batch(calls)` — parallel helper calls through a bounded
      `ThreadPoolExecutor`, each worker running the plain blocking `_call`.
      All calls are waited out before any error is re-raised, so a mixed
      batch never tears its side effects.
  """

  alias CodingAgent.Tools.ExecuteCode.Config

  # Fixed emission order, independent of how config lists the tools, so the
  # generated prelude stays deterministic.
  @stub_order ~w(read grep find ls webfetch)

  # Must match `Config`'s `@default_max_text_bytes`; both are pinned by tests.
  @default_text_budget 65_536

  # Cap on the ThreadPoolExecutor used by batch(): any higher fan-out just
  # queues python-side, because the Elixir pump bounds real dispatch
  # concurrency at `max_parallel_rpc`.
  @batch_max_workers 16

  @doc """
  Render an unconfigured, authority-free `lemon_tools.py` module defining a
  stub per enabled tool, the `text()`/`notify()` result channels, and
  `batch()` for parallel helper calls.

  Persistent Python sessions stage this source once and rotate its bridge
  credentials per cell with `_configure/2`. The `text()` byte budget is baked
  into the module source, so a live kernel keeps the budget it was first
  staged with until it is reset or reaped.
  """
  @spec render_module(tools :: [String.t()], max_text_bytes :: pos_integer()) :: String.t()
  def render_module(tools, max_text_bytes \\ @default_text_budget)
      when is_list(tools) and is_integer(max_text_bytes) and max_text_bytes > 0 do
    enabled = enabled_tools(tools)

    header = """
    # Generated by Lemon execute_code. Do not edit.
    import json, os, threading, time
    from concurrent.futures import ThreadPoolExecutor

    _RPC_DIR = None
    _TOKEN = None
    _SEQ = 0
    _TEXT_SEQ = 0
    _NOTIFY_SEQ = 0
    _TEXT_BYTES = 0
    _TEXT_BUDGET = #{max_text_bytes}
    _POLL_S = 0.02
    _BATCH_MAX_WORKERS = #{@batch_max_workers}
    _LOCK = threading.Lock()


    def _configure(rpc_dir, token):
        global _RPC_DIR, _TOKEN
        _RPC_DIR = rpc_dir
        _TOKEN = token

    class ToolError(Exception):
        pass


    def _next_req_id():
        global _SEQ
        with _LOCK:
            _SEQ += 1
            return _SEQ


    def _atomic_write(rpc_dir, final_name, payload):
        # Same publication discipline as every protocol file: an O_EXCL tmp at
        # 0600, verified owner-only, renamed into place so a reader never sees
        # a half-written frame and a planted symlink is replaced, not followed.
        tmp = os.path.join(rpc_dir, final_name + ".tmp")
        final = os.path.join(rpc_dir, final_name)
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
        try:
            fd = os.open(tmp, flags, 0o600)
        except FileExistsError:
            raise ToolError("rpc temp for %s already exists" % final_name)
        if (os.fstat(fd).st_mode & 0o777) != 0o600:
            os.close(fd)
            os.unlink(tmp)
            raise ToolError("rpc temp for %s is not owner-only" % final_name)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                json.dump(payload, f)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        os.replace(tmp, final)


    def text(s):
        # Result channel: each block is flushed to disk as it is written
        # (never at exit), so everything emitted before a timeout or kill
        # still reaches the tool result. Numbering and the byte budget are
        # lock-guarded because batch() workers call this from many threads.
        global _TEXT_SEQ, _TEXT_BYTES
        if s is None:
            s = ""
        elif not isinstance(s, str):
            s = str(s)
        payload = s.encode("utf-8")
        with _LOCK:
            if _TEXT_BYTES + len(payload) > _TEXT_BUDGET:
                raise ToolError(
                    "text() byte budget exceeded (%d bytes accumulated, %d more requested, cap %d)"
                    % (_TEXT_BYTES, len(payload), _TEXT_BUDGET)
                )
            _TEXT_BYTES += len(payload)
            _TEXT_SEQ += 1
            seq = _TEXT_SEQ
        rpc_dir = _RPC_DIR
        if not rpc_dir:
            raise ToolError("lemon_tools is not configured for this cell")
        _atomic_write(rpc_dir, "text-%d.json" % seq, {"n": seq, "text": s})


    def notify(msg):
        # Streaming side channel: fire-and-forget, never blocks for a reply.
        if msg is None:
            msg = ""
        elif not isinstance(msg, str):
            msg = str(msg)
        global _NOTIFY_SEQ
        with _LOCK:
            _NOTIFY_SEQ += 1
            seq = _NOTIFY_SEQ
        rpc_dir = _RPC_DIR
        if not rpc_dir:
            raise ToolError("lemon_tools is not configured for this cell")
        _atomic_write(rpc_dir, "notify-%d.json" % seq, {"n": seq, "msg": msg})


    def batch(calls):
        # Parallel helper calls: each worker runs the plain blocking _call, so
        # ids stay unique (the counter is lock-guarded) and a failure surfaces
        # as the same ToolError a plain call raises. Every call is waited out
        # before any exception is re-raised, so side effects are never torn.
        calls = list(calls)
        if not calls:
            return []
        workers = min(len(calls), _BATCH_MAX_WORKERS)
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = [pool.submit(_call, tool, params or {}) for tool, params in calls]
            results = []
            first_error = None
            for future in futures:
                try:
                    results.append(future.result())
                except BaseException as exc:
                    results.append(None)
                    if first_error is None:
                        first_error = exc
        if first_error is not None:
            raise first_error
        return results


    def _call(tool, params):
        rpc_dir = _RPC_DIR
        token = _TOKEN
        if not rpc_dir or not token:
            raise ToolError("lemon_tools is not configured for this cell")
        req_id = _next_req_id()
        params = {k: v for k, v in params.items() if v is not None}
        _atomic_write(
            rpc_dir,
            "req-%d.json" % req_id,
            {"id": req_id, "token": token, "tool": tool, "params": params},
        )
        res_path = os.path.join(rpc_dir, "res-%d.json" % req_id)
        while True:
            if os.path.exists(res_path):
                with open(res_path) as f:
                    res = json.load(f)
                if res.get("ok"):
                    return res.get("content", "")
                raise ToolError(res.get("error") or "tool call failed")
            time.sleep(_POLL_S)
    """

    Enum.reduce(enabled, header, fn name, acc -> acc <> "\n\n" <> stub(name) end)
  end

  @doc """
  Render an unconfigured `lemon_tools.py` with the default text budget.

  Kept for the one-shot compatibility path; persistent callers should use
  `render_module/2` to make the absence of initial bridge authority and the
  baked budget explicit.
  """
  @spec render_prelude(tools :: [String.t()]) :: String.t()
  def render_prelude(tools) when is_list(tools), do: render_module(tools)

  @doc """
  Render `lemon_tools.py` preconfigured for a one-shot `execute_code` run.

  `max_text_bytes` defaults to #{@default_text_budget} and is baked into the
  module source as the `text()` budget.
  """
  @spec render_prelude(
          rpc_dir :: String.t(),
          token :: String.t(),
          tools :: [String.t()],
          max_text_bytes :: pos_integer()
        ) :: String.t()
  def render_prelude(rpc_dir, token, tools, max_text_bytes \\ @default_text_budget)
      when is_binary(rpc_dir) and is_binary(token) and is_list(tools) do
    render_module(tools, max_text_bytes) <>
      "\n\n_configure(#{Jason.encode!(rpc_dir)}, #{Jason.encode!(token)})\n"
  end

  @doc """
  The single import line prepended to the submitted script.
  """
  @spec import_line(tools :: [String.t()]) :: String.t()
  def import_line(tools \\ Config.allowlist()) when is_list(tools) do
    # The result-channel helpers are part of the module itself, not the
    # tool-gated stubs, so they import even when `tools` narrows to none.
    names = ["ToolError" | enabled_tools(tools)] ++ ~w(text notify batch)
    "from lemon_tools import " <> Enum.join(names, ", ")
  end

  @doc """
  Prepend the import line to the user script.

  Exactly one line is injected, so python traceback line numbers are offset by
  one — the tool description says so.
  """
  @spec render_script(user_script :: String.t(), tools :: [String.t()]) :: String.t()
  def render_script(user_script, tools \\ Config.allowlist()) when is_binary(user_script) do
    import_line(tools) <> "\n" <> user_script
  end

  defp enabled_tools(tools), do: Enum.filter(@stub_order, &(&1 in tools))

  defp stub("read") do
    """
    def read(path, offset=None, limit=None):
        return _call("read", {"path": path, "offset": offset, "limit": limit})
    """
    |> String.trim_trailing()
  end

  defp stub("grep") do
    """
    def grep(pattern, path=None, glob=None, case_sensitive=None, literal=None, context_lines=None, max_results=None):
        return _call("grep", {"pattern": pattern, "path": path, "glob": glob, "case_sensitive": case_sensitive, "literal": literal, "context_lines": context_lines, "max_results": max_results})
    """
    |> String.trim_trailing()
  end

  defp stub("find") do
    """
    def find(pattern, path=None, type=None, max_depth=None, max_results=None, hidden=None):
        return _call("find", {"pattern": pattern, "path": path, "type": type, "max_depth": max_depth, "max_results": max_results, "hidden": hidden})
    """
    |> String.trim_trailing()
  end

  defp stub("ls") do
    """
    def ls(path=None, all=None, long=None, recursive=None, max_depth=None, max_entries=None):
        return _call("ls", {"path": path, "all": all, "long": long, "recursive": recursive, "max_depth": max_depth, "max_entries": max_entries})
    """
    |> String.trim_trailing()
  end

  defp stub("webfetch") do
    """
    def webfetch(url, extract_mode=None, max_chars=None):
        return _call("webfetch", {"url": url, "extractMode": extract_mode, "maxChars": max_chars})
    """
    |> String.trim_trailing()
  end
end
