defmodule CodingAgent.Tools.ExecuteCode.PythonShim do
  @moduledoc """
  Renders the stdlib-only python shim (`lemon_tools.py`) a script imports to
  reach the Lemon tool layer, plus the one-line import prelude prepended to the
  submitted script.

  Pure functions — no I/O — so the generated text is fully testable and, given
  the same rpc dir and tool list, byte-identical between runs.

  The shim speaks the file-RPC protocol: a request is written to
  `req-<id>.json.tmp` and atomically `os.replace`d onto `req-<id>.json`; the
  response appears the same way at `res-<id>.json`. Only `json`, `os`, and
  `time` are used, so the shim works on any stock python3.
  """

  alias CodingAgent.Tools.ExecuteCode.Config

  # Fixed emission order, independent of how config lists the tools, so the
  # generated prelude stays deterministic.
  @stub_order ~w(read grep find ls webfetch)

  @doc """
  Render `lemon_tools.py` for `rpc_dir`, defining a stub per enabled tool.
  """
  @spec render_prelude(rpc_dir :: String.t(), tools :: [String.t()]) :: String.t()
  def render_prelude(rpc_dir, tools) when is_binary(rpc_dir) and is_list(tools) do
    enabled = enabled_tools(tools)

    header = """
    # Generated by Lemon execute_code. Do not edit.
    import json, os, time

    _RPC_DIR = #{Jason.encode!(rpc_dir)}
    _SEQ = 0
    _POLL_S = 0.02


    class ToolError(Exception):
        pass


    def _call(tool, params):
        global _SEQ
        _SEQ += 1
        req_id = _SEQ
        params = {k: v for k, v in params.items() if v is not None}
        tmp = os.path.join(_RPC_DIR, "req-%d.json.tmp" % req_id)
        final = os.path.join(_RPC_DIR, "req-%d.json" % req_id)
        with open(tmp, "w") as f:
            json.dump({"id": req_id, "tool": tool, "params": params}, f)
        os.replace(tmp, final)
        res_path = os.path.join(_RPC_DIR, "res-%d.json" % req_id)
        while True:
            if os.path.exists(res_path):
                with open(res_path) as f:
                    res = json.load(f)
                if res.get("ok"):
                    return res.get("content", "")
                raise ToolError(res.get("error") or "tool call failed")
            time.sleep(_POLL_S)
    """

    Enum.reduce(enabled, header, fn name, acc -> acc <> "\n\n" <> stub(name) end)
  end

  @doc """
  The single import line prepended to the submitted script.
  """
  @spec import_line(tools :: [String.t()]) :: String.t()
  def import_line(tools \\ Config.allowlist()) when is_list(tools) do
    names = ["ToolError" | enabled_tools(tools)]
    "from lemon_tools import " <> Enum.join(names, ", ")
  end

  @doc """
  Prepend the import line to the user script.

  Exactly one line is injected, so python traceback line numbers are offset by
  one — the tool description says so.
  """
  @spec render_script(user_script :: String.t(), tools :: [String.t()]) :: String.t()
  def render_script(user_script, tools \\ Config.allowlist()) when is_binary(user_script) do
    import_line(tools) <> "\n" <> user_script
  end

  defp enabled_tools(tools), do: Enum.filter(@stub_order, &(&1 in tools))

  defp stub("read") do
    """
    def read(path, offset=None, limit=None):
        return _call("read", {"path": path, "offset": offset, "limit": limit})
    """
    |> String.trim_trailing()
  end

  defp stub("grep") do
    """
    def grep(pattern, path=None, glob=None, case_sensitive=None, literal=None, context_lines=None, max_results=None):
        return _call("grep", {"pattern": pattern, "path": path, "glob": glob, "case_sensitive": case_sensitive, "literal": literal, "context_lines": context_lines, "max_results": max_results})
    """
    |> String.trim_trailing()
  end

  defp stub("find") do
    """
    def find(pattern, path=None, type=None, max_depth=None, max_results=None, hidden=None):
        return _call("find", {"pattern": pattern, "path": path, "type": type, "max_depth": max_depth, "max_results": max_results, "hidden": hidden})
    """
    |> String.trim_trailing()
  end

  defp stub("ls") do
    """
    def ls(path=None, all=None, long=None, recursive=None, max_depth=None, max_entries=None):
        return _call("ls", {"path": path, "all": all, "long": long, "recursive": recursive, "max_depth": max_depth, "max_entries": max_entries})
    """
    |> String.trim_trailing()
  end

  defp stub("webfetch") do
    """
    def webfetch(url, extract_mode=None, max_chars=None):
        return _call("webfetch", {"url": url, "extractMode": extract_mode, "maxChars": max_chars})
    """
    |> String.trim_trailing()
  end
end
