#!/usr/bin/env python3
"""Lemon persistent python kernel runner (protocol v1).

The parent (an Erlang port owner) spawns this script with the resolved
interpreter, unbuffered, from a private ``0700`` workspace that also holds
``lemon_tools.py``. All protocol travels over the *original* stdout
descriptor, which is duplicated early into a non-inheritable control fd; fd 1
and fd 2 are then re-pointed at capture pipes so user stdout/stderr — however
produced — can never be mistaken for control frames. Protocol is therefore
typed and request-correlated, and the model-facing output contract stays
"only what the script prints".

Parent requests arrive as UTF-8 NDJSON on stdin:

    {"v":1,"type":"init","cwd":"/canonical/path"}
    {"v":1,"type":"eval","id":"cell-id","code":"...","cwd":"...","bridge":{...}}
    {"v":1,"type":"shutdown"}

Every emitted frame is ``RS + b"lemon-python\\t" + JSON + newline`` on the
control fd: ``ready`` (answers ``init``), ``started``/``stream``/``exception``
/``done`` (one ``done`` per ``started``), ``fatal`` (malformed request; the
process then exits non-zero), and ``bye`` (answers ``shutdown``; exit 0).
Stream payloads are base64 of at most 64 KiB of raw bytes. The host rejects
frames over 256 KiB, so chunking stays well inside that budget.

Semantics per the plan:

- exactly one globals namespace for the process lifetime; ordinary
  exceptions, ``SystemExit``, and rejected ``input()`` keep it,
- ``input()``/stdin reads raise an explicit unsupported-input error,
- the keyed cwd is restored before every cell,
- tracebacks are filtered of runner frames,
- code that already produced ``started`` is never replayed by this process,
- a POSIX session/process group is started when safe, and descendants never
  inherit the control fd (they do inherit the captured fd 1/2 on purpose).

Only the python3 standard library is used.
"""

import base64
import builtins
import importlib
import inspect
import io
import json
import os
import select
import sys
import threading
import time
import traceback

PROTOCOL_VERSION = 1
FRAME_PREFIX = b"\x1elemon-python\t"
CELL_FILENAME = "<cell>"

# Stream frames carry base64 of at most STREAM_CHUNK raw bytes, keeping every
# frame far below the host-side 256 KiB cap.
STREAM_CHUNK = 64 * 1024

# Exception frames must remain materially smaller than the host's 256 KiB
# frame cap even when exception classes, messages, or traceback details are
# hostile. These limits include JSON string escaping and leave substantial
# headroom for frame metadata and the control prefix.
EXCEPTION_NAME_JSON_BYTES = 4 * 1024
EXCEPTION_MESSAGE_JSON_BYTES = 48 * 1024
EXCEPTION_TRACEBACK_JSON_BYTES = 80 * 1024
EXCEPTION_TRUNCATION_MARKER = "... [truncated]"

# After a cell's code returns, its pipes are declared drained once both have
# stayed quiet for QUIET_SECONDS (and no frame write is in flight), bounded by
# MAX_QUIESCE_SECONDS so a lingering user thread cannot stall the cell.
QUIET_SECONDS = 0.05
MAX_QUIESCE_SECONDS = 0.5

EXIT_OK = 0
EXIT_FATAL = 70
EXIT_CONTROL_LOST = 75

# Names copied from lemon_tools into the persistent namespace on bridged
# cells; mirrors the per-call import line generated by PythonShim.
HELPER_NAMES = (
    "ToolError",
    "read",
    "grep",
    "find",
    "ls",
    "webfetch",
    "text",
    "notify",
    "batch",
)


class ProtocolError(Exception):
    """A parent request violated the protocol; the kernel must die."""


class UnsupportedInput(RuntimeError):
    """Raised when cell code tries to read interactive input."""


_INPUT_ERROR = (
    "input() is not supported: the lemon persistent python kernel has no "
    "interactive stdin; read from a file or call a helper function instead"
)

_RUNNER_PATH = os.path.realpath(__file__)
_RUNNER_DIR = os.path.dirname(_RUNNER_PATH)

_write_lock = threading.Lock()
_cell_lock = threading.Lock()
_inflight_lock = threading.Lock()
_inflight_writes = 0
_open_cell = None
_drainers = []

_control_fd = None
_base_cwd = None
_namespace = {"__name__": "__main__", "__doc__": None, "__builtins__": builtins}


# ---------------------------------------------------------------------------
# frames
# ---------------------------------------------------------------------------


def _hard_exit(code):
    # The control channel is gone or unusable; nothing the interpreter does
    # from here can be observed, so do not run user atexit hooks.
    os._exit(code)


def _frame_data(payload):
    return FRAME_PREFIX + json.dumps(payload, separators=(",", ":")).encode("utf-8") + b"\n"


def _write_data(data):
    view = memoryview(data)
    while view:
        try:
            written = os.write(_control_fd, view)
        except OSError:
            _hard_exit(EXIT_CONTROL_LOST)
        view = view[written:]


def _write_frame(payload):
    with _write_lock:
        _write_data(_frame_data(payload))


def _write_stream_frame(cell_id, payload):
    """Write a stream frame only while its cell remains open.

    Closing a cell and writing its ``done`` frame share ``_write_lock`` with
    this check. Thus a stream either wins the lock and precedes ``done``, or
    loses it and is dropped after the cell is no longer attributable.
    """
    data = _frame_data(payload)
    with _write_lock:
        if _current_cell() != cell_id:
            return
        _write_data(data)


def _current_cell():
    with _cell_lock:
        return _open_cell


def _set_open_cell(cell_id):
    global _open_cell
    with _cell_lock:
        _open_cell = cell_id


def _begin_stream_write():
    """Atomically claim an open cell before a drainer emits for it."""
    global _inflight_writes
    with _cell_lock:
        cell_id = _open_cell
        if cell_id is None:
            return None
        with _inflight_lock:
            _inflight_writes += 1
        return cell_id


def _end_stream_write():
    global _inflight_writes
    with _inflight_lock:
        _inflight_writes -= 1


def _close_cell_and_emit_done(cell_id):
    """Remove attribution before the terminal frame, without reordering."""
    with _write_lock:
        _set_open_cell(None)
        _write_data(_frame_data({"v": PROTOCOL_VERSION, "type": "done", "id": cell_id}))


def _emit_stream(cell_id, stream_name, data):
    if cell_id is None:
        # Bytes from a user thread that outlived its cell are dropped: they
        # cannot be attributed to a live cell and must never touch the
        # control channel unframed.
        return
    for start in range(0, len(data), STREAM_CHUNK):
        chunk = data[start : start + STREAM_CHUNK]
        _write_stream_frame(
            cell_id,
            {
                "v": PROTOCOL_VERSION,
                "type": "stream",
                "id": cell_id,
                "stream": stream_name,
                "data": base64.b64encode(chunk).decode("ascii"),
            },
        )


# ---------------------------------------------------------------------------
# capture pipes
# ---------------------------------------------------------------------------


class _Drainer(threading.Thread):
    """Pumps one capture pipe to stream frames while cell code runs.

    Draining concurrently matters: a child process inheriting fd 1/2 writing
    more than the pipe buffer would otherwise deadlock against its waiting
    parent.
    """

    def __init__(self, fd, stream_name):
        super().__init__(daemon=True, name="lemon-drain-" + stream_name)
        self.fd = fd
        self.stream_name = stream_name
        self.last_data = 0.0
        # Set whenever a poll observed the pipe empty, cleared on every read;
        # quiescing waits for "empty was observed after the last byte".
        self.quiet_since = time.monotonic()
        self.stopping = threading.Event()

    def run(self):
        if os.name == "posix":
            self._run_select()
        else:
            # select() does not accept pipes on Windows; fall back to
            # blocking reads (quiesce there is a bounded wait instead of a
            # quiet-window check).
            self._run_blocking()

    def _run_select(self):
        while not self.stopping.is_set():
            try:
                readable, _, _ = select.select([self.fd], [], [], 0.01)
            except (OSError, ValueError):
                return
            if self.fd in readable:
                if not self._read_and_emit():
                    return
            else:
                self.quiet_since = time.monotonic()

    def _run_blocking(self):
        while not self.stopping.is_set():
            if not self._read_and_emit():
                return

    def _read_and_emit(self):
        try:
            data = os.read(self.fd, STREAM_CHUNK)
        except (OSError, ValueError):
            return False
        if not data:
            # The write end only closes at process teardown; an early EOF
            # means the pipe is unusable.
            return False
        self.last_data = time.monotonic()
        self.quiet_since = None
        cell_id = _begin_stream_write()
        if cell_id is None:
            return True
        try:
            _emit_stream(cell_id, self.stream_name, data)
        finally:
            _end_stream_write()
        return True


def _setup_descriptors():
    global _control_fd
    try:
        os.setsid()
    except (AttributeError, OSError):
        # Already a group leader (or unsupported platform): the parent still
        # terminates the whole tree on teardown.
        pass

    _control_fd = os.dup(1)
    for fd in (_control_fd, 0):
        # The control channel and the request channel must not leak into
        # descendants: children inheriting them could forge or steal frames.
        try:
            os.set_inheritable(fd, False)
        except (AttributeError, OSError):
            pass

    out_r, out_w = os.pipe()
    err_r, err_w = os.pipe()
    for fd in (out_r, err_r):
        # Read ends stay process-private; fd 1/2 (dup2'd below) keep their
        # inheritable flag so user child processes keep writing captured
        # output.
        try:
            os.set_inheritable(fd, False)
        except (AttributeError, OSError):
            pass
    os.dup2(out_w, 1)
    os.dup2(err_w, 2)
    os.close(out_w)
    os.close(err_w)

    _drainers.extend([_Drainer(out_r, "stdout"), _Drainer(err_r, "stderr")])
    for drainer in _drainers:
        drainer.start()


def _flush_python_streams():
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.flush()
        except Exception:
            pass


def _quiesce():
    """Wait, for a bounded interval, for in-flight stream writes to finish.

    All platforms wait for writes already claimed by a drainer. POSIX adds a
    post-flush empty-pipe observation; Windows cannot select pipes, so its
    blocking drainers have no equivalent quiet signal. The later close gate
    still drops any bytes a lingering thread writes after this bound.
    """
    _flush_python_streams()
    for drainer in _drainers:
        drainer.quiet_since = None

    deadline = time.monotonic() + MAX_QUIESCE_SECONDS
    while True:
        with _inflight_lock:
            writes_drained = _inflight_writes == 0

        if os.name == "posix":
            settled = writes_drained and all(
                drainer.quiet_since is not None and drainer.quiet_since > drainer.last_data
                for drainer in _drainers
            )
        else:
            settled = writes_drained

        if settled or time.monotonic() >= deadline:
            return
        time.sleep(0.002)



def _detach_user_streams():
    """Point fd 1/2 at devnull so interpreter-exit flushes cannot block."""
    try:
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, 1)
        os.dup2(devnull, 2)
        if devnull > 2:
            os.close(devnull)
    except OSError:
        pass


def _stop_pumps():
    for drainer in _drainers:
        drainer.stopping.set()
    _detach_user_streams()


# ---------------------------------------------------------------------------
# input rejection
# ---------------------------------------------------------------------------


class _ClosedStdin:
    """A non-readable stdin stand-in: reading it is an explicit error."""

    encoding = "utf-8"
    errors = "replace"

    def readable(self):
        return False

    def writable(self):
        return False

    def seekable(self):
        return False

    def isatty(self):
        return False

    @property
    def closed(self):
        return False

    def close(self):
        pass

    def fileno(self):
        raise io.UnsupportedOperation("stdin is not available in the lemon python kernel")

    def read(self, *args):
        raise UnsupportedInput(_INPUT_ERROR)

    def readline(self, *args):
        raise UnsupportedInput(_INPUT_ERROR)

    def readlines(self, *args):
        raise UnsupportedInput(_INPUT_ERROR)

    def __iter__(self):
        return self

    def __next__(self):
        raise UnsupportedInput(_INPUT_ERROR)


def _reject_input(prompt=""):
    raise UnsupportedInput(
        _INPUT_ERROR if prompt == "" else "%s\n%s" % (_safe_str(prompt), _INPUT_ERROR)
    )


def _install_input_rejection():
    builtins.input = _reject_input
    sys.stdin = _ClosedStdin()
    sys.__stdin__ = sys.stdin


# ---------------------------------------------------------------------------
# exceptions
# ---------------------------------------------------------------------------


def _safe_str(value):
    try:
        return str(value)
    except Exception:
        return "<unprintable %s>" % type(value).__name__


def _unicode_scalar_safe_text(value):
    """Replace lone UTF-16 surrogates, which JSON decoders must reject."""
    if not any(0xD800 <= ord(char) <= 0xDFFF for char in value):
        return value

    return "".join(
        "\uFFFD" if 0xD800 <= ord(char) <= 0xDFFF else char for char in value
    )


def _json_escaped_character_size(char):
    """Return the byte count `json.dumps(char)` contributes inside quotes."""
    codepoint = ord(char)
    if char in ('"', "\\", "\b", "\f", "\n", "\r", "\t"):
        return 2
    if codepoint <= 0x1F:
        return 6
    if codepoint <= 0x7E:
        return 1
    if codepoint <= 0xFFFF:
        return 6
    return 12


def _bounded_exception_text(value, max_json_bytes):
    """Limit a JSON string without splitting Unicode or hiding truncation."""
    value = _unicode_scalar_safe_text(value)

    marker_bytes = sum(_json_escaped_character_size(char) for char in EXCEPTION_TRUNCATION_MARKER)
    content_limit = max_json_bytes - 2
    used = 0

    for index, char in enumerate(value):
        char_bytes = _json_escaped_character_size(char)
        if used + char_bytes > content_limit:
            prefix_limit = content_limit - marker_bytes
            prefix_used = 0
            prefix_end = 0

            for prefix_end, prefix_char in enumerate(value):
                prefix_char_bytes = _json_escaped_character_size(prefix_char)
                if prefix_used + prefix_char_bytes > prefix_limit:
                    break
                prefix_used += prefix_char_bytes
            else:
                prefix_end = len(value)

            return value[:prefix_end] + EXCEPTION_TRUNCATION_MARKER
        used += char_bytes

    return value


def _is_runner_frame(filename):
    try:
        return os.path.realpath(filename) == _RUNNER_PATH
    except (OSError, TypeError):
        return False


def _format_traceback(exc, name, message, unbounded_message):
    """Format a bounded user traceback without runner frames."""
    entries = []
    tb = exc.__traceback__
    while tb is not None:
        code = tb.tb_frame.f_code
        if not _is_runner_frame(code.co_filename):
            entries.append(
                (
                    _bounded_exception_text(code.co_filename, EXCEPTION_NAME_JSON_BYTES),
                    tb.tb_lineno,
                    _bounded_exception_text(code.co_name, EXCEPTION_NAME_JSON_BYTES),
                    None,
                )
            )
        tb = tb.tb_next

    lines = []
    if entries:
        lines.append("Traceback (most recent call last):\n")
        lines.extend(traceback.format_list(entries))
    if name == type(exc).__name__ and message == unbounded_message:
        lines.extend(traceback.format_exception_only(type(exc), exc))
    else:
        lines.append("%s: %s" % (name, message))
    return "".join(lines).rstrip("\n")


def _safe_format_traceback(exc, name, message, unbounded_message):
    try:
        traceback_text = _format_traceback(exc, name, message, unbounded_message)
    except Exception:
        traceback_text = "%s: <unformattable exception>" % name
    return _bounded_exception_text(traceback_text, EXCEPTION_TRACEBACK_JSON_BYTES)


def _exception_kind(exc):
    if isinstance(exc, UnsupportedInput):
        return "unsupported_input"
    if isinstance(exc, SystemExit):
        return "system_exit"
    if isinstance(exc, KeyboardInterrupt):
        return "interrupted"
    return "error"


def _system_exit_message(exc):
    if exc.code is None:
        return "SystemExit"
    if isinstance(exc.code, bool):
        return "SystemExit: %s" % exc.code
    if isinstance(exc.code, int):
        return "SystemExit: %d" % exc.code
    return "SystemExit: %s" % _safe_str(exc.code)


def _emit_exception(cell_id, exc):
    name = _bounded_exception_text(type(exc).__name__, EXCEPTION_NAME_JSON_BYTES)
    if isinstance(exc, SystemExit):
        unbounded_message = _system_exit_message(exc)
    else:
        unbounded_message = _safe_str(exc)
    message = _bounded_exception_text(unbounded_message, EXCEPTION_MESSAGE_JSON_BYTES)
    _write_frame(
        {
            "v": PROTOCOL_VERSION,
            "type": "exception",
            "id": cell_id,
            "kind": _exception_kind(exc),
            "name": name,
            "message": message,
            "traceback": _safe_format_traceback(exc, name, message, unbounded_message),
        }
    )


# ---------------------------------------------------------------------------
# cells
# ---------------------------------------------------------------------------


def _configure_bridge(bridge, cell_id):
    if not isinstance(bridge, dict):
        raise RuntimeError("eval bridge must be an object with dir and token")
    directory = bridge.get("dir")
    token = bridge.get("token")
    if not isinstance(directory, str) or not directory:
        raise RuntimeError("eval bridge is missing its dir")
    if not isinstance(token, str) or not token:
        raise RuntimeError("eval bridge is missing its token")

    try:
        module = importlib.import_module("lemon_tools")
    except ImportError as exc:
        raise RuntimeError(
            "lemon_tools was not staged next to the runner; helper calls are unavailable"
        ) from exc

    # The shim rotates per-cell credentials (and, since per-cell budgets,
    # resets the text accumulator and counters). Older shims bake the rpc dir
    # in at render time and have nothing to configure; pass only the
    # arguments the staged shim accepts so either generation works.
    configure = getattr(module, "_configure", None)
    if configure is not None:
        _invoke_configure(configure, directory, token, bridge.get("max_text_bytes"), cell_id)

    _namespace["lemon_tools"] = module
    for name in HELPER_NAMES:
        if hasattr(module, name):
            _namespace[name] = getattr(module, name)


def _invoke_configure(configure, directory, token, budget, cell_id):
    try:
        arity = len(inspect.signature(configure).parameters)
    except (TypeError, ValueError):
        arity = 2

    args = [directory, token]
    if arity >= 3:
        args.append(budget if isinstance(budget, int) and budget > 0 else None)
    if arity >= 4:
        args.append(cell_id)
    configure(*args)


def _install_thread_cell_tags():
    """Make threads inherit the cell generation of the thread that created them.

    lemon_tools refuses bridge calls from threads tagged with an earlier
    cell (see `_live_bridge` in the shim), so a thread a finished cell left
    behind can neither spend a later cell's text budget nor write frames into
    its rpc directory.

    The tag is captured in `Thread.__init__` — at CONSTRUCTION time, in the
    creating thread — and children inherit their creator's generation. A
    start-time stamp could be bypassed: a stale cell-1 thread can wait for
    cell 2 and then spawn, and the spawn would be stamped with cell 2 (the
    *current* cell) rather than the stale thread that caused it. With
    construction-time inheritance, a stale thread's descendants carry the
    stale generation forever and are refused by the bridge.

    The main thread (and any thread without a tag, e.g. ones this runner
    starts outside any cell) has no generation, so its children fall back to
    the currently open cell — exactly the behavior runner-internal threads
    always had.
    """
    if getattr(threading.Thread.__init__, "_lemon_tagged", False):
        return

    original_init = threading.Thread.__init__

    def __init__(self, *args, **kwargs):
        inherited = getattr(threading.current_thread(), "_lemon_gen", None)
        original_init(self, *args, **kwargs)
        self._lemon_gen = (
            inherited if inherited is not None else _current_cell()
        )

    __init__._lemon_tagged = True
    threading.Thread.__init__ = __init__


def _prepare_cell(cwd, bridge, cell_id):
    try:
        os.chdir(cwd)
    except OSError as exc:
        raise RuntimeError(
            "cell cwd is no longer accessible: %s (%s)" % (cwd, exc.strerror or exc)
        ) from exc
    if bridge is not None:
        _configure_bridge(bridge, cell_id)


def _run_cell(request):
    cell_id = request["id"]
    cwd = request.get("cwd") or _base_cwd
    try:
        # `started` marks the no-retry boundary: from here the host must
        # never replay or fall back for this cell.
        _write_frame({"v": PROTOCOL_VERSION, "type": "started", "id": cell_id})
        # Stream frames may only follow `started`, never precede it.
        _set_open_cell(cell_id)
        try:
            code = compile(request["code"], CELL_FILENAME, "exec")
            _prepare_cell(cwd, request.get("bridge"), cell_id)
            exec(code, _namespace)
        except BaseException as exc:  # noqa: BLE001 - the kernel must survive cells
            _emit_exception(cell_id, exc)
        # Success or failure, the cell's streams are quiesced and exactly one
        # `done` closes it. Attribution is removed first so output from a
        # late user thread cannot be emitted after the terminal frame.
        _quiesce()
        _close_cell_and_emit_done(cell_id)
    finally:
        _set_open_cell(None)


# ---------------------------------------------------------------------------
# requests
# ---------------------------------------------------------------------------


def _parse_request(line):
    try:
        request = json.loads(line)
    except ValueError:
        raise ProtocolError("request is not valid JSON")
    if not isinstance(request, dict):
        raise ProtocolError("request is not a JSON object")
    if request.get("v") != PROTOCOL_VERSION:
        raise ProtocolError("unsupported protocol version")
    kind = request.get("type")
    if kind == "init":
        if not isinstance(request.get("cwd"), str) or not request["cwd"]:
            raise ProtocolError("init requires a cwd string")
    elif kind == "eval":
        if not isinstance(request.get("id"), str) or not request["id"]:
            raise ProtocolError("eval requires an id string")
        if not isinstance(request.get("code"), str):
            raise ProtocolError("eval requires a code string")
        cwd = request.get("cwd")
        if cwd is not None and (not isinstance(cwd, str) or not cwd):
            raise ProtocolError("eval cwd must be a non-empty string when present")
    elif kind == "shutdown":
        pass
    else:
        raise ProtocolError("unknown request type: %r" % (kind,))
    return request


def _handle_init(request, initialized):
    global _base_cwd
    if initialized:
        raise ProtocolError("duplicate init request")
    cwd = request["cwd"]
    try:
        os.chdir(cwd)
    except OSError:
        raise ProtocolError("init cwd is not accessible: %s" % cwd)
    _base_cwd = cwd
    _write_frame({"v": PROTOCOL_VERSION, "type": "ready", "pid": os.getpid()})


def _read_line(stdin):
    try:
        return stdin.readline()
    except (OSError, ValueError):
        return ""


def main():
    if _RUNNER_DIR not in sys.path:
        # Keep the staged lemon_tools importable after cells chdir elsewhere.
        sys.path.insert(0, _RUNNER_DIR)

    stdin = sys.stdin
    _install_input_rejection()
    _install_thread_cell_tags()
    _setup_descriptors()

    initialized = False
    while True:
        if stdin is None:
            # No request channel: the parent is gone, so leave quietly.
            _stop_pumps()
            return EXIT_OK
        line = _read_line(stdin)
        if line == "":
            # Parent EOF: nothing can be reported and nothing must be faked.
            _stop_pumps()
            return EXIT_OK
        line = line.strip()
        if not line:
            continue
        try:
            request = _parse_request(line)
            if request["type"] == "init":
                _handle_init(request, initialized)
                initialized = True
            elif request["type"] == "eval":
                if not initialized:
                    raise ProtocolError("eval before init")
                _run_cell(request)
            else:
                _write_frame({"v": PROTOCOL_VERSION, "type": "bye"})
                _stop_pumps()
                return EXIT_OK
        except ProtocolError as exc:
            _write_frame({"v": PROTOCOL_VERSION, "type": "fatal", "reason": str(exc)})
            _stop_pumps()
            return EXIT_FATAL


if __name__ == "__main__":
    sys.exit(main())
