#!/bin/bash
#
# Setup script for zeebot voice integration
#
# This script configures the voice transport with Twilio, Deepgram, and ElevenLabs
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEMON_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$LEMON_DIR/config/runtime.exs"

echo "🎙️  zeebot Voice Setup"
echo "======================"
echo ""

# Check for API keys
TWILIO_FILE="$HOME/.zeebot/api_keys/twilio.txt"
if [ -f "$TWILIO_FILE" ]; then
    echo "✓ Found Twilio credentials"
    TWILIO_ACCOUNT_SID=$(grep "Account SID" "$TWILIO_FILE" | awk '{print $3}')
    TWILIO_AUTH_TOKEN=$(grep "Auth token" "$TWILIO_FILE" | awk '{print $3}')
else
    echo "✗ Twilio credentials not found at $TWILIO_FILE"
    echo "Please create this file with:"
    echo "  Account SID: your_account_sid"
    echo "  Auth token: your_auth_token"
    exit 1
fi

# Prompt for Deepgram API key
if [ -z "$DEEPGRAM_API_KEY" ]; then
    echo ""
    echo "Deepgram API key is required for speech-to-text."
    echo "Get one at: https://console.deepgram.com"
    read -sp "Enter Deepgram API key: " DEEPGRAM_API_KEY
    echo ""
fi

# Prompt for ElevenLabs API key
if [ -z "$ELEVENLABS_API_KEY" ]; then
    echo ""
    echo "ElevenLabs API key is required for text-to-speech."
    echo "Get one at: https://elevenlabs.io"
    read -sp "Enter ElevenLabs API key: " ELEVENLABS_API_KEY
    echo ""
fi

# Prompt for Twilio phone number
if [ -z "$TWILIO_PHONE_NUMBER" ]; then
    echo ""
    echo "Enter your Twilio phone number (e.g., +1234567890):"
    read TWILIO_PHONE_NUMBER
fi

# Prompt for public URL (for webhooks)
if [ -z "$VOICE_PUBLIC_URL" ]; then
    echo ""
    echo "Enter your public URL for webhooks (e.g., your-domain.com)"
    echo "For local development, you can use ngrok: ngrok http 4047"
    read VOICE_PUBLIC_URL
fi

echo ""
echo "Configuration:"
echo "  Twilio Account SID: ${TWILIO_ACCOUNT_SID:0:8}..."
echo "  Twilio Phone: $TWILIO_PHONE_NUMBER"
echo "  Public URL: $VOICE_PUBLIC_URL"
echo ""

# Create or update runtime config
mkdir -p "$LEMON_DIR/config"

cat > "$CONFIG_FILE" << EOF
# Runtime configuration for Lemon Gateway
# Generated by voice_setup.sh

import Config

# Voice transport configuration
config :lemon_gateway,
  voice_enabled: true,
  voice_websocket_port: 4047,
  voice_public_url: "${VOICE_PUBLIC_URL}",
  twilio_account_sid: "${TWILIO_ACCOUNT_SID}",
  twilio_auth_token: "${TWILIO_AUTH_TOKEN}",
  twilio_phone_number: "${TWILIO_PHONE_NUMBER}",
  deepgram_api_key: "${DEEPGRAM_API_KEY}",
  elevenlabs_api_key: "${ELEVENLABS_API_KEY}",
  elevenlabs_voice_id: "21m00Tcm4TlvDq8ikWAM",
  voice_llm_model: "gpt-4o-mini",
  voice_max_call_duration_seconds: 600,
  voice_silence_timeout_ms: 5000

# System prompt for voice conversations
config :lemon_gateway,
  voice_system_prompt: """
You are zeebot, a friendly AI assistant built on the Lemon framework. You're talking to someone on the phone.

Guidelines:
- Keep responses concise (1-3 sentences max) — this is a voice conversation
- Be warm, helpful, and occasionally witty
- If you need to perform actions, do so efficiently
- If you don't know something, say so honestly
- Remember: the user is listening, not reading

You can help with:
- Answering questions
- Performing tasks via tools
- Having casual conversation
- Crypto and Ethereum topics (you're crypto-native)
"""
EOF

echo "✓ Configuration written to $CONFIG_FILE"
echo ""

# Install dependencies
echo "Installing dependencies..."
cd "$LEMON_DIR"
mix deps.get

echo ""
echo "🎉 Setup complete!"
echo ""
echo "To start the voice server:"
echo "  cd $LEMON_DIR"
echo "  mix run --no-halt"
echo ""
echo "Your phone number $TWILIO_PHONE_NUMBER is ready to receive calls!"
echo ""
echo "For local development with ngrok:"
echo "  1. Start the voice server: mix run --no-halt"
echo "  2. In another terminal: ngrok http 4047"
echo "  3. Update your Twilio webhook URL to: https://YOUR_NGROK.ngrok.io/webhooks/twilio/voice"
