defmodule LemonSim.Examples.Legislature.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Caucus Phase --

  @spec send_message(String.t(), String.t(), String.t()) :: Event.t()
  def send_message(sender_id, recipient_id, message) do
    Event.new("send_message", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "message" => message
    })
  end

  @spec propose_trade(String.t(), String.t(), String.t(), String.t()) :: Event.t()
  def propose_trade(proposer_id, recipient_id, bill_a, bill_b) do
    Event.new("propose_trade", %{
      "proposer_id" => proposer_id,
      "recipient_id" => recipient_id,
      "bill_a" => bill_a,
      "bill_b" => bill_b
    })
  end

  @spec end_caucus(String.t()) :: Event.t()
  def end_caucus(player_id) do
    Event.new("end_caucus", %{"player_id" => player_id})
  end

  # -- Floor Debate Phase --

  @spec make_speech(String.t(), String.t(), String.t()) :: Event.t()
  def make_speech(player_id, bill_id, speech) do
    Event.new("make_speech", %{
      "player_id" => player_id,
      "bill_id" => bill_id,
      "speech" => speech
    })
  end

  @spec end_floor_debate(String.t()) :: Event.t()
  def end_floor_debate(player_id) do
    Event.new("end_floor_debate", %{"player_id" => player_id})
  end

  # -- Amendment Phase --

  @spec propose_amendment(String.t(), String.t(), String.t()) :: Event.t()
  def propose_amendment(player_id, bill_id, amendment_text) do
    Event.new("propose_amendment", %{
      "player_id" => player_id,
      "bill_id" => bill_id,
      "amendment_text" => amendment_text
    })
  end

  @spec lobby(String.t(), String.t(), non_neg_integer()) :: Event.t()
  def lobby(player_id, bill_id, capital_spent) do
    Event.new("lobby", %{
      "player_id" => player_id,
      "bill_id" => bill_id,
      "capital_spent" => capital_spent
    })
  end

  @spec end_amendment(String.t()) :: Event.t()
  def end_amendment(player_id) do
    Event.new("end_amendment", %{"player_id" => player_id})
  end

  # -- Amendment Vote Phase --

  @spec cast_amendment_vote(String.t(), String.t(), String.t(), String.t()) :: Event.t()
  def cast_amendment_vote(player_id, amendment_id, vote, bill_id) do
    Event.new("cast_amendment_vote", %{
      "player_id" => player_id,
      "amendment_id" => amendment_id,
      "vote" => vote,
      "bill_id" => bill_id
    })
  end

  @spec end_amendment_vote(String.t()) :: Event.t()
  def end_amendment_vote(player_id) do
    Event.new("end_amendment_vote", %{"player_id" => player_id})
  end

  # -- Final Vote Phase --

  @spec cast_votes(String.t(), map()) :: Event.t()
  def cast_votes(player_id, votes) do
    Event.new("cast_votes", %{
      "player_id" => player_id,
      "votes" => votes
    })
  end

  # -- Resolution events (generated by updater) --

  @spec message_delivered(String.t(), String.t(), String.t()) :: Event.t()
  def message_delivered(sender_id, recipient_id, message) do
    Event.new("message_delivered", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "message" => message
    })
  end

  @spec trade_proposed(String.t(), String.t(), String.t(), String.t()) :: Event.t()
  def trade_proposed(proposer_id, recipient_id, bill_a, bill_b) do
    Event.new("trade_proposed", %{
      "proposer_id" => proposer_id,
      "recipient_id" => recipient_id,
      "bill_a" => bill_a,
      "bill_b" => bill_b
    })
  end

  @spec caucus_ended(String.t()) :: Event.t()
  def caucus_ended(player_id) do
    Event.new("caucus_ended", %{"player_id" => player_id})
  end

  @spec speech_delivered(String.t(), String.t()) :: Event.t()
  def speech_delivered(player_id, bill_id) do
    Event.new("speech_delivered", %{
      "player_id" => player_id,
      "bill_id" => bill_id
    })
  end

  @spec floor_debate_ended(String.t()) :: Event.t()
  def floor_debate_ended(player_id) do
    Event.new("floor_debate_ended", %{"player_id" => player_id})
  end

  @spec amendment_proposed(String.t(), String.t(), String.t(), String.t()) :: Event.t()
  def amendment_proposed(player_id, bill_id, amendment_id, amendment_text) do
    Event.new("amendment_proposed", %{
      "player_id" => player_id,
      "bill_id" => bill_id,
      "amendment_id" => amendment_id,
      "amendment_text" => amendment_text
    })
  end

  @spec lobby_recorded(String.t(), String.t(), non_neg_integer()) :: Event.t()
  def lobby_recorded(player_id, bill_id, capital_spent) do
    Event.new("lobby_recorded", %{
      "player_id" => player_id,
      "bill_id" => bill_id,
      "capital_spent" => capital_spent
    })
  end

  @spec amendment_ended(String.t()) :: Event.t()
  def amendment_ended(player_id) do
    Event.new("amendment_ended", %{"player_id" => player_id})
  end

  @spec amendment_vote_cast(String.t(), String.t(), String.t()) :: Event.t()
  def amendment_vote_cast(player_id, amendment_id, vote) do
    Event.new("amendment_vote_cast", %{
      "player_id" => player_id,
      "amendment_id" => amendment_id,
      "vote" => vote
    })
  end

  @spec amendment_resolved(String.t(), String.t(), boolean()) :: Event.t()
  def amendment_resolved(amendment_id, bill_id, passed?) do
    Event.new("amendment_resolved", %{
      "amendment_id" => amendment_id,
      "bill_id" => bill_id,
      "passed" => passed?
    })
  end

  @spec amendment_vote_ended(String.t()) :: Event.t()
  def amendment_vote_ended(player_id) do
    Event.new("amendment_vote_ended", %{"player_id" => player_id})
  end

  @spec votes_cast(String.t(), map()) :: Event.t()
  def votes_cast(player_id, votes) do
    Event.new("votes_cast", %{
      "player_id" => player_id,
      "votes" => votes
    })
  end

  @spec bill_voted(String.t(), boolean(), non_neg_integer(), non_neg_integer()) :: Event.t()
  def bill_voted(bill_id, passed?, yes_votes, no_votes) do
    Event.new("bill_voted", %{
      "bill_id" => bill_id,
      "passed" => passed?,
      "yes_votes" => yes_votes,
      "no_votes" => no_votes
    })
  end

  @spec scores_updated(map()) :: Event.t()
  def scores_updated(score_delta) do
    Event.new("scores_updated", %{"score_delta" => score_delta})
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec session_advanced(pos_integer()) :: Event.t()
  def session_advanced(session) do
    Event.new("session_advanced", %{"session" => session})
  end

  @spec game_over(String.t(), String.t()) :: Event.t()
  def game_over(status, winner) do
    Event.new("game_over", %{
      "status" => status,
      "winner" => winner,
      "message" => "#{winner} wins the legislature game"
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, player_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "player_id" => player_id,
      "reason" => reason
    })
  end
end
