Mix.Tasks.Lemon.Sim.Werewolf.run([
  "--player-count",
  "8",
  "--models",
  Enum.join(
    [
      "google_gemini_cli:gemini-3-flash-preview",
      "google_gemini_cli:gemini-3-pro-preview",
      "google_gemini_cli:gemini-2.5-flash",
      "google_gemini_cli:gemini-2.5-pro",
      "openai-codex:gpt-5.1-codex-mini",
      "openai-codex:gpt-5.3-codex-spark",
      "openai-codex:gpt-5.3-codex",
      "kimi:k2p5"
    ],
    ","
  ),
  "--transcript-path",
  "apps/lemon_sim/priv/game_logs/werewolf_multi_#{System.system_time(:second)}.jsonl",
  "--no-persist",
  "--max-turns",
  "200"
])
