defmodule LemonSimUi.Env do
  @moduledoc """
  Environment variables read by `lemon_sim_ui` — the simulation UI, hosted rooms, and the always-on model arenas.

  Aggregated by `LemonCore.Env` through the `:env_registries` list; see
  `LemonCore.Env.Registry`.
  """

  use LemonCore.Env.Registry

  @declarations [
    %{
      name: :lemon_arena_league_root,
      env_var: "LEMON_ARENA_LEAGUE_ROOT",
      aliases: [],
      type: :string,
      default: nil,
      doc:
        "Root directory under which each arena domain's league dir defaults to `<domain>_league`; must be absolute for the production sim UI.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_poker_enabled,
      env_var: "LEMON_ARENA_POKER_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the poker arena is enabled (only checked once MODELS is set).",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_poker_game_delay_ms,
      env_var: "LEMON_ARENA_POKER_GAME_DELAY_MS",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Delay between games (ms) for the poker arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_poker_league_dir,
      env_var: "LEMON_ARENA_POKER_LEAGUE_DIR",
      aliases: [],
      type: :string,
      default: nil,
      doc: "League standings directory for the poker arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_poker_models,
      env_var: "LEMON_ARENA_POKER_MODELS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated provider:model specs enabling the poker arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_poker_player_count,
      env_var: "LEMON_ARENA_POKER_PLAYER_COUNT",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Player count for the poker arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_space_station_enabled,
      env_var: "LEMON_ARENA_SPACE_STATION_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the space_station arena is enabled (only checked once MODELS is set).",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_space_station_game_delay_ms,
      env_var: "LEMON_ARENA_SPACE_STATION_GAME_DELAY_MS",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Delay between games (ms) for the space_station arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_space_station_league_dir,
      env_var: "LEMON_ARENA_SPACE_STATION_LEAGUE_DIR",
      aliases: [],
      type: :string,
      default: nil,
      doc: "League standings directory for the space_station arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_space_station_models,
      env_var: "LEMON_ARENA_SPACE_STATION_MODELS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated provider:model specs enabling the space_station arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_space_station_player_count,
      env_var: "LEMON_ARENA_SPACE_STATION_PLAYER_COUNT",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Player count for the space_station arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_stock_market_enabled,
      env_var: "LEMON_ARENA_STOCK_MARKET_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the stock_market arena is enabled (only checked once MODELS is set).",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_stock_market_game_delay_ms,
      env_var: "LEMON_ARENA_STOCK_MARKET_GAME_DELAY_MS",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Delay between games (ms) for the stock_market arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_stock_market_league_dir,
      env_var: "LEMON_ARENA_STOCK_MARKET_LEAGUE_DIR",
      aliases: [],
      type: :string,
      default: nil,
      doc: "League standings directory for the stock_market arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_stock_market_models,
      env_var: "LEMON_ARENA_STOCK_MARKET_MODELS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated provider:model specs enabling the stock_market arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_stock_market_player_count,
      env_var: "LEMON_ARENA_STOCK_MARKET_PLAYER_COUNT",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Player count for the stock_market arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_survivor_enabled,
      env_var: "LEMON_ARENA_SURVIVOR_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the survivor arena is enabled (only checked once MODELS is set).",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_survivor_game_delay_ms,
      env_var: "LEMON_ARENA_SURVIVOR_GAME_DELAY_MS",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Delay between games (ms) for the survivor arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_survivor_league_dir,
      env_var: "LEMON_ARENA_SURVIVOR_LEAGUE_DIR",
      aliases: [],
      type: :string,
      default: nil,
      doc: "League standings directory for the survivor arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_survivor_models,
      env_var: "LEMON_ARENA_SURVIVOR_MODELS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated provider:model specs enabling the survivor arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_survivor_player_count,
      env_var: "LEMON_ARENA_SURVIVOR_PLAYER_COUNT",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Player count for the survivor arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_werewolf_enabled,
      env_var: "LEMON_ARENA_WEREWOLF_ENABLED",
      aliases: ["WEREWOLF_ARENA_ENABLED"],
      type: :boolean,
      default: true,
      doc: "Whether the werewolf arena is enabled (only checked once MODELS is set).",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_werewolf_game_delay_ms,
      env_var: "LEMON_ARENA_WEREWOLF_GAME_DELAY_MS",
      aliases: ["WEREWOLF_ARENA_GAME_DELAY_MS"],
      type: :integer,
      default: nil,
      doc: "Delay between games (ms) for the werewolf arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_werewolf_league_dir,
      env_var: "LEMON_ARENA_WEREWOLF_LEAGUE_DIR",
      aliases: ["WEREWOLF_LEAGUE_DIR"],
      type: :string,
      default: nil,
      doc: "League standings directory for the werewolf arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_werewolf_models,
      env_var: "LEMON_ARENA_WEREWOLF_MODELS",
      aliases: ["WEREWOLF_ARENA_MODELS"],
      type: :list,
      default: [],
      doc: "Comma-separated provider:model specs enabling the werewolf arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_arena_werewolf_player_count,
      env_var: "LEMON_ARENA_WEREWOLF_PLAYER_COUNT",
      aliases: ["WEREWOLF_ARENA_PLAYER_COUNT"],
      type: :integer,
      default: nil,
      doc: "Player count for the werewolf arena.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_auto_loop,
      env_var: "LEMON_SIM_AUTO_LOOP",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the werewolf auto-loop starts automatically on boot.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_werewolf_players,
      env_var: "LEMON_SIM_WEREWOLF_PLAYERS",
      aliases: [],
      type: :integer,
      default: 6,
      doc: "Player count for the werewolf auto-loop.",
      secret?: false,
      required?: false,
      area: :arena,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_access_token,
      env_var: "LEMON_SIM_UI_ACCESS_TOKEN",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Admin token; required with at least 32 bytes for a production Sim UI endpoint.",
      secret?: true,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_bind_ip,
      env_var: "LEMON_SIM_UI_BIND_IP",
      aliases: [],
      type: :string,
      default: "127.0.0.1",
      doc: "Bind IP address for the LemonSimUi dev endpoint.",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_host,
      env_var: "LEMON_SIM_UI_HOST",
      aliases: [],
      type: :string,
      default: "localhost",
      doc: "Public hostname for the LemonSimUi prod endpoint; explicit in production.",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_port,
      env_var: "LEMON_SIM_UI_PORT",
      aliases: [],
      type: :integer,
      default: 4090,
      doc: "Port LemonSimUi listens on.",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_url_scheme,
      env_var: "LEMON_SIM_UI_URL_SCHEME",
      aliases: [],
      type: :string,
      default: "https",
      doc: "Public URL scheme for generated LemonSimUi links (http or https).",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_url_port,
      env_var: "LEMON_SIM_UI_URL_PORT",
      aliases: [],
      type: :integer,
      default: 443,
      doc: "Public URL port for generated LemonSimUi links.",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_public_vending_launcher,
      env_var: "LEMON_SIM_UI_PUBLIC_VENDING_LAUNCHER",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the public VendingBench launcher page is exposed.",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_secret_key_base,
      env_var: "LEMON_SIM_UI_SECRET_KEY_BASE",
      aliases: [],
      type: :string,
      default: nil,
      doc:
        "Phoenix secret_key_base; required with at least 64 bytes for a production Sim UI endpoint.",
      secret?: true,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    },
    %{
      name: :lemon_sim_ui_suite_roots,
      env_var: "LEMON_SIM_UI_SUITE_ROOTS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Colon-separated extra suite root directories for LemonSimUi.",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_sim_ui]
    }
  ]
end
