defmodule LemonSim.Examples.SupplyChain.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Observe Phase --

  @spec check_inventory(String.t()) :: Event.t()
  def check_inventory(tier_id) do
    Event.new("check_inventory", %{"tier_id" => tier_id})
  end

  # -- Communicate Phase --

  @spec send_forecast(String.t(), String.t(), map()) :: Event.t()
  def send_forecast(sender_id, recipient_id, forecast) do
    Event.new("send_forecast", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "forecast" => forecast
    })
  end

  @spec request_info(String.t(), String.t()) :: Event.t()
  def request_info(requester_id, target_id) do
    Event.new("request_info", %{
      "requester_id" => requester_id,
      "target_id" => target_id
    })
  end

  @spec end_communicate(String.t()) :: Event.t()
  def end_communicate(tier_id) do
    Event.new("end_communicate", %{"tier_id" => tier_id})
  end

  # -- Order Phase --

  @spec place_order(String.t(), non_neg_integer()) :: Event.t()
  def place_order(tier_id, quantity) do
    Event.new("place_order", %{
      "tier_id" => tier_id,
      "quantity" => quantity
    })
  end

  # -- Additional Actions --

  @spec adjust_safety_stock(String.t(), non_neg_integer()) :: Event.t()
  def adjust_safety_stock(tier_id, target_minimum) do
    Event.new("adjust_safety_stock", %{
      "tier_id" => tier_id,
      "target_minimum" => target_minimum
    })
  end

  @spec expedite_order(String.t(), non_neg_integer()) :: Event.t()
  def expedite_order(tier_id, quantity) do
    Event.new("expedite_order", %{
      "tier_id" => tier_id,
      "quantity" => quantity
    })
  end

  # -- System events (generated by updater) --

  @spec inventory_observed(String.t(), map()) :: Event.t()
  def inventory_observed(tier_id, snapshot) do
    Event.new("inventory_observed", %{
      "tier_id" => tier_id,
      "snapshot" => snapshot
    })
  end

  @spec forecast_sent(String.t(), String.t(), map()) :: Event.t()
  def forecast_sent(sender_id, recipient_id, forecast) do
    Event.new("forecast_sent", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "forecast" => forecast
    })
  end

  @spec info_requested(String.t(), String.t()) :: Event.t()
  def info_requested(requester_id, target_id) do
    Event.new("info_requested", %{
      "requester_id" => requester_id,
      "target_id" => target_id
    })
  end

  @spec communicate_ended(String.t()) :: Event.t()
  def communicate_ended(tier_id) do
    Event.new("communicate_ended", %{"tier_id" => tier_id})
  end

  @spec order_placed(String.t(), non_neg_integer()) :: Event.t()
  def order_placed(tier_id, quantity) do
    Event.new("order_placed", %{
      "tier_id" => tier_id,
      "quantity" => quantity
    })
  end

  @spec order_fulfilled(String.t(), String.t(), non_neg_integer(), non_neg_integer()) :: Event.t()
  def order_fulfilled(supplier_id, customer_id, ordered, fulfilled) do
    Event.new("order_fulfilled", %{
      "supplier_id" => supplier_id,
      "customer_id" => customer_id,
      "ordered" => ordered,
      "fulfilled" => fulfilled
    })
  end

  @spec delivery_dispatched(String.t(), String.t(), non_neg_integer(), pos_integer()) :: Event.t()
  def delivery_dispatched(supplier_id, customer_id, quantity, arrive_round) do
    Event.new("delivery_dispatched", %{
      "supplier_id" => supplier_id,
      "customer_id" => customer_id,
      "quantity" => quantity,
      "arrive_round" => arrive_round
    })
  end

  @spec delivery_arrived(String.t(), non_neg_integer()) :: Event.t()
  def delivery_arrived(tier_id, quantity) do
    Event.new("delivery_arrived", %{
      "tier_id" => tier_id,
      "quantity" => quantity
    })
  end

  @spec demand_realized(non_neg_integer(), non_neg_integer(), non_neg_integer()) :: Event.t()
  def demand_realized(demand, fulfilled, backlog) do
    Event.new("demand_realized", %{
      "demand" => demand,
      "fulfilled" => fulfilled,
      "backlog" => backlog
    })
  end

  @spec costs_assessed(String.t(), float(), float(), float()) :: Event.t()
  def costs_assessed(tier_id, holding_cost, stockout_cost, round_total) do
    Event.new("costs_assessed", %{
      "tier_id" => tier_id,
      "holding_cost" => holding_cost,
      "stockout_cost" => stockout_cost,
      "round_total" => round_total
    })
  end

  @spec safety_stock_adjusted(String.t(), non_neg_integer()) :: Event.t()
  def safety_stock_adjusted(tier_id, target_minimum) do
    Event.new("safety_stock_adjusted", %{
      "tier_id" => tier_id,
      "target_minimum" => target_minimum
    })
  end

  @spec expedite_order_placed(String.t(), non_neg_integer()) :: Event.t()
  def expedite_order_placed(tier_id, quantity) do
    Event.new("expedite_order_placed", %{
      "tier_id" => tier_id,
      "quantity" => quantity
    })
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec round_advanced(pos_integer()) :: Event.t()
  def round_advanced(round) do
    Event.new("round_advanced", %{"round" => round})
  end

  @spec game_over(String.t(), String.t() | nil) :: Event.t()
  def game_over(status, winner) do
    Event.new("game_over", %{
      "status" => status,
      "winner" => winner,
      "message" =>
        if(winner,
          do: "#{winner} wins with lowest total cost!",
          else: "Supply chain simulation complete"
        )
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, tier_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "tier_id" => tier_id,
      "reason" => reason
    })
  end
end
