defmodule LemonCli.CompletionCommand do
  @moduledoc """
  Generates deterministic Bash, Zsh, and Fish completion scripts from
  `LemonCli.CommandRegistry`.

  The launchers set `LEMON_CLI_LAUNCHER` only for generation so source-only
  and packaged-release-only commands remain truthful.
  """

  alias LemonCli.CommandRegistry

  @shells ~w(bash zsh fish)

  @spec run([String.t()]) :: 0 | 2
  def run([shell]) when shell in @shells do
    IO.write(render(shell, launcher_from_env()))
    0
  end

  def run(_args) do
    IO.puts(:stderr, "Usage: lemon completion <bash|zsh|fish>")
    2
  end

  @spec render(String.t(), :source | :release) :: String.t()
  def render("bash", launcher), do: render_bash(commands(launcher))
  def render("zsh", launcher), do: render_zsh(commands(launcher))
  def render("fish", launcher), do: render_fish(commands(launcher))

  defp launcher_from_env do
    case System.get_env("LEMON_CLI_LAUNCHER") do
      "source" -> :source
      _other -> :release
    end
  end

  defp commands(launcher), do: CommandRegistry.completion_commands(launcher)

  defp render_bash(commands) do
    top_level = Enum.map_join(commands, " ", & &1.name)

    cases =
      Enum.map_join(commands, "\n", fn command ->
        words = completion_words(command)

        """
            #{command.name})
              COMPREPLY=( $(compgen -W #{shell_quote(Enum.join(words, " "))} -- "$cur") )
              ;;
        """
        |> String.trim_trailing()
      end)

    """
    # Bash completion for Lemon. Generated by `lemon completion bash`.
    _lemon_completion() {
      local cur family
      COMPREPLY=()
      cur="${COMP_WORDS[COMP_CWORD]}"

      if (( COMP_CWORD == 1 )); then
        COMPREPLY=( $(compgen -W #{shell_quote(top_level)} -- "$cur") )
        return 0
      fi

      family="${COMP_WORDS[1]}"
      case "$family" in
    #{cases}
      esac
    }

    complete -F _lemon_completion lemon ./bin/lemon
    """
  end

  defp render_zsh(commands) do
    described_commands =
      Enum.map_join(commands, "\n", fn command ->
        "    #{shell_quote("#{command.name}:#{command.summary}")}"
      end)

    cases =
      Enum.map_join(commands, "\n", fn command ->
        described_words =
          command
          |> completion_entries()
          |> Enum.map_join("\n", fn {word, summary} ->
            "        #{shell_quote("#{word}:#{summary}")}"
          end)

        """
          #{command.name})
            local -a family_words
            family_words=(
        #{described_words}
            )
            _describe 'argument' family_words
            ;;
        """
        |> String.trim_trailing()
      end)

    """
    #compdef lemon
    # Zsh completion for Lemon. Generated by `lemon completion zsh`.
    _lemon() {
      local -a commands
      commands=(
    #{described_commands}
      )

      if (( CURRENT == 2 )); then
        _describe 'command' commands
        return
      fi

      case "${words[2]}" in
    #{cases}
      esac
    }

    compdef _lemon lemon
    """
  end

  defp render_fish(commands) do
    command_lines =
      Enum.map_join(commands, "\n", fn command ->
        "complete -c lemon -f -n '__fish_use_subcommand' -a #{shell_quote(command.name)} -d #{shell_quote(command.summary)}"
      end)

    family_lines =
      Enum.flat_map(commands, fn command ->
        condition = "__fish_seen_subcommand_from #{command.name}"

        subcommands =
          Enum.map(command.subcommands, fn subcommand ->
            "complete -c lemon -f -n #{shell_quote(condition)} -a #{shell_quote(subcommand.name)} -d #{shell_quote(subcommand.summary)}"
          end)

        options =
          command.options
          |> Enum.flat_map(fn option ->
            Enum.map(option.flags, fn flag ->
              fish_option(command.name, flag, option.summary)
            end)
          end)

        subcommands ++ options
      end)
      |> Enum.join("\n")

    """
    # Fish completion for Lemon. Generated by `lemon completion fish`.
    complete -c lemon -e
    #{command_lines}
    #{family_lines}
    """
  end

  defp completion_words(command) do
    Enum.map(command.subcommands, & &1.name) ++
      Enum.flat_map(command.options, & &1.flags) ++ ["--help", "-h"]
  end

  defp completion_entries(command) do
    subcommands = Enum.map(command.subcommands, &{&1.name, &1.summary})

    options =
      Enum.flat_map(command.options, fn option ->
        Enum.map(option.flags, &{&1, option.summary})
      end)

    subcommands ++ options ++ [{"--help", "Show command help"}, {"-h", "Show command help"}]
  end

  defp fish_option(command, "--" <> flag, summary) do
    "complete -c lemon -f -n #{shell_quote("__fish_seen_subcommand_from #{command}")} -l #{shell_quote(flag)} -d #{shell_quote(summary)}"
  end

  defp fish_option(command, "-" <> flag, summary) do
    "complete -c lemon -f -n #{shell_quote("__fish_seen_subcommand_from #{command}")} -s #{shell_quote(flag)} -d #{shell_quote(summary)}"
  end

  defp shell_quote(value) do
    "'" <> String.replace(to_string(value), "'", "'\"'\"'") <> "'"
  end
end
