defmodule LemonSim.Examples.Diplomacy.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Diplomacy Phase --

  @spec send_message(String.t(), String.t(), String.t()) :: Event.t()
  def send_message(sender_id, recipient_id, message) do
    Event.new("send_message", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "message" => message
    })
  end

  @spec end_diplomacy(String.t()) :: Event.t()
  def end_diplomacy(player_id) do
    Event.new("end_diplomacy", %{"player_id" => player_id})
  end

  # -- Orders Phase --

  @spec issue_order(String.t(), String.t(), String.t(), String.t(), String.t() | nil) :: Event.t()
  def issue_order(player_id, army_territory, order_type, target_territory, support_target \\ nil) do
    Event.new("issue_order", %{
      "player_id" => player_id,
      "army_territory" => army_territory,
      "order_type" => order_type,
      "target_territory" => target_territory,
      "support_target" => support_target
    })
  end

  @spec submit_orders(String.t()) :: Event.t()
  def submit_orders(player_id) do
    Event.new("submit_orders", %{"player_id" => player_id})
  end

  # -- Resolution events (generated by updater) --

  @spec message_delivered(String.t(), String.t(), String.t()) :: Event.t()
  def message_delivered(sender_id, recipient_id, message) do
    Event.new("message_delivered", %{
      "sender_id" => sender_id,
      "recipient_id" => recipient_id,
      "message" => message
    })
  end

  @spec diplomacy_ended(String.t()) :: Event.t()
  def diplomacy_ended(player_id) do
    Event.new("diplomacy_ended", %{"player_id" => player_id})
  end

  @spec order_recorded(String.t(), String.t(), String.t(), String.t(), String.t() | nil) ::
          Event.t()
  def order_recorded(player_id, army_territory, order_type, target_territory, support_target) do
    Event.new("order_recorded", %{
      "player_id" => player_id,
      "army_territory" => army_territory,
      "order_type" => order_type,
      "target_territory" => target_territory,
      "support_target" => support_target
    })
  end

  @spec orders_submitted(String.t()) :: Event.t()
  def orders_submitted(player_id) do
    Event.new("orders_submitted", %{"player_id" => player_id})
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec move_resolved(String.t(), String.t(), String.t(), boolean()) :: Event.t()
  def move_resolved(player_id, from_territory, to_territory, success?) do
    Event.new("move_resolved", %{
      "player_id" => player_id,
      "from" => from_territory,
      "to" => to_territory,
      "success" => success?
    })
  end

  @spec territory_captured(String.t(), String.t(), String.t() | nil) :: Event.t()
  def territory_captured(territory, new_owner, old_owner) do
    Event.new("territory_captured", %{
      "territory" => territory,
      "new_owner" => new_owner,
      "old_owner" => old_owner
    })
  end

  @spec bounce(String.t(), [String.t()]) :: Event.t()
  def bounce(territory, contestants) do
    Event.new("bounce", %{
      "territory" => territory,
      "contestants" => contestants
    })
  end

  @spec armies_produced(String.t(), String.t()) :: Event.t()
  def armies_produced(territory, owner) do
    Event.new("armies_produced", %{
      "territory" => territory,
      "owner" => owner
    })
  end

  @spec round_advanced(pos_integer()) :: Event.t()
  def round_advanced(round) do
    Event.new("round_advanced", %{"round" => round})
  end

  @spec game_over(String.t(), String.t()) :: Event.t()
  def game_over(status, winner) do
    Event.new("game_over", %{
      "status" => status,
      "winner" => winner,
      "message" => "#{winner} wins the diplomacy game"
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, player_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "player_id" => player_id,
      "reason" => reason
    })
  end
end
