defmodule LemonSim.Examples.Pandemic.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Intelligence phase --

  @spec check_region(String.t(), String.t()) :: Event.t()
  def check_region(governor_id, region_id) do
    Event.new("check_region", %{
      "governor_id" => governor_id,
      "region_id" => region_id
    })
  end

  @spec end_intelligence(String.t()) :: Event.t()
  def end_intelligence(governor_id) do
    Event.new("end_intelligence", %{"governor_id" => governor_id})
  end

  # -- Communication phase --

  @spec share_data(String.t(), String.t(), map()) :: Event.t()
  def share_data(from_id, to_id, data) do
    Event.new("share_data", %{
      "from_id" => from_id,
      "to_id" => to_id,
      "data" => data
    })
  end

  @spec request_help(String.t(), String.t(), String.t()) :: Event.t()
  def request_help(from_id, to_id, message) do
    Event.new("request_help", %{
      "from_id" => from_id,
      "to_id" => to_id,
      "message" => message
    })
  end

  @spec end_communication(String.t()) :: Event.t()
  def end_communication(governor_id) do
    Event.new("end_communication", %{"governor_id" => governor_id})
  end

  # -- Resource allocation phase --

  @spec request_resources(String.t(), non_neg_integer(), non_neg_integer(), non_neg_integer()) ::
          Event.t()
  def request_resources(governor_id, vaccines, funding, medical_teams) do
    Event.new("request_resources", %{
      "governor_id" => governor_id,
      "vaccines" => vaccines,
      "funding" => funding,
      "medical_teams" => medical_teams
    })
  end

  @spec donate_resources(
          String.t(),
          String.t(),
          non_neg_integer(),
          non_neg_integer(),
          non_neg_integer()
        ) :: Event.t()
  def donate_resources(from_id, to_id, vaccines, funding, medical_teams) do
    Event.new("donate_resources", %{
      "from_id" => from_id,
      "to_id" => to_id,
      "vaccines" => vaccines,
      "funding" => funding,
      "medical_teams" => medical_teams
    })
  end

  @spec end_resource_allocation(String.t()) :: Event.t()
  def end_resource_allocation(governor_id) do
    Event.new("end_resource_allocation", %{"governor_id" => governor_id})
  end

  # -- Local action phase --

  @spec vaccinate(String.t(), non_neg_integer()) :: Event.t()
  def vaccinate(governor_id, count) do
    Event.new("vaccinate", %{
      "governor_id" => governor_id,
      "count" => count
    })
  end

  @spec quarantine_zone(String.t(), String.t()) :: Event.t()
  def quarantine_zone(governor_id, region_id) do
    Event.new("quarantine_zone", %{
      "governor_id" => governor_id,
      "region_id" => region_id
    })
  end

  @spec build_hospital(String.t()) :: Event.t()
  def build_hospital(governor_id) do
    Event.new("build_hospital", %{"governor_id" => governor_id})
  end

  @spec fund_research(String.t(), non_neg_integer()) :: Event.t()
  def fund_research(governor_id, funding) do
    Event.new("fund_research", %{
      "governor_id" => governor_id,
      "funding" => funding
    })
  end

  @spec hoard_supplies(String.t(), non_neg_integer(), non_neg_integer()) :: Event.t()
  def hoard_supplies(governor_id, vaccines, medical_teams) do
    Event.new("hoard_supplies", %{
      "governor_id" => governor_id,
      "vaccines" => vaccines,
      "medical_teams" => medical_teams
    })
  end

  @spec end_local_action(String.t()) :: Event.t()
  def end_local_action(governor_id) do
    Event.new("end_local_action", %{"governor_id" => governor_id})
  end

  # -- System events (generated by updater) --

  @spec data_shared(String.t(), String.t(), map()) :: Event.t()
  def data_shared(from_id, to_id, data) do
    Event.new("data_shared", %{
      "from_id" => from_id,
      "to_id" => to_id,
      "data" => data
    })
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec round_advanced(pos_integer()) :: Event.t()
  def round_advanced(round) do
    Event.new("round_advanced", %{"round" => round})
  end

  @spec spread_occurred(String.t(), non_neg_integer(), non_neg_integer()) :: Event.t()
  def spread_occurred(region_id, new_infections, total_infected) do
    Event.new("spread_occurred", %{
      "region_id" => region_id,
      "new_infections" => new_infections,
      "total_infected" => total_infected
    })
  end

  @spec deaths_recorded(String.t(), non_neg_integer()) :: Event.t()
  def deaths_recorded(region_id, deaths) do
    Event.new("deaths_recorded", %{
      "region_id" => region_id,
      "deaths" => deaths
    })
  end

  @spec game_over(String.t(), String.t() | nil, String.t()) :: Event.t()
  def game_over(status, winner, reason) do
    Event.new("game_over", %{
      "status" => status,
      "winner" => winner,
      "reason" => reason
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, governor_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "governor_id" => governor_id,
      "reason" => reason
    })
  end
end
