defmodule LemonSim.Examples.StartupIncubator.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Pitch Phase --

  @spec make_pitch(String.t(), String.t()) :: Event.t()
  def make_pitch(founder_id, pitch_text) do
    Event.new("make_pitch", %{
      "founder_id" => founder_id,
      "pitch_text" => pitch_text
    })
  end

  # -- Due Diligence Phase --

  @spec ask_question(String.t(), String.t(), String.t()) :: Event.t()
  def ask_question(investor_id, founder_id, question) do
    Event.new("ask_question", %{
      "investor_id" => investor_id,
      "founder_id" => founder_id,
      "question" => question
    })
  end

  @spec answer_question(String.t(), String.t(), String.t(), boolean()) :: Event.t()
  def answer_question(founder_id, investor_id, answer, truthful \\ true) do
    Event.new("answer_question", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id,
      "answer" => answer,
      "truthful" => truthful
    })
  end

  # -- Negotiation Phase --

  @spec make_offer(String.t(), String.t(), non_neg_integer(), float()) :: Event.t()
  def make_offer(investor_id, founder_id, amount, equity_pct) do
    Event.new("make_offer", %{
      "investor_id" => investor_id,
      "founder_id" => founder_id,
      "amount" => amount,
      "equity_pct" => equity_pct
    })
  end

  @spec counter_offer(String.t(), String.t(), non_neg_integer(), float()) :: Event.t()
  def counter_offer(founder_id, investor_id, amount, equity_pct) do
    Event.new("counter_offer", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id,
      "amount" => amount,
      "equity_pct" => equity_pct
    })
  end

  @spec accept_deal(String.t(), String.t()) :: Event.t()
  def accept_deal(founder_id, investor_id) do
    Event.new("accept_deal", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id
    })
  end

  @spec reject_deal(String.t(), String.t()) :: Event.t()
  def reject_deal(founder_id, investor_id) do
    Event.new("reject_deal", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id
    })
  end

  @spec merge_startups(String.t(), String.t()) :: Event.t()
  def merge_startups(founder_a_id, founder_b_id) do
    Event.new("merge_startups", %{
      "founder_a_id" => founder_a_id,
      "founder_b_id" => founder_b_id
    })
  end

  # -- Operations Phase --

  @spec allocate_funds(String.t(), String.t(), non_neg_integer()) :: Event.t()
  def allocate_funds(founder_id, allocation_type, amount) do
    Event.new("allocate_funds", %{
      "founder_id" => founder_id,
      "allocation_type" => allocation_type,
      "amount" => amount
    })
  end

  # -- Phase completion signals --

  @spec end_phase(String.t(), String.t()) :: Event.t()
  def end_phase(player_id, phase) do
    Event.new("end_phase", %{
      "player_id" => player_id,
      "phase" => phase
    })
  end

  # -- System events (generated by updater) --

  @spec pitch_delivered(String.t(), String.t()) :: Event.t()
  def pitch_delivered(founder_id, pitch_text) do
    Event.new("pitch_delivered", %{
      "founder_id" => founder_id,
      "pitch_text" => pitch_text
    })
  end

  @spec question_asked(String.t(), String.t()) :: Event.t()
  def question_asked(investor_id, founder_id) do
    Event.new("question_asked", %{
      "investor_id" => investor_id,
      "founder_id" => founder_id
    })
  end

  @spec answer_delivered(String.t(), String.t()) :: Event.t()
  def answer_delivered(founder_id, investor_id) do
    Event.new("answer_delivered", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id
    })
  end

  @spec offer_made(String.t(), String.t(), non_neg_integer(), float()) :: Event.t()
  def offer_made(investor_id, founder_id, amount, equity_pct) do
    Event.new("offer_made", %{
      "investor_id" => investor_id,
      "founder_id" => founder_id,
      "amount" => amount,
      "equity_pct" => equity_pct
    })
  end

  @spec deal_closed(String.t(), String.t(), non_neg_integer(), float()) :: Event.t()
  def deal_closed(founder_id, investor_id, amount, equity_pct) do
    Event.new("deal_closed", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id,
      "amount" => amount,
      "equity_pct" => equity_pct
    })
  end

  @spec deal_rejected(String.t(), String.t()) :: Event.t()
  def deal_rejected(founder_id, investor_id) do
    Event.new("deal_rejected", %{
      "founder_id" => founder_id,
      "investor_id" => investor_id
    })
  end

  @spec startups_merged(String.t(), String.t()) :: Event.t()
  def startups_merged(founder_a_id, founder_b_id) do
    Event.new("startups_merged", %{
      "founder_a_id" => founder_a_id,
      "founder_b_id" => founder_b_id
    })
  end

  @spec funds_allocated(String.t(), String.t(), non_neg_integer()) :: Event.t()
  def funds_allocated(founder_id, allocation_type, amount) do
    Event.new("funds_allocated", %{
      "founder_id" => founder_id,
      "allocation_type" => allocation_type,
      "amount" => amount
    })
  end

  @spec market_event_applied(String.t(), map()) :: Event.t()
  def market_event_applied(event_name, sector_changes) do
    Event.new("market_event_applied", %{
      "event_name" => event_name,
      "sector_changes" => sector_changes
    })
  end

  @spec metrics_updated(String.t(), map()) :: Event.t()
  def metrics_updated(founder_id, new_metrics) do
    Event.new("metrics_updated", %{
      "founder_id" => founder_id,
      "new_metrics" => new_metrics
    })
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec round_advanced(pos_integer()) :: Event.t()
  def round_advanced(round) do
    Event.new("round_advanced", %{"round" => round})
  end

  @spec game_over(String.t(), String.t()) :: Event.t()
  def game_over(status, winner) do
    Event.new("game_over", %{
      "status" => status,
      "winner" => winner,
      "message" => "#{winner} wins the startup incubator game"
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, player_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "player_id" => player_id,
      "reason" => reason
    })
  end
end
