defmodule LemonCore.Setup.Scaffold do
  @moduledoc """
  Generates minimal TOML config scaffolds for first-time Lemon setup.

  The generated config includes the most commonly needed sections with
  sensible defaults, leaving advanced options commented out. Users can
  expand it using `examples/config.example.toml` as a reference.
  """

  alias LemonCore.Config.Modular

  @doc """
  Returns `true` when a global config file already exists.
  """
  @spec global_config_exists?() :: boolean()
  def global_config_exists? do
    Modular.global_path()
    |> Path.expand()
    |> File.exists?()
  end

  @doc """
  Returns `true` when a project config exists under `dir/.lemon/config.toml`.
  """
  @spec project_config_exists?(String.t()) :: boolean()
  def project_config_exists?(dir) do
    Modular.project_path(dir)
    |> Path.expand()
    |> File.exists?()
  end

  @doc """
  Generates a minimal TOML config string.

  ## Options

    * `:provider` - provider id string (default: `"anthropic"`)
    * `:model` - model id string (default: `"claude-sonnet-4-20250514"`)
    * `:api_key_placeholder` - placeholder for the API key (default: `"<your-api-key>"`)

  ## Examples

      Scaffold.generate(provider: "anthropic", model: "claude-sonnet-4-5")
  """
  @spec generate(keyword()) :: String.t()
  def generate(opts \\ []) do
    provider = Keyword.get(opts, :provider, "anthropic")
    model = Keyword.get(opts, :model, "claude-sonnet-4-20250514")
    api_key_placeholder = Keyword.get(opts, :api_key_placeholder, "<your-api-key>")

    """
    # Lemon configuration
    # Generated by mix lemon.setup
    # Full reference: examples/config.example.toml

    [defaults]
    provider = "#{provider}"
    model = "#{model}"

    [providers.#{provider}]
    # Set via secret: mix lemon.onboard #{provider}
    # Or use the env override: LEMON_#{String.upcase(provider)}_API_KEY
    api_key_secret = "#{provider}_api_key"
    # api_key = "#{api_key_placeholder}"

    [runtime]
    theme = "default"

    [gateway]
    max_concurrent_runs = 2
    auto_resume = false
    enable_telegram = false

    [tui]
    theme = "lemon"
    """
  end

  @doc """
  Writes a config scaffold to `path` unless a file already exists there.

  Returns `{:ok, path}` when written, `{:exists, path}` when skipped,
  or `{:error, reason}` on write failure.
  """
  @spec write_unless_exists(String.t(), String.t()) ::
          {:ok, String.t()} | {:exists, String.t()} | {:error, term()}
  def write_unless_exists(path, content) do
    expanded = Path.expand(path)

    if File.exists?(expanded) do
      {:exists, expanded}
    else
      File.mkdir_p!(Path.dirname(expanded))

      case File.write(expanded, content) do
        :ok -> {:ok, expanded}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @doc """
  Writes the global config scaffold unless it already exists.

  Uses `generate/1` with the given `opts` to produce the content.
  """
  @spec bootstrap_global(keyword()) ::
          {:ok, String.t()} | {:exists, String.t()} | {:error, term()}
  def bootstrap_global(opts \\ []) do
    path = Modular.global_path()
    content = generate(opts)
    write_unless_exists(path, content)
  end
end
