defmodule LemonSim.Examples.MurderMystery.Events do
  @moduledoc false

  alias LemonSim.Event

  @spec normalize(Event.t() | map() | keyword()) :: Event.t()
  def normalize(raw_event), do: Event.new(raw_event)

  # -- Investigation phase --

  @spec search_room(String.t(), String.t()) :: Event.t()
  def search_room(player_id, room_id) do
    Event.new("search_room", %{
      "player_id" => player_id,
      "room_id" => room_id
    })
  end

  # -- Interrogation phase --

  @spec ask_player(String.t(), String.t(), String.t()) :: Event.t()
  def ask_player(asker_id, target_id, question) do
    Event.new("ask_player", %{
      "asker_id" => asker_id,
      "player_id" => asker_id,
      "target_id" => target_id,
      "question" => question
    })
  end

  @spec answer_question(String.t(), String.t()) :: Event.t()
  def answer_question(player_id, answer) do
    Event.new("answer_question", %{
      "player_id" => player_id,
      "answer" => answer
    })
  end

  # -- Discussion phase --

  @spec share_finding(String.t(), String.t()) :: Event.t()
  def share_finding(player_id, finding) do
    Event.new("share_finding", %{
      "player_id" => player_id,
      "content" => finding,
      "finding" => finding
    })
  end

  @spec make_theory(String.t(), String.t()) :: Event.t()
  def make_theory(player_id, theory) do
    Event.new("make_theory", %{
      "player_id" => player_id,
      "content" => theory,
      "theory" => theory
    })
  end

  @spec challenge_alibi(String.t(), String.t(), String.t()) :: Event.t()
  def challenge_alibi(player_id, target_id, reason) do
    Event.new("challenge_alibi", %{
      "player_id" => player_id,
      "target_id" => target_id,
      "content" => reason,
      "reason" => reason
    })
  end

  @spec end_discussion(String.t()) :: Event.t()
  def end_discussion(player_id) do
    Event.new("end_discussion", %{"player_id" => player_id})
  end

  # -- Killer action phase --

  @spec plant_evidence(String.t(), String.t(), String.t()) :: Event.t()
  def plant_evidence(player_id, room_id, clue_type) do
    Event.new("plant_evidence", %{
      "player_id" => player_id,
      "room_id" => room_id,
      "clue_type" => clue_type
    })
  end

  @spec destroy_clue(String.t(), String.t(), String.t()) :: Event.t()
  def destroy_clue(player_id, room_id, clue_id) do
    Event.new("destroy_clue", %{
      "player_id" => player_id,
      "room_id" => room_id,
      "clue_id" => clue_id
    })
  end

  @spec killer_do_nothing(String.t()) :: Event.t()
  def killer_do_nothing(player_id) do
    Event.new("killer_do_nothing", %{"player_id" => player_id})
  end

  # kept for backwards compatibility / action_space use
  @spec do_nothing(String.t()) :: Event.t()
  def do_nothing(player_id), do: killer_do_nothing(player_id)

  # -- Deduction vote phase --

  @spec make_accusation(String.t(), String.t(), String.t(), String.t()) :: Event.t()
  def make_accusation(player_id, accused_id, weapon, room_id) do
    Event.new("make_accusation", %{
      "player_id" => player_id,
      "accused_id" => accused_id,
      "weapon" => weapon,
      "room_id" => room_id
    })
  end

  @spec skip_accusation(String.t()) :: Event.t()
  def skip_accusation(player_id) do
    Event.new("skip_accusation", %{"player_id" => player_id})
  end

  # -- System events (generated by updater) --

  @spec room_searched(String.t(), String.t()) :: Event.t()
  def room_searched(player_id, room_id) do
    Event.new("room_searched", %{
      "player_id" => player_id,
      "room_id" => room_id
    })
  end

  @spec clue_found(String.t(), String.t(), String.t()) :: Event.t()
  def clue_found(player_id, room_id, clue_id) do
    Event.new("clue_found", %{
      "player_id" => player_id,
      "room_id" => room_id,
      "clue_id" => clue_id
    })
  end

  @spec question_logged(String.t(), String.t(), String.t()) :: Event.t()
  def question_logged(asker_id, target_id, question) do
    Event.new("question_logged", %{
      "asker_id" => asker_id,
      "target_id" => target_id,
      "question" => question
    })
  end

  @spec answer_logged(String.t(), String.t(), String.t()) :: Event.t()
  def answer_logged(player_id, question, answer) do
    Event.new("answer_logged", %{
      "player_id" => player_id,
      "question" => question,
      "answer" => answer
    })
  end

  @spec evidence_planted(String.t(), String.t()) :: Event.t()
  def evidence_planted(player_id, clue_id) do
    Event.new("evidence_planted", %{
      "player_id" => player_id,
      "clue_id" => clue_id
    })
  end

  @spec clue_destroyed(String.t(), String.t()) :: Event.t()
  def clue_destroyed(player_id, clue_id) do
    Event.new("clue_destroyed", %{
      "player_id" => player_id,
      "clue_id" => clue_id
    })
  end

  @spec accusation_result(String.t(), boolean(), String.t()) :: Event.t()
  def accusation_result(player_id, correct?, reason) do
    Event.new("accusation_result", %{
      "player_id" => player_id,
      "correct" => correct?,
      "reason" => reason
    })
  end

  @spec phase_changed(String.t(), String.t()) :: Event.t()
  def phase_changed(from_phase, to_phase) do
    Event.new("phase_changed", %{
      "from" => from_phase,
      "to" => to_phase
    })
  end

  @spec round_advanced(pos_integer()) :: Event.t()
  def round_advanced(round) do
    Event.new("round_advanced", %{"round" => round})
  end

  @spec game_over(String.t(), String.t()) :: Event.t()
  def game_over(winner, reason) do
    Event.new("game_over", %{
      "winner" => winner,
      "reason" => reason
    })
  end

  @spec action_rejected(String.t(), String.t(), String.t()) :: Event.t()
  def action_rejected(kind, player_id, reason) do
    Event.new("action_rejected", %{
      "kind" => kind,
      "player_id" => player_id,
      "reason" => reason
    })
  end
end
