defmodule LemonCore.Env.Declarations do
  @moduledoc """
  Environment variables read by `lemon_core` — the platform primitives (store, secrets, logging, retries), the standard platform/release variables no single app owns, and — until their readers move out in plan 1.10 — the variables lemon_core's own `Config.*` modules resolve on other apps' behalf.

  Aggregated by `LemonCore.Env` through the `:env_registries` list; see
  `LemonCore.Env.Registry`.

  The bulk of this module is a single `@declarations` data table — one map per
  environment variable — so its length tracks the number of variables, not code
  complexity. It renders `docs/config-registry.md`.
  """

  use LemonCore.Env.Registry

  @declarations [
    %{
      name: :lemon_base_delay_ms,
      env_var: "LEMON_BASE_DELAY_MS",
      aliases: [],
      type: :integer,
      default: 1000,
      doc: "Base backoff delay (ms) between retry attempts.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_budget_max_children,
      env_var: "LEMON_BUDGET_MAX_CHILDREN",
      aliases: [],
      type: :integer,
      default: 5,
      doc: "Default max concurrent delegated sub-agent children per run.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_compaction_enabled,
      env_var: "LEMON_COMPACTION_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether context compaction runs automatically as the transcript grows.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_compaction_keep_recent_tokens,
      env_var: "LEMON_COMPACTION_KEEP_RECENT_TOKENS",
      aliases: [],
      type: :integer,
      default: 20_000,
      doc: "Recent-token window kept verbatim (uncompacted) at the tail of the transcript.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_compaction_reserve_tokens,
      env_var: "LEMON_COMPACTION_RESERVE_TOKENS",
      aliases: [],
      type: :integer,
      default: 16_384,
      doc: "Token budget reserved (not compacted away) during compaction.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_default_model,
      env_var: "LEMON_DEFAULT_MODEL",
      aliases: [],
      type: :string,
      default: "claude-sonnet-4-20250514",
      doc: "Default model id used when no per-run model is specified.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_default_provider,
      env_var: "LEMON_DEFAULT_PROVIDER",
      aliases: [],
      type: :string,
      default: "anthropic",
      doc: "Default LLM provider id used when no per-run provider is specified.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_default_thinking_level,
      env_var: "LEMON_DEFAULT_THINKING_LEVEL",
      aliases: [],
      type: :string,
      default: "medium",
      doc: "Default reasoning/thinking effort level for the agent loop.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_extension_paths,
      env_var: "LEMON_EXTENSION_PATHS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated list of extra extension directories to load.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_extensions_auto_load_default_paths,
      env_var: "LEMON_EXTENSIONS_AUTO_LOAD_DEFAULT_PATHS",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether default extension search paths are auto-loaded.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_extensions_enabled,
      env_var: "LEMON_EXTENSIONS_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the extensions subsystem is enabled.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_max_retries,
      env_var: "LEMON_MAX_RETRIES",
      aliases: [],
      type: :integer,
      default: 3,
      doc: "Maximum retry attempts for a failing LLM call.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_provider_fallback_providers,
      env_var: "LEMON_PROVIDER_FALLBACK_PROVIDERS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated fallback provider ids tried after the primary provider fails.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_provider_routing_default_pool,
      env_var: "LEMON_PROVIDER_ROUTING_DEFAULT_POOL",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Default credential pool name used for provider routing.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_provider_routing_default_profile,
      env_var: "LEMON_PROVIDER_ROUTING_DEFAULT_PROFILE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Default provider routing profile name.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_provider_routing_enabled,
      env_var: "LEMON_PROVIDER_ROUTING_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether multi-provider routing/fallback is enabled.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_provider_routing_require_credentials,
      env_var: "LEMON_PROVIDER_ROUTING_REQUIRE_CREDENTIALS",
      aliases: [],
      type: :boolean,
      default: true,
      doc:
        "Whether provider routing requires resolvable credentials before selecting a provider.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_retry_enabled,
      env_var: "LEMON_RETRY_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether transient LLM call failures are retried.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_shell_command_prefix,
      env_var: "LEMON_SHELL_COMMAND_PREFIX",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Command prefix prepended to every shell tool invocation.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_shell_path,
      env_var: "LEMON_SHELL_PATH",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Shell executable path used by the bash/shell tool.",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_theme,
      env_var: "LEMON_THEME",
      aliases: [],
      type: :string,
      default: "lemon",
      doc: "Agent-level theme name (distinct from the TUI theme).",
      secret?: false,
      required?: false,
      area: :agent,
      apps: [:lemon_core]
    },
    %{
      name: :phx_server,
      env_var: "PHX_SERVER",
      aliases: [],
      type: :boolean,
      default: false,
      doc:
        "Standard Phoenix flag to start the HTTP server in a release (ecosystem-standard name).",
      secret?: false,
      required?: false,
      area: :endpoints,
      apps: [:lemon_web, :lemon_sim_ui]
    },
    %{
      name: :sentry_dsn,
      env_var: "SENTRY_DSN",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Sentry DSN; error reporting is dormant unless this is set.",
      secret?: true,
      required?: false,
      area: :error_reporting,
      apps: [:lemon_core]
    },
    %{
      name: :sentry_environment,
      env_var: "SENTRY_ENVIRONMENT",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Sentry environment name override (falls back to LEMON_ENV, then Mix env).",
      secret?: false,
      required?: false,
      area: :error_reporting,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_log_compress_on_rotate,
      env_var: "LEMON_LOG_COMPRESS_ON_ROTATE",
      aliases: [],
      type: :boolean,
      default: nil,
      doc: "Whether rotated log files are gzip-compressed.",
      secret?: false,
      required?: false,
      area: :logging,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_log_file,
      env_var: "LEMON_LOG_FILE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Path to the log file (nil disables file logging).",
      secret?: false,
      required?: false,
      area: :logging,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_log_filesync_repeat_interval,
      env_var: "LEMON_LOG_FILESYNC_REPEAT_INTERVAL",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Log file sync interval, in milliseconds.",
      secret?: false,
      required?: false,
      area: :logging,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_log_level,
      env_var: "LEMON_LOG_LEVEL",
      aliases: [],
      type: :string,
      default: nil,
      doc:
        "Global log level override (debug/info/notice/warning/error/critical/alert/emergency).",
      secret?: false,
      required?: false,
      area: :logging,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_log_max_no_bytes,
      env_var: "LEMON_LOG_MAX_NO_BYTES",
      aliases: [],
      type: :integer,
      default: nil,
      doc:
        "Log file rotation size threshold, in bytes. Plain integer only -- unlike " <>
          "LEMON_WASM_DEFAULT_MEMORY_LIMIT, this one does not accept \"10MB\"-style suffixes.",
      secret?: false,
      required?: false,
      area: :logging,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_log_max_no_files,
      env_var: "LEMON_LOG_MAX_NO_FILES",
      aliases: [],
      type: :integer,
      default: nil,
      doc: "Number of rotated log files retained.",
      secret?: false,
      required?: false,
      area: :logging,
      apps: [:lemon_core]
    },
    %{
      name: :home,
      env_var: "HOME",
      aliases: [],
      type: :string,
      default: nil,
      doc:
        "Standard POSIX home directory; used for default `.lemon` locations and OAuth token caches.",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_core, :lemon_ai, :coding_agent]
    },
    %{
      name: :mix_env,
      env_var: "MIX_ENV",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Standard Mix environment (dev/test/prod).",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_core]
    },
    %{
      name: :release_name,
      env_var: "RELEASE_NAME",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Standard Elixir release name; selects which endpoint(s) boot in a multi-app release.",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_core]
    },
    %{
      name: :release_node,
      env_var: "RELEASE_NODE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Standard Elixir release node name; presence indicates a running release (vs. `mix`).",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_core]
    },
    %{
      name: :release_vsn,
      env_var: "RELEASE_VSN",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Standard Elixir release version.",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_core]
    },
    %{
      name: :shell,
      env_var: "SHELL",
      aliases: [],
      type: :string,
      default: "/bin/sh",
      doc: "Standard POSIX shell path, used as a fallback shell for the external decider.",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_sim]
    },
    %{
      name: :term,
      env_var: "TERM",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Standard terminal type variable; used to detect non-interactive/dumb terminals.",
      secret?: false,
      required?: false,
      area: :platform,
      apps: [:lemon_cli]
    },
    %{
      name: :aws_default_region,
      env_var: "AWS_DEFAULT_REGION",
      aliases: [],
      type: :string,
      default: nil,
      doc: "AWS region fallback (ecosystem-standard AWS CLI name).",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :aws_region,
      env_var: "AWS_REGION",
      aliases: [],
      type: :string,
      default: "us-east-1",
      doc: "AWS region for Bedrock (ecosystem-standard name).",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :aws_session_token,
      env_var: "AWS_SESSION_TOKEN",
      aliases: [],
      type: :string,
      default: nil,
      doc: "AWS temporary session token for Bedrock (ecosystem-standard name).",
      secret?: true,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :azure_openai_api_version,
      env_var: "AZURE_OPENAI_API_VERSION",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Azure OpenAI API version.",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :azure_openai_base_url,
      env_var: "AZURE_OPENAI_BASE_URL",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Azure OpenAI resource base URL.",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :azure_openai_deployment_name_map,
      env_var: "AZURE_OPENAI_DEPLOYMENT_NAME_MAP",
      aliases: [],
      type: :string,
      default: nil,
      doc: "JSON map of model id to Azure OpenAI deployment name.",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :azure_openai_resource_name,
      env_var: "AZURE_OPENAI_RESOURCE_NAME",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Azure OpenAI resource name.",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :google_application_credentials_json,
      env_var: "GOOGLE_APPLICATION_CREDENTIALS_JSON",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Inline Google service-account JSON credentials.",
      secret?: true,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :google_cloud_location,
      env_var: "GOOGLE_CLOUD_LOCATION",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Google Cloud / Vertex AI region.",
      secret?: false,
      required?: false,
      area: :provider_secrets,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_debug,
      env_var: "LEMON_DEBUG",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Global debug flag checked at a few call sites in addition to LEMON_LOG_LEVEL.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_dotenv_dir,
      env_var: "LEMON_DOTENV_DIR",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Directory to load a `.env` file from at boot.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_env,
      env_var: "LEMON_ENV",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Deployment environment label (used for Sentry environment tagging).",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_gateway_node_cookie,
      env_var: "LEMON_GATEWAY_NODE_COOKIE",
      aliases: ["LEMON_GATEWAY_COOKIE"],
      type: :string,
      default: nil,
      doc: "Distributed Erlang cookie for the gateway node.",
      secret?: true,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_gateway_node_name,
      env_var: "LEMON_GATEWAY_NODE_NAME",
      aliases: [],
      type: :string,
      default: "lemon",
      doc: "Distributed Erlang node name for the gateway.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_path,
      env_var: "LEMON_PATH",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Override for the `PATH` used when locating CLI subprocess executables.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_release_channel,
      env_var: "LEMON_RELEASE_CHANNEL",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Release channel label (stable/beta/etc), falls back to inferring from RELEASE_VSN.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_runtime_profile,
      env_var: "LEMON_RUNTIME_PROFILE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Named runtime profile selecting a bundle of feature defaults.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_test_allow_live_credentials,
      env_var: "LEMON_TEST_ALLOW_LIVE_CREDENTIALS",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Test-only opt-in to allow hermetic tests to use real provider credentials.",
      secret?: false,
      required?: false,
      area: :runtime,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_store_db_path,
      env_var: "LEMON_STORE_DB_PATH",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Override path for the SQLite store database file.",
      secret?: false,
      required?: false,
      area: :store,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_store_path,
      env_var: "LEMON_STORE_PATH",
      aliases: [],
      type: :string,
      default: nil,
      doc:
        "Override path for the primary JSONL/SQLite data store; required and absolute for the production sim UI.",
      secret?: false,
      required?: false,
      area: :store,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_cpus,
      env_var: "LEMON_DOCKER_TERMINAL_CPUS",
      aliases: [],
      type: :string,
      default: nil,
      doc: "CPU limit for the Docker terminal backend container.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_image,
      env_var: "LEMON_DOCKER_TERMINAL_IMAGE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Docker image used for the Docker terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_memory,
      env_var: "LEMON_DOCKER_TERMINAL_MEMORY",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Memory limit for the Docker terminal backend container.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_network,
      env_var: "LEMON_DOCKER_TERMINAL_NETWORK",
      aliases: [],
      type: :string,
      default: "none",
      doc: "Docker network mode for the Docker terminal backend container.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_pids_limit,
      env_var: "LEMON_DOCKER_TERMINAL_PIDS_LIMIT",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Process count limit for the Docker terminal backend container.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_read_only_rootfs,
      env_var: "LEMON_DOCKER_TERMINAL_READ_ONLY_ROOTFS",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the Docker terminal backend mounts a read-only root filesystem.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_docker_terminal_tmpfs_size,
      env_var: "LEMON_DOCKER_TERMINAL_TMPFS_SIZE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "tmpfs size for the Docker terminal backend's writable /tmp mount.",
      secret?: false,
      required?: false,
      area: :terminal_docker,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_connect_timeout,
      env_var: "LEMON_SSH_TERMINAL_CONNECT_TIMEOUT",
      aliases: [],
      type: :string,
      default: "10",
      doc: "SSH connect timeout (seconds) for the SSH terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_identity_file,
      env_var: "LEMON_SSH_TERMINAL_IDENTITY_FILE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "SSH identity (private key) file for the SSH terminal backend.",
      secret?: true,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_port,
      env_var: "LEMON_SSH_TERMINAL_PORT",
      aliases: [],
      type: :string,
      default: "22",
      doc: "SSH port for the SSH terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_strict_host_key_checking,
      env_var: "LEMON_SSH_TERMINAL_STRICT_HOST_KEY_CHECKING",
      aliases: [],
      type: :string,
      default: "yes",
      doc: "SSH StrictHostKeyChecking setting for the SSH terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_target,
      env_var: "LEMON_SSH_TERMINAL_TARGET",
      aliases: [],
      type: :string,
      default: nil,
      doc: "SSH target (user@host) for the SSH terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_user_known_hosts_file,
      env_var: "LEMON_SSH_TERMINAL_USER_KNOWN_HOSTS_FILE",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Known-hosts file used by the SSH terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_ssh_terminal_workdir,
      env_var: "LEMON_SSH_TERMINAL_WORKDIR",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Remote working directory for the SSH terminal backend.",
      secret?: false,
      required?: false,
      area: :terminal_ssh,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_tool_disclosure_budget_tokens,
      env_var: "LEMON_TOOL_DISCLOSURE_BUDGET_TOKENS",
      aliases: [],
      type: :integer,
      default: 40_000,
      doc:
        "Estimated tool-schema token total above which long-tail tools are hidden behind tool_search/tool_invoke.",
      secret?: false,
      required?: false,
      area: :tools_disclosure,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_tool_disclosure_catalog_tokens,
      env_var: "LEMON_TOOL_DISCLOSURE_CATALOG_TOKENS",
      aliases: [],
      type: :integer,
      default: 2_000,
      doc:
        "Token budget for the hidden-tool catalog digest embedded in the tool_search description.",
      secret?: false,
      required?: false,
      area: :tools_disclosure,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_tool_disclosure_enabled,
      env_var: "LEMON_TOOL_DISCLOSURE_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc:
        "Whether tool-schema progressive disclosure may activate when the tool catalog exceeds the token budget.",
      secret?: false,
      required?: false,
      area: :tools_disclosure,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_enabled,
      env_var: "LEMON_EXECUTE_CODE_ENABLED",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the execute_code programmatic tool-calling tool is enabled.",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_max_output_bytes,
      env_var: "LEMON_EXECUTE_CODE_MAX_OUTPUT_BYTES",
      aliases: [],
      type: :integer,
      default: 50_000,
      doc:
        "Maximum script stdout bytes returned to the model (larger output is spilled to a file).",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_max_rpc_calls,
      env_var: "LEMON_EXECUTE_CODE_MAX_RPC_CALLS",
      aliases: [],
      type: :integer,
      default: 100,
      doc: "Maximum tool RPC calls one execute_code script may make.",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_max_rpc_result_bytes,
      env_var: "LEMON_EXECUTE_CODE_MAX_RPC_RESULT_BYTES",
      aliases: [],
      type: :integer,
      default: 5_242_880,
      doc: "Total byte budget for tool RPC results returned to one execute_code script.",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_python_path,
      env_var: "LEMON_EXECUTE_CODE_PYTHON_PATH",
      aliases: [],
      type: :string,
      default: "",
      doc:
        "Explicit python3 interpreter path for execute_code scripts (empty = find python3 on PATH).",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_timeout_ms,
      env_var: "LEMON_EXECUTE_CODE_TIMEOUT_MS",
      aliases: [],
      type: :integer,
      default: 120_000,
      doc: "Wall-clock cap for one execute_code script run, in milliseconds.",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_execute_code_tools,
      env_var: "LEMON_EXECUTE_CODE_TOOLS",
      aliases: [],
      type: :list,
      default: [],
      doc:
        "Comma-separated subset of the execute_code RPC allowlist (read, grep, find, ls, webfetch) to expose; empty = full allowlist.",
      secret?: false,
      required?: false,
      area: :tools_execute_code,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_auto_build,
      env_var: "LEMON_WASM_AUTO_BUILD",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether WASM tools are auto-built from source on load.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_cache_compiled,
      env_var: "LEMON_WASM_CACHE_COMPILED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether compiled WASM modules are cached on disk.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_cache_dir,
      env_var: "LEMON_WASM_CACHE_DIR",
      aliases: [],
      type: :string,
      default: "",
      doc: "Directory used for the compiled WASM module cache.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_default_fuel_limit,
      env_var: "LEMON_WASM_DEFAULT_FUEL_LIMIT",
      aliases: [],
      type: :integer,
      default: 10_000_000,
      doc: "Default WASM interpreter fuel (execution-step) limit.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_default_memory_limit,
      env_var: "LEMON_WASM_DEFAULT_MEMORY_LIMIT",
      aliases: [],
      type: :bytes,
      default: 10_485_760,
      doc: "Default WASM tool memory limit (accepts B/KB/MB/GB suffixes).",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_default_timeout_ms,
      env_var: "LEMON_WASM_DEFAULT_TIMEOUT_MS",
      aliases: [],
      type: :integer,
      default: 60_000,
      doc: "Default WASM tool execution timeout, in milliseconds.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_enabled,
      env_var: "LEMON_WASM_ENABLED",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the WASM tool runtime is enabled.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_max_tool_invoke_depth,
      env_var: "LEMON_WASM_MAX_TOOL_INVOKE_DEPTH",
      aliases: [],
      type: :integer,
      default: 4,
      doc: "Maximum nested WASM tool invocation depth.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_runtime_path,
      env_var: "LEMON_WASM_RUNTIME_PATH",
      aliases: [],
      type: :string,
      default: "",
      doc: "Path to the WASM runtime executable/library.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_wasm_tool_paths,
      env_var: "LEMON_WASM_TOOL_PATHS",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated extra directories to search for WASM tools.",
      secret?: false,
      required?: false,
      area: :tools_wasm,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_auto_resize_images,
      env_var: "LEMON_AUTO_RESIZE_IMAGES",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether oversized images are auto-resized before being sent to a model.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_firecrawl_api_key,
      env_var: "LEMON_FIRECRAWL_API_KEY",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Firecrawl API key.",
      secret?: true,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_firecrawl_base_url,
      env_var: "LEMON_FIRECRAWL_BASE_URL",
      aliases: [],
      type: :string,
      default: "https://api.firecrawl.dev",
      doc: "Firecrawl API base URL.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_firecrawl_enabled,
      env_var: "LEMON_FIRECRAWL_ENABLED",
      aliases: [],
      type: :boolean,
      default: nil,
      doc:
        "Whether Firecrawl is used as the webfetch backend. Tri-state (nil = undecided, " <>
          "falls through to TOML/default); recognizes \"true\"/\"1\"/\"yes\" and " <>
          "\"false\"/\"0\"/\"no\" only -- not the \"on\"/\"off\" spellings most other " <>
          "booleans in this registry accept. Resolved with bespoke logic in " <>
          "LemonCore.Config.Tools.resolve_firecrawl/1, not the standard :boolean cast.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_perplexity_api_key,
      env_var: "LEMON_PERPLEXITY_API_KEY",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Perplexity API key used by the web search provider.",
      secret?: true,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_perplexity_base_url,
      env_var: "LEMON_PERPLEXITY_BASE_URL",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Perplexity API base URL override.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_perplexity_model,
      env_var: "LEMON_PERPLEXITY_MODEL",
      aliases: [],
      type: :string,
      default: "perplexity/sonar-pro",
      doc: "Perplexity model id used for web search.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_allow_private_network,
      env_var: "LEMON_WEB_FETCH_ALLOW_PRIVATE_NETWORK",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether webfetch is allowed to reach private/internal network addresses.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_allowed_hostnames,
      env_var: "LEMON_WEB_FETCH_ALLOWED_HOSTNAMES",
      aliases: [],
      type: :list,
      default: [],
      doc: "Comma-separated hostname allowlist for webfetch.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_cache_ttl,
      env_var: "LEMON_WEB_FETCH_CACHE_TTL",
      aliases: [],
      type: :integer,
      default: 15,
      doc: "Webfetch result cache TTL, in minutes.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_enabled,
      env_var: "LEMON_WEB_FETCH_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the webfetch tool is enabled.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_max_chars,
      env_var: "LEMON_WEB_FETCH_MAX_CHARS",
      aliases: [],
      type: :integer,
      default: 50_000,
      doc: "Maximum characters of fetched page content returned to the model.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_max_redirects,
      env_var: "LEMON_WEB_FETCH_MAX_REDIRECTS",
      aliases: [],
      type: :integer,
      default: 3,
      doc: "Maximum HTTP redirects followed by webfetch.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_readability,
      env_var: "LEMON_WEB_FETCH_READABILITY",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether webfetch runs readability extraction on HTML pages.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_timeout,
      env_var: "LEMON_WEB_FETCH_TIMEOUT",
      aliases: [],
      type: :integer,
      default: 30,
      doc: "Webfetch request timeout, in seconds.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_fetch_user_agent,
      env_var: "LEMON_WEB_FETCH_USER_AGENT",
      aliases: [],
      type: :string,
      default:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      doc: "User-Agent header sent by webfetch.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_api_key,
      env_var: "LEMON_WEB_SEARCH_API_KEY",
      aliases: [],
      type: :string,
      default: nil,
      doc: "API key for the configured web search provider.",
      secret?: true,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_cache_ttl,
      env_var: "LEMON_WEB_SEARCH_CACHE_TTL",
      aliases: [],
      type: :integer,
      default: 15,
      doc: "Web search result cache TTL, in minutes.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_enabled,
      env_var: "LEMON_WEB_SEARCH_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the web search tool is enabled.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_failover_enabled,
      env_var: "LEMON_WEB_SEARCH_FAILOVER_ENABLED",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether web search falls over to a secondary provider on failure.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_failover_provider,
      env_var: "LEMON_WEB_SEARCH_FAILOVER_PROVIDER",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Secondary web search provider id used on failover.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_max_results,
      env_var: "LEMON_WEB_SEARCH_MAX_RESULTS",
      aliases: [],
      type: :integer,
      default: 5,
      doc: "Maximum results returned per web search call.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_provider,
      env_var: "LEMON_WEB_SEARCH_PROVIDER",
      aliases: [],
      type: :string,
      default: "brave",
      doc: "Web search provider id (e.g. brave, perplexity).",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_web_search_timeout,
      env_var: "LEMON_WEB_SEARCH_TIMEOUT",
      aliases: [],
      type: :integer,
      default: 30,
      doc: "Web search request timeout, in seconds.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core]
    },
    %{
      name: :lemon_gateway_auto_resume,
      env_var: "LEMON_GATEWAY_AUTO_RESUME",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the gateway auto-resumes interrupted runs on boot.",
      secret?: false,
      required?: false,
      area: :gateway,
      apps: [:lemon_core, :lemon_gateway]
    },
    %{
      name: :lemon_gateway_default_cwd,
      env_var: "LEMON_GATEWAY_DEFAULT_CWD",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Default working directory for gateway-initiated runs.",
      secret?: false,
      required?: false,
      area: :gateway,
      apps: [:lemon_core, :lemon_gateway]
    },
    %{
      name: :lemon_gateway_enable_webhook,
      env_var: "LEMON_GATEWAY_ENABLE_WEBHOOK",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the generic webhook transport is enabled.",
      secret?: false,
      required?: false,
      area: :gateway,
      apps: [:lemon_core, :lemon_gateway]
    },
    %{
      name: :lemon_gateway_engine_lock_timeout_ms,
      env_var: "LEMON_GATEWAY_ENGINE_LOCK_TIMEOUT_MS",
      aliases: [],
      type: :integer,
      default: 60_000,
      doc: "Engine lock acquisition timeout, in milliseconds.",
      secret?: false,
      required?: false,
      area: :gateway,
      apps: [:lemon_core, :lemon_gateway]
    },
    %{
      name: :lemon_gateway_max_concurrent_runs,
      env_var: "LEMON_GATEWAY_MAX_CONCURRENT_RUNS",
      aliases: [],
      type: :integer,
      default: 2,
      doc: "Maximum concurrent agent runs the gateway will schedule.",
      secret?: false,
      required?: false,
      area: :gateway,
      apps: [:lemon_core, :lemon_gateway]
    },
    %{
      name: :lemon_gateway_require_engine_lock,
      env_var: "LEMON_GATEWAY_REQUIRE_ENGINE_LOCK",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether an engine lock is required before starting a gateway run.",
      secret?: false,
      required?: false,
      area: :gateway,
      apps: [:lemon_core, :lemon_gateway]
    },
    %{
      name: :lemon_web_cache_max_entries,
      env_var: "LEMON_WEB_CACHE_MAX_ENTRIES",
      aliases: [],
      type: :integer,
      default: 100,
      doc: "Maximum entries retained in the web cache.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core, :coding_agent]
    },
    %{
      name: :lemon_web_cache_path,
      env_var: "LEMON_WEB_CACHE_PATH",
      aliases: [],
      type: :string,
      default: nil,
      doc: "Path override for the persistent web cache file.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core, :coding_agent]
    },
    %{
      name: :lemon_web_cache_persistent,
      env_var: "LEMON_WEB_CACHE_PERSISTENT",
      aliases: [],
      type: :boolean,
      default: true,
      doc: "Whether the webfetch/websearch cache persists to disk.",
      secret?: false,
      required?: false,
      area: :tools_web,
      apps: [:lemon_core, :coding_agent]
    },
    %{
      name: :lemon_tui_debug,
      env_var: "LEMON_TUI_DEBUG",
      aliases: [],
      type: :boolean,
      default: false,
      doc: "Whether the terminal UI runs in debug mode.",
      secret?: false,
      required?: false,
      area: :tui,
      apps: [:lemon_core, :lemon_cli]
    },
    %{
      name: :lemon_tui_theme,
      env_var: "LEMON_TUI_THEME",
      aliases: [],
      type: :string,
      default: "lemon",
      doc: "Terminal UI theme name.",
      secret?: false,
      required?: false,
      area: :tui,
      apps: [:lemon_core, :lemon_cli]
    }
  ]
end
