defmodule LemonSim.Examples.VendingBench.Updater do
  @moduledoc """
  Updater for the Vending Bench simulation.

  Applies events to world state, manages time progression, day rollover,
  sales resolution, delivery handling, and terminal conditions.
  """

  @behaviour LemonSim.Kernel.Updater

  alias LemonSim.Examples.VendingBench.ArenaEvents
  alias LemonSim.Examples.VendingBench.DayRollover
  alias LemonSim.Examples.VendingBench.Events
  alias LemonSim.Examples.VendingBench.MachineEvents
  alias LemonSim.Examples.VendingBench.Operations
  alias LemonSim.Examples.VendingBench.Support
  alias LemonSim.Examples.VendingBench.SupplierOrders
  alias LemonSim.Kernel.State

  @impl true
  def apply_event(%State{} = state, raw_event, _opts) do
    event = Events.normalize(raw_event)

    case event.kind do
      # -- Support events (operator lookups) --
      "operator_checked_balance" -> Operations.apply_support_event(state, event, 5)
      "operator_checked_storage" -> Operations.apply_support_event(state, event, 5)
      "operator_read_inbox" -> Operations.apply_support_event(state, event, 5)
      "operator_inspected_suppliers" -> Operations.apply_support_event(state, event, 5)
      "operator_reviewed_sales" -> Operations.apply_support_event(state, event, 5)
      "operator_researched_suppliers" -> Operations.apply_supplier_research(state, event)
      "operator_researched_market" -> Operations.apply_market_research(state, event)
      "operator_checked_competitors" -> Operations.apply_support_event(state, event, 5)
      "operator_created_reminder" -> Operations.apply_reminder_created(state, event)
      "operator_listed_reminders" -> Operations.apply_support_event(state, event, 3)
      "operator_completed_reminder" -> Operations.apply_reminder_completed(state, event)
      # -- Terminal: supplier email --
      "supplier_message_sent" -> SupplierOrders.apply_supplier_message_sent(state, event)
      "place_supplier_order" -> SupplierOrders.apply_place_supplier_order(state, event)
      "supplier_order_placed" -> SupplierOrders.apply_supplier_order_placed(state, event)
      "supplier_email_sent" -> SupplierOrders.apply_supplier_email(state, event)
      # -- Terminal: Arena PvP --
      "arena_message_sent" -> ArenaEvents.apply_arena_message_sent(state, event)
      "arena_money_sent" -> ArenaEvents.apply_arena_money_sent(state, event)
      "arena_trade_completed" -> ArenaEvents.apply_arena_trade_completed(state, event)
      "arena_trade_reversed" -> ArenaEvents.apply_arena_trade_reversed(state, event)
      "arena_supplier_lead_shared" -> ArenaEvents.apply_arena_supplier_lead_shared(state, event)
      "arena_price_war_detected" -> ArenaEvents.apply_arena_price_war_detected(state, event)
      "arena_collusion_signal" -> ArenaEvents.apply_arena_collusion_signal(state, event)
      # -- Terminal: physical worker --
      "physical_worker_run_requested" -> MachineEvents.apply_worker_requested(state, event)
      # -- Worker events (batch processing from physical worker) --
      "physical_worker_started" -> Support.apply_skip(state, event)
      "machine_inventory_checked" -> Support.apply_skip(state, event)
      "machine_stocked" -> MachineEvents.apply_machine_stocked(state, event)
      "cash_collected" -> MachineEvents.apply_cash_collected(state, event)
      "price_set" -> MachineEvents.apply_price_set(state, event)
      "expired_inventory_removed" -> MachineEvents.apply_expired_inventory_removed(state, event)
      "machine_fault_reported" -> MachineEvents.apply_machine_fault_reported(state, event)
      "physical_worker_finished" -> MachineEvents.apply_worker_finished(state, event)
      # -- Terminal: wait for next day --
      "next_day_waited" -> DayRollover.apply_next_day_waited(state, event)
      # -- System events (generated by rollover) --
      "day_advanced" -> Support.apply_skip(state, event)
      "daily_fee_charged" -> Support.apply_skip(state, event)
      "sale_realized" -> Support.apply_skip(state, event)
      "customer_refund_paid" -> Support.apply_skip(state, event)
      "delivery_arrived" -> Support.apply_skip(state, event)
      "storage_overflow_discarded" -> Support.apply_skip(state, event)
      "inventory_spoiled" -> Support.apply_skip(state, event)
      "supplier_reply_received" -> SupplierOrders.apply_supplier_reply_received(state, event)
      "weather_changed" -> Support.apply_skip(state, event)
      "bankruptcy_triggered" -> Support.apply_skip(state, event)
      "game_over" -> Support.apply_skip(state, event)
      "action_rejected" -> Support.apply_action_rejected(state, event)
      # -- Unknown --
      _ -> {:error, {:unknown_vending_bench_event, event.kind}}
    end
  end
end
