defmodule LemonSim.Examples.VendingBench.Updater do
  @moduledoc """
  Updater for the Vending Bench simulation.

  Applies events to world state, manages time progression, day rollover,
  sales resolution, delivery handling, and terminal conditions.
  """

  @behaviour LemonSim.Updater

  alias LemonSim.State
  alias LemonSim.Examples.VendingBench.{DemandModel, Events, Performance}

  @bankruptcy_threshold 5
  @start_of_day_minutes 9 * 60
  @worker_visit_minutes 75
  @worker_day_end_minutes 17 * 60
  @worker_latest_departure_minutes @worker_day_end_minutes - @worker_visit_minutes

  @impl true
  def apply_event(%State{} = state, raw_event, _opts) do
    event = Events.normalize(raw_event)

    case event.kind do
      # -- Support events (operator lookups) --
      "operator_checked_balance" -> apply_support_event(state, event, 5)
      "operator_checked_storage" -> apply_support_event(state, event, 5)
      "operator_read_inbox" -> apply_support_event(state, event, 5)
      "operator_inspected_suppliers" -> apply_support_event(state, event, 5)
      "operator_reviewed_sales" -> apply_support_event(state, event, 5)
      # -- Terminal: supplier email --
      "supplier_email_sent" -> apply_supplier_email(state, event)
      # -- Terminal: physical worker --
      "physical_worker_run_requested" -> apply_worker_requested(state, event)
      # -- Worker events (batch processing from physical worker) --
      "physical_worker_started" -> apply_skip(state, event)
      "machine_inventory_checked" -> apply_skip(state, event)
      "machine_stocked" -> apply_machine_stocked(state, event)
      "cash_collected" -> apply_cash_collected(state, event)
      "price_set" -> apply_price_set(state, event)
      "physical_worker_finished" -> apply_worker_finished(state, event)
      # -- Terminal: wait for next day --
      "next_day_waited" -> apply_next_day_waited(state, event)
      # -- System events (generated by rollover) --
      "day_advanced" -> apply_skip(state, event)
      "daily_fee_charged" -> apply_skip(state, event)
      "sale_realized" -> apply_skip(state, event)
      "delivery_arrived" -> apply_skip(state, event)
      "supplier_reply_received" -> apply_skip(state, event)
      "weather_changed" -> apply_skip(state, event)
      "bankruptcy_triggered" -> apply_skip(state, event)
      "game_over" -> apply_skip(state, event)
      "action_rejected" -> apply_action_rejected(state, event)
      # -- Unknown --
      _ -> apply_skip(state, event)
    end
  end

  # -- Support event handler --

  defp apply_support_event(state, event, time_cost) do
    state =
      state
      |> State.update_world(fn world ->
        time = get(world, :time_minutes, 540) + time_cost
        Map.put(world, :time_minutes, time)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  # -- Supplier email --

  defp apply_supplier_email(state, event) do
    supplier_id = get(event.payload, :supplier_id, "")
    item_id = get(event.payload, :item_id, "")
    quantity = get(event.payload, :quantity, 0)
    cost = get(event.payload, :cost, 0.0)
    delivery_day = get(event.payload, :delivery_day, 1)

    state =
      state
      |> State.update_world(fn world ->
        balance = get(world, :bank_balance, 0.0)
        pending = get(world, :pending_deliveries, [])
        supplier_order_history = get(world, :supplier_order_history, [])

        new_delivery = %{
          supplier_id: supplier_id,
          item_id: item_id,
          quantity: quantity,
          cost: cost,
          delivery_day: delivery_day,
          ordered_day: get(world, :day_number, 1)
        }

        world
        |> Map.put(:bank_balance, Float.round(balance - cost, 2))
        |> Map.put(:pending_deliveries, pending ++ [new_delivery])
        |> Map.put(:supplier_order_history, supplier_order_history ++ [new_delivery])
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 25)
      end)
      |> State.append_event(event)

    case maybe_rollover(state) do
      {:ok, next_state, :skip} ->
        {:ok, next_state,
         {:decide,
          "Order placed. $#{format_price(cost)} deducted. Delivery on day #{delivery_day}."}}

      other ->
        other
    end
  end

  # -- Physical worker --

  defp apply_worker_requested(state, event) do
    time_minutes = get(state.world, :time_minutes, 540)

    if time_minutes > @worker_latest_departure_minutes do
      reject_worker_dispatch(
        state,
        "Too late to dispatch the physical worker at #{format_time(time_minutes)}. " <>
          "Worker visits must start by #{format_time(@worker_latest_departure_minutes)} to be back by 17:00."
      )
    else
      state =
        state
        |> State.update_world(fn world ->
          count = get(world, :physical_worker_run_count, 0)

          world
          |> Map.put(:physical_worker_run_count, count + 1)
          |> Map.put(:time_minutes, get(world, :time_minutes, 540) + @worker_visit_minutes)
        end)
        |> State.append_event(event)

      {:ok, state, :skip}
    end
  end

  defp apply_machine_stocked(state, event) do
    slot_id = get(event.payload, :slot_id, "")
    item_id = get(event.payload, :item_id, "")
    quantity = get(event.payload, :quantity, 0)
    world = state.world
    machine = get(world, :machine, %{})
    slots = get(machine, :slots, %{})
    storage = get(world, :storage, %{})
    storage_inv = get(storage, :inventory, %{})
    catalog = get(world, :catalog, %{})
    slot = Map.get(slots, slot_id)
    storage_qty = Map.get(storage_inv, item_id, 0)

    cond do
      is_nil(slot) ->
        reject_worker_event(state, "Invalid slot #{slot_id}")

      not Map.has_key?(catalog, item_id) ->
        reject_worker_event(state, "Unknown catalog item #{item_id}")

      quantity <= 0 ->
        reject_worker_event(state, "Stock quantity must be positive")

      storage_qty < quantity ->
        reject_worker_event(
          state,
          "Cannot stock #{quantity} units of #{item_id}; only #{storage_qty} available in storage"
        )

      get(slot, :item_id) != nil and get(slot, :item_id) != item_id ->
        reject_worker_event(
          state,
          "Slot #{slot_id} already contains #{get(slot, :item_id)}"
        )

      true ->
        state =
          state
          |> State.update_world(fn world ->
            machine = get(world, :machine, %{})
            slots = get(machine, :slots, %{})
            storage = get(world, :storage, %{})
            storage_inv = get(storage, :inventory, %{})
            catalog = get(world, :catalog, %{})
            slot = Map.get(slots, slot_id, %{})
            current_inv = get(slot, :inventory, 0)

            new_storage_inv = Map.put(storage_inv, item_id, storage_qty - quantity)

            new_price =
              if get(slot, :price) do
                get(slot, :price)
              else
                item_info = Map.get(catalog, item_id, %{})
                Map.get(item_info, :reference_price, 2.00)
              end

            new_slot =
              slot
              |> Map.put(:item_id, item_id)
              |> Map.put(:inventory, current_inv + quantity)
              |> Map.put(:price, new_price)

            new_slots = Map.put(slots, slot_id, new_slot)
            new_machine = Map.put(machine, :slots, new_slots)
            new_storage = Map.put(storage, :inventory, new_storage_inv)

            world
            |> Map.put(:machine, new_machine)
            |> Map.put(:storage, new_storage)
          end)
          |> State.append_event(event)

        {:ok, state, :skip}
    end
  end

  defp apply_cash_collected(state, event) do
    amount = get(event.payload, :amount, 0.0)
    cash = get(state.world, :cash_in_machine, 0.0)

    cond do
      amount <= 0 ->
        reject_worker_event(state, "Collected cash amount must be positive")

      cash <= 0 ->
        reject_worker_event(state, "No cash is available to collect")

      amount > cash ->
        reject_worker_event(
          state,
          "Cannot collect $#{format_price(amount)}; only $#{format_price(cash)} is available"
        )

      true ->
        state =
          state
          |> State.update_world(fn world ->
            balance = get(world, :bank_balance, 0.0)
            cash = get(world, :cash_in_machine, 0.0)

            world
            |> Map.put(:bank_balance, Float.round(balance + amount, 2))
            |> Map.put(:cash_in_machine, Float.round(cash - amount, 2))
          end)
          |> State.append_event(event)

        {:ok, state, :skip}
    end
  end

  defp apply_price_set(state, event) do
    slot_id = get(event.payload, :slot_id, "")
    new_price = get(event.payload, :new_price, 0.0)
    machine = get(state.world, :machine, %{})
    slots = get(machine, :slots, %{})
    slot = Map.get(slots, slot_id)

    cond do
      is_nil(slot) ->
        reject_worker_event(state, "Invalid slot #{slot_id}")

      get(slot, :item_id) == nil ->
        reject_worker_event(state, "Cannot price empty slot #{slot_id}")

      new_price <= 0 ->
        reject_worker_event(state, "Price must be positive")

      true ->
        state =
          state
          |> State.update_world(fn world ->
            machine = get(world, :machine, %{})
            slots = get(machine, :slots, %{})
            slot = Map.get(slots, slot_id, %{})

            new_slot = Map.put(slot, :price, Float.round(new_price * 1.0, 2))
            new_slots = Map.put(slots, slot_id, new_slot)
            new_machine = Map.put(machine, :slots, new_slots)

            price_changes = get(world, :price_change_count, 0)

            world
            |> Map.put(:machine, new_machine)
            |> Map.put(:price_change_count, price_changes + 1)
          end)
          |> State.append_event(event)

        {:ok, state, :skip}
    end
  end

  defp apply_worker_finished(state, event) do
    summary = get(event.payload, :summary, "")

    state =
      state
      |> State.update_world(fn world ->
        history = get(world, :physical_worker_history, [])

        report = %{
          summary: summary,
          day: get(world, :day_number, 1),
          time: get(world, :time_minutes, 540)
        }

        world
        |> Map.put(:physical_worker_last_report, report)
        |> Map.put(:physical_worker_history, history ++ [report])
      end)
      |> State.append_event(event)

    case maybe_rollover(state) do
      {:ok, next_state, :skip} ->
        {:ok, next_state, {:decide, "Worker visit complete: #{summary}"}}

      other ->
        other
    end
  end

  # -- Wait for next day --

  defp apply_next_day_waited(state, event) do
    state = State.append_event(state, event)
    run_day_rollover(state)
  end

  # -- Day Rollover --

  defp run_day_rollover(state) do
    world = state.world
    day = get(world, :day_number, 1)
    max_days = get(world, :max_days, 30)
    seed = get(world, :seed, 42)
    next_day = day + 1

    machine = get(world, :machine, %{})
    slots = get(machine, :slots, %{})
    catalog = get(world, :catalog, %{})
    weather = get(world, :weather, %{kind: "mild", demand_multiplier: 1.0})

    # 1. Resolve sales
    sales = DemandModel.daily_sales(slots, catalog, weather, day, seed)

    {updated_slots, total_revenue, sale_events, sale_records} =
      Enum.reduce(sales, {slots, 0.0, [], []}, fn {slot_id, units_sold, revenue},
                                                  {acc_slots, acc_rev, acc_events, acc_records} ->
        slot = Map.get(acc_slots, slot_id, %{})
        current_inv = get(slot, :inventory, 0)
        new_inv = max(0, current_inv - units_sold)
        item_id = get(slot, :item_id)

        updated_slot = Map.put(slot, :inventory, new_inv)
        new_slots = Map.put(acc_slots, slot_id, updated_slot)

        sale_event = Events.sale_realized(slot_id, item_id, units_sold, revenue, day)

        sale_record = %{
          slot_id: slot_id,
          item_id: item_id,
          quantity: units_sold,
          revenue: revenue,
          day: day
        }

        {new_slots, acc_rev + revenue, acc_events ++ [sale_event], acc_records ++ [sale_record]}
      end)

    # 2. Add revenue to cash_in_machine
    cash_in_machine = get(world, :cash_in_machine, 0.0) + total_revenue

    # 3. Resolve deliveries arriving today
    pending = get(world, :pending_deliveries, [])

    {arrived, still_pending} =
      Enum.split_with(pending, fn d -> get(d, :delivery_day) <= next_day end)

    {updated_storage_inv, delivery_events, inbox_items} =
      Enum.reduce(arrived, {get(get(world, :storage, %{}), :inventory, %{}), [], []}, fn delivery,
                                                                                         {acc_inv,
                                                                                          acc_events,
                                                                                          acc_inbox} ->
        item_id = get(delivery, :item_id)
        quantity = get(delivery, :quantity, 0)
        supplier_id = get(delivery, :supplier_id, "")

        new_qty = Map.get(acc_inv, item_id, 0) + quantity
        new_inv = Map.put(acc_inv, item_id, new_qty)

        del_event = Events.delivery_arrived(supplier_id, item_id, quantity, next_day)

        inbox_item = %{
          from: supplier_id,
          subject: "Order Delivered",
          body: "Your order of #{quantity}x #{item_id} has been delivered to storage.",
          day: next_day
        }

        {new_inv, acc_events ++ [del_event], acc_inbox ++ [inbox_item]}
      end)

    # 4. Deduct daily fee
    balance = get(world, :bank_balance, 0.0)
    daily_fee = get(world, :daily_fee, 2.0)
    unpaid_streak = get(world, :unpaid_fee_streak, 0)

    {new_balance, new_unpaid} =
      if balance >= daily_fee do
        {Float.round(balance - daily_fee, 2), 0}
      else
        {balance, unpaid_streak + 1}
      end

    fee_event = Events.daily_fee_charged(daily_fee, new_balance)

    # 5. Check bankruptcy
    bankrupt? = new_unpaid >= @bankruptcy_threshold

    # 6. Update weather
    new_weather = DemandModel.generate_weather(next_day, seed)
    new_season = DemandModel.season_for_day(next_day)
    weather_event = Events.weather_changed(new_weather.kind, new_weather.demand_multiplier)

    # 7. Build new world
    storage = get(world, :storage, %{})

    new_machine = Map.put(machine, :slots, updated_slots)
    new_storage = Map.put(storage, :inventory, updated_storage_inv)

    sales_history = get(world, :sales_history, [])

    day_event = Events.day_advanced(day, next_day)

    updated_world =
      world
      |> Map.put(:machine, new_machine)
      |> Map.put(:storage, new_storage)
      |> Map.put(:cash_in_machine, Float.round(cash_in_machine, 2))
      |> Map.put(:bank_balance, new_balance)
      |> Map.put(:unpaid_fee_streak, new_unpaid)
      |> Map.put(:pending_deliveries, still_pending)
      |> Map.put(:recent_sales, sale_records)
      |> Map.put(:sales_history, sales_history ++ sale_records)
      |> Map.put(:inbox, get(world, :inbox, []) ++ inbox_items)
      |> Map.put(:weather, new_weather)
      |> Map.put(:season, new_season)
      |> Map.put(:day_number, next_day)
      |> Map.put(:time_minutes, @start_of_day_minutes)

    # 8. Check terminal conditions
    {final_world, terminal_events} =
      cond do
        bankrupt? ->
          bankruptcy_event = Events.bankruptcy_triggered(day, new_unpaid)
          perf = Performance.summarize(updated_world)
          game_over_event = Events.game_over("bankruptcy", day, perf)

          w =
            updated_world
            |> Map.put(:status, "bankrupt")

          {w, [bankruptcy_event, game_over_event]}

        next_day > max_days ->
          perf = Performance.summarize(updated_world)
          game_over_event = Events.game_over("completed", day, perf)

          w =
            updated_world
            |> Map.put(:day_number, max_days)
            |> Map.put(:status, "complete")

          {w, [game_over_event]}

        true ->
          {updated_world, []}
      end

    all_rollover_events =
      sale_events ++ delivery_events ++ [fee_event, weather_event, day_event] ++ terminal_events

    state =
      state
      |> State.update_world(fn _ -> final_world end)
      |> State.append_events(all_rollover_events)

    if final_world[:status] in ["bankrupt", "complete"] do
      {:ok, state, :skip}
    else
      {:ok, state, {:decide, "Day #{next_day} begins. Weather: #{new_weather.kind}."}}
    end
  end

  # -- Skip handler --

  defp apply_skip(state, event) do
    state = State.append_event(state, event)
    {:ok, state, :skip}
  end

  defp apply_action_rejected(state, event) do
    state =
      state
      |> State.append_event(event)
      |> State.update_world(fn world ->
        failures = get(world, :coordination_failures, 0)
        Map.put(world, :coordination_failures, failures + 1)
      end)

    {:ok, state, :skip}
  end

  defp reject_worker_event(state, reason) do
    apply_action_rejected(state, Events.action_rejected("physical_worker", reason))
  end

  defp reject_worker_dispatch(state, reason) do
    apply_action_rejected(state, Events.action_rejected("operator", reason))
  end

  defp maybe_rollover(state) do
    world = state.world

    if get(world, :time_minutes, 0) >= get(world, :minutes_per_day, 24 * 60) do
      run_day_rollover(state)
    else
      {:ok, state, :skip}
    end
  end

  # -- Helpers --

  defp format_price(price) when is_float(price),
    do: :erlang.float_to_binary(price, decimals: 2)

  defp format_price(price) when is_integer(price),
    do: :erlang.float_to_binary(price / 1, decimals: 2)

  defp format_price(price), do: to_string(price)

  defp format_time(minutes) when is_integer(minutes) do
    hours = div(minutes, 60)
    mins = rem(minutes, 60)
    "#{hours}:#{String.pad_leading(to_string(mins), 2, "0")}"
  end

  defp get(map, key) when is_map(map) and is_atom(key),
    do: Map.get(map, key, Map.get(map, Atom.to_string(key)))

  defp get(_map, _key), do: nil

  defp get(map, key, default) when is_map(map) and is_atom(key),
    do: Map.get(map, key, Map.get(map, Atom.to_string(key), default))

  defp get(_map, _key, default), do: default
end
