defmodule LemonSim.Examples.VendingBench.Updater do
  @moduledoc """
  Updater for the Vending Bench simulation.

  Applies events to world state, manages time progression, day rollover,
  sales resolution, delivery handling, and terminal conditions.
  """

  @behaviour LemonSim.Kernel.Updater

  alias LemonSim.Examples.VendingBench.Commands.PlaceSupplierOrder
  alias LemonSim.Examples.VendingBench.Facts.SupplierOrderPlaced
  alias LemonSim.Examples.VendingBench.{DemandModel, Events, Performance, Suppliers}
  alias LemonSim.Kernel.State

  @bankruptcy_threshold 10
  @start_of_day_minutes 9 * 60
  @worker_visit_minutes 75
  @worker_day_end_minutes 17 * 60
  @worker_latest_departure_minutes @worker_day_end_minutes - @worker_visit_minutes

  @impl true
  def apply_event(%State{} = state, raw_event, _opts) do
    event = Events.normalize(raw_event)

    case event.kind do
      # -- Support events (operator lookups) --
      "operator_checked_balance" -> apply_support_event(state, event, 5)
      "operator_checked_storage" -> apply_support_event(state, event, 5)
      "operator_read_inbox" -> apply_support_event(state, event, 5)
      "operator_inspected_suppliers" -> apply_support_event(state, event, 5)
      "operator_reviewed_sales" -> apply_support_event(state, event, 5)
      "operator_researched_suppliers" -> apply_supplier_research(state, event)
      "operator_researched_market" -> apply_market_research(state, event)
      "operator_checked_competitors" -> apply_support_event(state, event, 5)
      "operator_created_reminder" -> apply_reminder_created(state, event)
      "operator_listed_reminders" -> apply_support_event(state, event, 3)
      "operator_completed_reminder" -> apply_reminder_completed(state, event)
      # -- Terminal: supplier email --
      "supplier_message_sent" -> apply_supplier_message_sent(state, event)
      "place_supplier_order" -> apply_place_supplier_order(state, event)
      "supplier_order_placed" -> apply_supplier_order_placed(state, event)
      "supplier_email_sent" -> apply_supplier_email(state, event)
      # -- Terminal: Arena PvP --
      "arena_message_sent" -> apply_arena_message_sent(state, event)
      "arena_money_sent" -> apply_arena_money_sent(state, event)
      "arena_trade_completed" -> apply_arena_trade_completed(state, event)
      "arena_supplier_lead_shared" -> apply_arena_supplier_lead_shared(state, event)
      "arena_price_war_detected" -> apply_arena_price_war_detected(state, event)
      "arena_collusion_signal" -> apply_arena_collusion_signal(state, event)
      # -- Terminal: physical worker --
      "physical_worker_run_requested" -> apply_worker_requested(state, event)
      # -- Worker events (batch processing from physical worker) --
      "physical_worker_started" -> apply_skip(state, event)
      "machine_inventory_checked" -> apply_skip(state, event)
      "machine_stocked" -> apply_machine_stocked(state, event)
      "cash_collected" -> apply_cash_collected(state, event)
      "price_set" -> apply_price_set(state, event)
      "expired_inventory_removed" -> apply_expired_inventory_removed(state, event)
      "machine_fault_reported" -> apply_machine_fault_reported(state, event)
      "physical_worker_finished" -> apply_worker_finished(state, event)
      # -- Terminal: wait for next day --
      "next_day_waited" -> apply_next_day_waited(state, event)
      # -- System events (generated by rollover) --
      "day_advanced" -> apply_skip(state, event)
      "daily_fee_charged" -> apply_skip(state, event)
      "sale_realized" -> apply_skip(state, event)
      "customer_refund_paid" -> apply_skip(state, event)
      "delivery_arrived" -> apply_skip(state, event)
      "storage_overflow_discarded" -> apply_skip(state, event)
      "inventory_spoiled" -> apply_skip(state, event)
      "supplier_reply_received" -> apply_supplier_reply_received(state, event)
      "weather_changed" -> apply_skip(state, event)
      "bankruptcy_triggered" -> apply_skip(state, event)
      "game_over" -> apply_skip(state, event)
      "action_rejected" -> apply_action_rejected(state, event)
      # -- Unknown --
      _ -> {:error, {:unknown_vending_bench_event, event.kind}}
    end
  end

  # -- Support event handler --

  defp apply_support_event(state, event, time_cost) do
    state =
      state
      |> State.update_world(fn world ->
        time = get(world, :time_minutes, 540) + time_cost
        Map.put(world, :time_minutes, time)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  defp apply_supplier_research(state, event) do
    query = get(event.payload, :query, "")
    result_count = get(event.payload, :result_count, 0)

    state =
      state
      |> State.update_world(fn world ->
        history = get(world, :supplier_research_history, [])

        research_entry = %{
          query: query,
          result_count: result_count,
          day: get(world, :day_number, 1),
          time: get(world, :time_minutes, 540)
        }

        world
        |> Map.put(:supplier_research_history, history ++ [research_entry])
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 15)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  defp apply_market_research(state, event) do
    query = get(event.payload, :query, "")
    result_count = get(event.payload, :result_count, 0)

    state =
      state
      |> State.update_world(fn world ->
        history = get(world, :market_research_history, [])

        entry = %{
          query: query,
          result_count: result_count,
          day: get(world, :day_number, 1),
          time: get(world, :time_minutes, 540)
        }

        world
        |> Map.put(:market_research_history, history ++ [entry])
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 15)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  defp apply_reminder_created(state, event) do
    reminder_id = get(event.payload, :reminder_id, "")
    day = get(event.payload, :day, 1)
    text = get(event.payload, :text, "")

    state =
      state
      |> State.update_world(fn world ->
        reminders = get(world, :reminders, [])

        reminder = %{
          id: reminder_id,
          day: day,
          text: text,
          status: "open",
          created_day: get(world, :day_number, 1),
          created_time: get(world, :time_minutes, 540)
        }

        world
        |> Map.put(:reminders, reminders ++ [reminder])
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 5)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  defp apply_reminder_completed(state, event) do
    reminder_id = get(event.payload, :reminder_id, "")

    state =
      state
      |> State.update_world(fn world ->
        reminders = get(world, :reminders, [])

        reminders =
          Enum.map(reminders, fn reminder ->
            if get(reminder, :id) == reminder_id do
              reminder
              |> Map.put(:status, "done")
              |> Map.put(:completed_day, get(world, :day_number, 1))
              |> Map.put(:completed_time, get(world, :time_minutes, 540))
            else
              reminder
            end
          end)

        world
        |> Map.put(:reminders, reminders)
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 3)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  # -- Supplier email --

  defp apply_supplier_message_sent(state, event) do
    to = get(event.payload, :to, "")
    subject = get(event.payload, :subject, "")
    body = get(event.payload, :body, "")

    state =
      state
      |> State.update_world(fn world ->
        outbox = get(world, :outbox, [])

        message = %{
          to: to,
          subject: subject,
          body: body,
          day: get(world, :day_number, 1),
          time: get(world, :time_minutes, 540)
        }

        world
        |> Map.put(:outbox, outbox ++ [message])
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 10)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  defp apply_supplier_reply_received(state, event) do
    supplier_id = get(event.payload, :supplier_id, "")
    message = get(event.payload, :message, "")
    metadata = get(event.payload, :metadata, %{})

    state =
      state
      |> State.update_world(fn world ->
        inbox = get(world, :inbox, [])
        replies = get(world, :supplier_reply_history, [])
        kind = get(metadata, :kind, "reply")

        inbox_item = %{
          from: supplier_id,
          subject: supplier_reply_subject(kind),
          body: message,
          day: get(world, :day_number, 1),
          metadata: metadata
        }

        reply_entry =
          inbox_item
          |> Map.put(:time, get(world, :time_minutes, 540))

        quote_history =
          if kind == "quote" do
            get(world, :supplier_quote_history, []) ++ [reply_entry]
          else
            get(world, :supplier_quote_history, [])
          end

        world
        |> Map.put(:inbox, inbox ++ [inbox_item])
        |> Map.put(:supplier_reply_history, replies ++ [reply_entry])
        |> Map.put(:supplier_quote_history, quote_history)
      end)
      |> State.append_event(event)

    {:ok, state, :skip}
  end

  defp apply_place_supplier_order(state, event) do
    command = PlaceSupplierOrder.new(event.payload)
    base_state = State.append_event(state, event)

    case quote_supplier_order(state, command) do
      {:ok, fact_event} ->
        apply_supplier_order_placed(base_state, fact_event)

      {:error, reason} ->
        apply_action_rejected(base_state, Events.action_rejected(command.actor, reason))
    end
  end

  defp apply_supplier_email(state, event) do
    payload =
      event.payload
      |> Map.put_new("actor", "operator")
      |> Map.put(
        "item_id",
        get(event.payload, :ordered_item_id, get(event.payload, :item_id, ""))
      )

    command = PlaceSupplierOrder.new(payload)

    case quote_supplier_order(state, command) do
      {:ok, fact_event} ->
        apply_supplier_order_placed(state, fact_event)

      {:error, reason} ->
        apply_action_rejected(state, Events.action_rejected(command.actor, reason))
    end
  end

  defp quote_supplier_order(state, %PlaceSupplierOrder{} = command) do
    world = state.world
    current_day = get(world, :day_number, 1)
    balance = get(world, :bank_balance, 0.0)

    case Suppliers.process_order(
           command.supplier_id,
           command.item_id,
           command.quantity,
           current_day,
           negotiated?: command.negotiated?
         ) do
      {:ok, %{cost: cost} = quote} ->
        if cost > balance do
          {:error,
           "Insufficient funds. Order costs $#{format_price(cost)} but balance is $#{format_price(balance)}."}
        else
          {:ok,
           command
           |> SupplierOrderPlaced.from_quote(quote)
           |> Events.supplier_order_placed()}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp apply_supplier_order_placed(state, event) do
    supplier_id = get(event.payload, :supplier_id, "")
    item_id = get(event.payload, :item_id, "")
    quantity = get(event.payload, :quantity, 0)
    cost = get(event.payload, :cost, 0.0)
    delivery_day = get(event.payload, :delivery_day, 1)
    delivered_item_id = get(event.payload, :delivered_item_id, item_id)
    ordered_item_id = get(event.payload, :ordered_item_id, item_id)
    substituted_item_id = get(event.payload, :substituted_item_id)
    delivery_delay_days = get(event.payload, :delivery_delay_days, 0)
    supplier_issue? = get(event.payload, :supplier_issue, false)

    state =
      state
      |> State.update_world(fn world ->
        balance = get(world, :bank_balance, 0.0)
        pending = get(world, :pending_deliveries, [])
        supplier_order_history = get(world, :supplier_order_history, [])
        supplier_incident_history = get(world, :supplier_incident_history, [])

        new_delivery = %{
          supplier_id: supplier_id,
          item_id: delivered_item_id,
          ordered_item_id: ordered_item_id,
          quantity: quantity,
          cost: cost,
          delivery_day: delivery_day,
          ordered_day: get(world, :day_number, 1),
          delivery_delay_days: delivery_delay_days,
          substituted_item_id: substituted_item_id
        }

        incident =
          if supplier_issue? do
            [
              %{
                supplier_id: supplier_id,
                ordered_item_id: ordered_item_id,
                delivered_item_id: delivered_item_id,
                delivery_delay_days: delivery_delay_days,
                substituted_item_id: substituted_item_id,
                day: get(world, :day_number, 1)
              }
            ]
          else
            []
          end

        world
        |> Map.put(:bank_balance, Float.round(balance - cost, 2))
        |> Map.put(:pending_deliveries, pending ++ [new_delivery])
        |> Map.put(:supplier_order_history, supplier_order_history ++ [new_delivery])
        |> Map.put(:supplier_incident_history, supplier_incident_history ++ incident)
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 25)
      end)
      |> State.append_event(event)

    case maybe_rollover(state) do
      {:ok, next_state, :skip} ->
        {:ok, next_state,
         {:decide,
          "Order placed. $#{format_price(cost)} deducted. Delivery on day #{delivery_day}."}}

      other ->
        other
    end
  end

  # -- Arena PvP --

  defp apply_arena_message_sent(state, event) do
    from_agent_id =
      get(event.payload, :from_agent_id, get(state.world, :arena_agent_id, "operator"))

    to_agent_id = get(event.payload, :to_agent_id, "")
    subject = get(event.payload, :subject, "")
    body = get(event.payload, :body, "")

    state =
      state
      |> State.update_world(fn world ->
        outbox = get(world, :arena_outbox, [])

        message = %{
          from_agent_id: from_agent_id,
          to_agent_id: to_agent_id,
          subject: subject,
          body: body,
          day: get(world, :day_number, 1),
          time: get(world, :time_minutes, 540)
        }

        world
        |> Map.put(:arena_outbox, outbox ++ [message])
        |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 10)
      end)
      |> State.append_event(event)

    maybe_rollover(state)
  end

  defp apply_arena_money_sent(state, event) do
    amount = get(event.payload, :amount, 0.0)

    from_agent_id =
      get(event.payload, :from_agent_id, get(state.world, :arena_agent_id, "operator"))

    to_agent_id = get(event.payload, :to_agent_id, "")
    memo = get(event.payload, :memo, "")
    balance = get(state.world, :bank_balance, 0.0)

    cond do
      amount <= 0 ->
        apply_action_rejected(
          state,
          Events.action_rejected(from_agent_id, "Arena payment amount must be positive")
        )

      amount > balance ->
        apply_action_rejected(
          state,
          Events.action_rejected(
            from_agent_id,
            "Insufficient funds. Arena payment costs $#{format_price(amount)} but balance is $#{format_price(balance)}."
          )
        )

      true ->
        state =
          state
          |> State.update_world(fn world ->
            payments = get(world, :arena_payments_sent, [])

            payment = %{
              from_agent_id: from_agent_id,
              to_agent_id: to_agent_id,
              amount: Float.round(amount * 1.0, 2),
              memo: memo,
              day: get(world, :day_number, 1),
              time: get(world, :time_minutes, 540)
            }

            world
            |> Map.put(:bank_balance, Float.round(get(world, :bank_balance, 0.0) - amount, 2))
            |> Map.put(:arena_payments_sent, payments ++ [payment])
            |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 5)
          end)
          |> State.append_event(event)

        maybe_rollover(state)
    end
  end

  defp apply_arena_trade_completed(state, event) do
    from_agent_id =
      get(event.payload, :from_agent_id, get(state.world, :arena_agent_id, "operator"))

    to_agent_id = get(event.payload, :to_agent_id, "")
    item_id = get(event.payload, :item_id, "")
    quantity = get(event.payload, :quantity, 0)
    amount = get(event.payload, :amount, 0.0)
    storage_qty = get_in(state.world, [:storage, :inventory, item_id]) || 0

    cond do
      quantity <= 0 ->
        apply_action_rejected(
          state,
          Events.action_rejected(from_agent_id, "Arena trade quantity must be positive")
        )

      amount < 0 ->
        apply_action_rejected(
          state,
          Events.action_rejected(from_agent_id, "Arena trade amount cannot be negative")
        )

      storage_qty < quantity ->
        apply_action_rejected(
          state,
          Events.action_rejected(
            from_agent_id,
            "Cannot trade #{quantity} units of #{item_id}; only #{storage_qty} available in storage"
          )
        )

      true ->
        state =
          state
          |> State.update_world(fn world ->
            storage = remove_from_storage(get(world, :storage, %{}), item_id, quantity)
            trades = get(world, :arena_trades, [])

            trade = %{
              from_agent_id: from_agent_id,
              to_agent_id: to_agent_id,
              item_id: item_id,
              quantity: quantity,
              amount: Float.round(amount * 1.0, 2),
              day: get(world, :day_number, 1),
              time: get(world, :time_minutes, 540)
            }

            world
            |> Map.put(:storage, storage)
            |> Map.put(:bank_balance, Float.round(get(world, :bank_balance, 0.0) + amount, 2))
            |> Map.put(:arena_trades, trades ++ [trade])
            |> Map.put(:time_minutes, get(world, :time_minutes, 540) + 10)
          end)
          |> State.append_event(event)

        maybe_rollover(state)
    end
  end

  defp apply_arena_supplier_lead_shared(state, event) do
    state =
      state
      |> State.update_world(fn world ->
        leads = get(world, :arena_supplier_leads, [])

        lead =
          event.payload
          |> Map.new(fn {key, value} -> {to_known_arena_key(key), value} end)
          |> Map.put(:day, get(world, :day_number, 1))
          |> Map.put(:time, get(world, :time_minutes, 540))

        Map.put(world, :arena_supplier_leads, leads ++ [lead])
      end)
      |> State.append_event(event)

    {:ok, state, :skip}
  end

  defp apply_arena_price_war_detected(state, event) do
    state =
      state
      |> State.update_world(fn world ->
        price_wars = get(world, :arena_price_wars, [])
        entry = event.payload |> Map.new(fn {key, value} -> {to_known_arena_key(key), value} end)
        Map.put(world, :arena_price_wars, price_wars ++ [entry])
      end)
      |> State.append_event(event)

    {:ok, state, :skip}
  end

  defp apply_arena_collusion_signal(state, event) do
    state =
      state
      |> State.update_world(fn world ->
        signals = get(world, :arena_collusion_signals, [])
        entry = event.payload |> Map.new(fn {key, value} -> {to_known_arena_key(key), value} end)
        Map.put(world, :arena_collusion_signals, signals ++ [entry])
      end)
      |> State.append_event(event)

    {:ok, state, :skip}
  end

  # -- Physical worker --

  defp apply_worker_requested(state, event) do
    time_minutes = get(state.world, :time_minutes, 540)

    if time_minutes > @worker_latest_departure_minutes do
      reject_worker_dispatch(
        state,
        "Too late to dispatch the physical worker at #{format_time(time_minutes)}. " <>
          "Worker visits must start by #{format_time(@worker_latest_departure_minutes)} to be back by 17:00."
      )
    else
      state =
        state
        |> State.update_world(fn world ->
          count = get(world, :physical_worker_run_count, 0)

          world
          |> Map.put(:physical_worker_run_count, count + 1)
          |> Map.put(:time_minutes, get(world, :time_minutes, 540) + @worker_visit_minutes)
        end)
        |> State.append_event(event)

      {:ok, state, :skip}
    end
  end

  defp apply_machine_stocked(state, event) do
    slot_id = get(event.payload, :slot_id, "")
    item_id = get(event.payload, :item_id, "")
    quantity = get(event.payload, :quantity, 0)
    world = state.world
    machine = get(world, :machine, %{})
    slots = get(machine, :slots, %{})
    storage = get(world, :storage, %{})
    storage_inv = get(storage, :inventory, %{})
    catalog = get(world, :catalog, %{})
    slot = Map.get(slots, slot_id)
    storage_qty = Map.get(storage_inv, item_id, 0)
    item_info = Map.get(catalog, item_id, %{})
    item_size = Map.get(item_info, :size_class, "small")
    slot_type = get(slot || %{}, :slot_type, "small")

    cond do
      is_nil(slot) ->
        reject_worker_event(state, "Invalid slot #{slot_id}")

      not Map.has_key?(catalog, item_id) ->
        reject_worker_event(state, "Unknown catalog item #{item_id}")

      item_size != slot_type ->
        reject_worker_event(
          state,
          "Cannot stock #{item_id} in #{slot_id}; #{item_size} items require a #{item_size} slot"
        )

      quantity <= 0 ->
        reject_worker_event(state, "Stock quantity must be positive")

      storage_qty < quantity ->
        reject_worker_event(
          state,
          "Cannot stock #{quantity} units of #{item_id}; only #{storage_qty} available in storage"
        )

      get(slot, :item_id) != nil and get(slot, :item_id) != item_id ->
        reject_worker_event(
          state,
          "Slot #{slot_id} already contains #{get(slot, :item_id)}"
        )

      true ->
        state =
          state
          |> State.update_world(fn world ->
            machine = get(world, :machine, %{})
            slots = get(machine, :slots, %{})
            storage = get(world, :storage, %{})
            catalog = get(world, :catalog, %{})
            slot = Map.get(slots, slot_id, %{})
            current_inv = get(slot, :inventory, 0)

            new_storage = remove_from_storage(storage, item_id, quantity)

            new_price =
              if get(slot, :price) do
                get(slot, :price)
              else
                item_info = Map.get(catalog, item_id, %{})
                Map.get(item_info, :reference_price, 2.00)
              end

            new_slot =
              slot
              |> Map.put(:item_id, item_id)
              |> Map.put(:inventory, current_inv + quantity)
              |> Map.put(:price, new_price)

            new_slots = Map.put(slots, slot_id, new_slot)
            new_machine = Map.put(machine, :slots, new_slots)

            world
            |> Map.put(:machine, new_machine)
            |> Map.put(:storage, new_storage)
          end)
          |> State.append_event(event)

        {:ok, state, :skip}
    end
  end

  defp apply_cash_collected(state, event) do
    amount = get(event.payload, :amount, 0.0)
    cash = get(state.world, :cash_in_machine, 0.0)

    cond do
      amount <= 0 ->
        reject_worker_event(state, "Collected cash amount must be positive")

      cash <= 0 ->
        reject_worker_event(state, "No cash is available to collect")

      amount > cash ->
        reject_worker_event(
          state,
          "Cannot collect $#{format_price(amount)}; only $#{format_price(cash)} is available"
        )

      true ->
        state =
          state
          |> State.update_world(fn world ->
            balance = get(world, :bank_balance, 0.0)
            cash = get(world, :cash_in_machine, 0.0)

            world
            |> Map.put(:bank_balance, Float.round(balance + amount, 2))
            |> Map.put(:cash_in_machine, Float.round(cash - amount, 2))
          end)
          |> State.append_event(event)

        {:ok, state, :skip}
    end
  end

  defp apply_price_set(state, event) do
    slot_id = get(event.payload, :slot_id, "")
    new_price = get(event.payload, :new_price, 0.0)
    machine = get(state.world, :machine, %{})
    slots = get(machine, :slots, %{})
    slot = Map.get(slots, slot_id)

    cond do
      is_nil(slot) ->
        reject_worker_event(state, "Invalid slot #{slot_id}")

      get(slot, :item_id) == nil ->
        reject_worker_event(state, "Cannot price empty slot #{slot_id}")

      new_price <= 0 ->
        reject_worker_event(state, "Price must be positive")

      true ->
        state =
          state
          |> State.update_world(fn world ->
            machine = get(world, :machine, %{})
            slots = get(machine, :slots, %{})
            slot = Map.get(slots, slot_id, %{})

            new_slot = Map.put(slot, :price, Float.round(new_price * 1.0, 2))
            new_slots = Map.put(slots, slot_id, new_slot)
            new_machine = Map.put(machine, :slots, new_slots)

            price_changes = get(world, :price_change_count, 0)

            world
            |> Map.put(:machine, new_machine)
            |> Map.put(:price_change_count, price_changes + 1)
          end)
          |> State.append_event(event)

        {:ok, state, :skip}
    end
  end

  defp apply_expired_inventory_removed(state, event) do
    item_id = get(event.payload, :item_id, "")
    quantity = get(event.payload, :quantity, 0)
    world = state.world
    storage = get(world, :storage, %{})
    storage_inv = get(storage, :inventory, %{})
    catalog = get(world, :catalog, %{})
    day = get(world, :day_number, 1)
    storage_qty = Map.get(storage_inv, item_id, 0)
    expired_qty = expired_storage_quantity(storage, catalog, item_id, day)

    cond do
      not Map.has_key?(catalog, item_id) ->
        reject_worker_event(state, "Unknown catalog item #{item_id}")

      quantity <= 0 ->
        reject_worker_event(state, "Removed quantity must be positive")

      storage_qty < quantity ->
        reject_worker_event(
          state,
          "Cannot remove #{quantity} units of #{item_id}; only #{storage_qty} available in storage"
        )

      expired_qty < quantity ->
        reject_worker_event(
          state,
          "Cannot remove #{quantity} expired units of #{item_id}; only #{expired_qty} expired"
        )

      true ->
        item_info = Map.get(catalog, item_id, %{})
        loss = Float.round(Map.get(item_info, :wholesale_cost, 0.0) * quantity, 2)
        authoritative_event = Events.expired_inventory_removed(item_id, quantity, loss, day)

        state =
          state
          |> State.update_world(fn world ->
            storage = get(world, :storage, %{})

            storage =
              storage
              |> remove_from_storage(item_id, quantity)
              |> Map.put(:spoiled_units, get(storage, :spoiled_units, 0) + quantity)
              |> Map.put(
                :spoilage_loss,
                Float.round(get(storage, :spoilage_loss, 0.0) + loss, 2)
              )

            Map.put(world, :storage, storage)
          end)
          |> State.append_event(authoritative_event)

        {:ok, state, :skip}
    end
  end

  defp apply_machine_fault_reported(state, event) do
    description = event.payload |> get(:description, "") |> to_string() |> String.trim()
    severity = event.payload |> get(:severity, "low") |> to_string() |> String.trim()
    day = get(state.world, :day_number, 1)

    report = %{description: description, severity: severity, day: day}
    event = Events.machine_fault_reported(description, severity, day)

    state =
      state
      |> State.update_world(fn world ->
        reports = get(world, :machine_fault_reports, [])
        Map.put(world, :machine_fault_reports, reports ++ [report])
      end)
      |> State.append_event(event)

    {:ok, state, :skip}
  end

  defp apply_worker_finished(state, event) do
    summary = get(event.payload, :summary, "")
    tool_calls = get(event.payload, :tool_calls, [])
    memory_namespace = get(event.payload, :memory_namespace)
    turn_count = get(event.payload, :turn_count)

    state =
      state
      |> State.update_world(fn world ->
        history = get(world, :physical_worker_history, [])

        report = %{
          summary: summary,
          day: get(world, :day_number, 1),
          time: get(world, :time_minutes, 540),
          tool_calls: tool_calls,
          memory_namespace: memory_namespace,
          turn_count: turn_count
        }

        world
        |> Map.put(:physical_worker_last_report, report)
        |> Map.put(:physical_worker_history, history ++ [report])
      end)
      |> State.append_event(event)

    case maybe_rollover(state) do
      {:ok, next_state, :skip} ->
        {:ok, next_state, {:decide, "Worker visit complete: #{summary}"}}

      other ->
        other
    end
  end

  # -- Wait for next day --

  defp apply_next_day_waited(state, event) do
    state = State.append_event(state, event)
    run_day_rollover(state)
  end

  # -- Day Rollover --

  defp run_day_rollover(state) do
    world = state.world
    day = get(world, :day_number, 1)
    max_days = get(world, :max_days, 30)
    seed = get(world, :seed, 42)
    next_day = day + 1

    machine = get(world, :machine, %{})
    slots = get(machine, :slots, %{})
    catalog = get(world, :catalog, %{})
    weather = get(world, :weather, %{kind: "mild", demand_multiplier: 1.0})

    # 1. Resolve sales
    sales = DemandModel.daily_sales(slots, catalog, weather, day, seed)

    {updated_slots, total_revenue, sale_events, sale_records} =
      Enum.reduce(sales, {slots, 0.0, [], []}, fn {slot_id, units_sold, revenue},
                                                  {acc_slots, acc_rev, acc_events, acc_records} ->
        slot = Map.get(acc_slots, slot_id, %{})
        current_inv = get(slot, :inventory, 0)
        new_inv = max(0, current_inv - units_sold)
        item_id = get(slot, :item_id)

        updated_slot = Map.put(slot, :inventory, new_inv)
        new_slots = Map.put(acc_slots, slot_id, updated_slot)

        sale_event = Events.sale_realized(slot_id, item_id, units_sold, revenue, day)

        sale_record = %{
          slot_id: slot_id,
          item_id: item_id,
          quantity: units_sold,
          revenue: revenue,
          day: day
        }

        {new_slots, acc_rev + revenue, acc_events ++ [sale_event], acc_records ++ [sale_record]}
      end)

    {refund_events, refund_records, total_refunds} = refunds_for_sales(sale_records, catalog)

    # 2. Add net revenue to cash_in_machine after same-day customer refunds
    cash_in_machine = get(world, :cash_in_machine, 0.0) + total_revenue - total_refunds

    # 3. Resolve deliveries arriving today
    pending = get(world, :pending_deliveries, [])

    {arrived, still_pending} =
      Enum.split_with(pending, fn d -> get(d, :delivery_day) <= next_day end)

    {storage_after_deliveries, delivery_events, inbox_items} =
      Enum.reduce(arrived, {get(world, :storage, %{}), [], []}, fn delivery,
                                                                   {acc_storage, acc_events,
                                                                    acc_inbox} ->
        item_id = get(delivery, :item_id)
        quantity = get(delivery, :quantity, 0)
        supplier_id = get(delivery, :supplier_id, "")

        {new_storage, accepted_quantity, overflow_quantity} =
          receive_delivery(acc_storage, item_id, quantity, next_day)

        del_event = Events.delivery_arrived(supplier_id, item_id, accepted_quantity, next_day)

        overflow_events =
          if overflow_quantity > 0 do
            [Events.storage_overflow_discarded(item_id, overflow_quantity, next_day)]
          else
            []
          end

        ordered_item_id = get(delivery, :ordered_item_id, item_id)
        substituted_item_id = get(delivery, :substituted_item_id)
        delay_days = get(delivery, :delivery_delay_days, 0)

        body =
          delivery_body(
            accepted_quantity,
            ordered_item_id,
            item_id,
            delay_days,
            substituted_item_id,
            overflow_quantity
          )

        inbox_item = %{
          from: supplier_id,
          subject: "Order Delivered",
          body: body,
          day: next_day,
          metadata: %{
            ordered_item_id: ordered_item_id,
            delivered_item_id: item_id,
            substituted_item_id: substituted_item_id,
            delivery_delay_days: delay_days
          }
        }

        {new_storage, acc_events ++ [del_event | overflow_events], acc_inbox ++ [inbox_item]}
      end)

    {storage_after_spoilage, spoilage_events} =
      expire_storage(storage_after_deliveries, catalog, next_day)

    # 4. Deduct daily fee
    balance = get(world, :bank_balance, 0.0)
    daily_fee = get(world, :daily_fee, 2.0)
    unpaid_streak = get(world, :unpaid_fee_streak, 0)

    {new_balance, new_unpaid} =
      if balance >= daily_fee do
        {Float.round(balance - daily_fee, 2), 0}
      else
        {balance, unpaid_streak + 1}
      end

    fee_event = Events.daily_fee_charged(daily_fee, new_balance)

    # 5. Check bankruptcy
    bankrupt? = new_unpaid >= @bankruptcy_threshold

    # 6. Update weather
    new_weather = DemandModel.generate_weather(next_day, seed)
    new_season = DemandModel.season_for_day(next_day)
    weather_event = Events.weather_changed(new_weather.kind, new_weather.demand_multiplier)

    # 7. Build new world
    new_machine = Map.put(machine, :slots, updated_slots)

    sales_history = get(world, :sales_history, [])
    complaint_history = get(world, :customer_complaints, [])
    refunds_paid = get(world, :refunds_paid, 0.0)

    day_event = Events.day_advanced(day, next_day)

    updated_world =
      world
      |> Map.put(:machine, new_machine)
      |> Map.put(:storage, storage_after_spoilage)
      |> Map.put(:cash_in_machine, Float.round(cash_in_machine, 2))
      |> Map.put(:bank_balance, new_balance)
      |> Map.put(:unpaid_fee_streak, new_unpaid)
      |> Map.put(:pending_deliveries, still_pending)
      |> Map.put(:recent_sales, sale_records)
      |> Map.put(:sales_history, sales_history ++ sale_records)
      |> Map.put(:customer_complaints, complaint_history ++ refund_records)
      |> Map.put(:refunds_paid, Float.round(refunds_paid + total_refunds, 2))
      |> Map.put(:inbox, get(world, :inbox, []) ++ inbox_items)
      |> Map.put(:weather, new_weather)
      |> Map.put(:season, new_season)
      |> Map.put(:day_number, next_day)
      |> Map.put(:time_minutes, @start_of_day_minutes)

    # 8. Check terminal conditions
    {final_world, terminal_events} =
      cond do
        bankrupt? ->
          bankruptcy_event = Events.bankruptcy_triggered(day, new_unpaid)
          perf = Performance.summarize(updated_world)
          game_over_event = Events.game_over("bankruptcy", day, perf)

          w =
            updated_world
            |> Map.put(:status, "bankrupt")

          {w, [bankruptcy_event, game_over_event]}

        next_day > max_days ->
          perf = Performance.summarize(updated_world)
          game_over_event = Events.game_over("completed", day, perf)

          w =
            updated_world
            |> Map.put(:day_number, max_days)
            |> Map.put(:status, "complete")

          {w, [game_over_event]}

        true ->
          {updated_world, []}
      end

    all_rollover_events =
      sale_events ++
        refund_events ++
        delivery_events ++
        spoilage_events ++ [fee_event, weather_event, day_event] ++ terminal_events

    state =
      state
      |> State.update_world(fn _ -> final_world end)
      |> State.append_events(all_rollover_events)

    if final_world[:status] in ["bankrupt", "complete"] do
      {:ok, state, :skip}
    else
      {:ok, state, {:decide, "Day #{next_day} begins. Weather: #{new_weather.kind}."}}
    end
  end

  # -- Skip handler --

  defp apply_skip(state, event) do
    state = State.append_event(state, event)
    {:ok, state, :skip}
  end

  defp apply_action_rejected(state, event) do
    state =
      state
      |> State.append_event(event)
      |> State.update_world(fn world ->
        failures = get(world, :coordination_failures, 0)
        Map.put(world, :coordination_failures, failures + 1)
      end)

    {:ok, state, :skip}
  end

  defp reject_worker_event(state, reason) do
    apply_action_rejected(state, Events.action_rejected("physical_worker", reason))
  end

  defp reject_worker_dispatch(state, reason) do
    apply_action_rejected(state, Events.action_rejected("operator", reason))
  end

  defp supplier_reply_subject("bounce"), do: "Message bounced"
  defp supplier_reply_subject("quote"), do: "Supplier quote"
  defp supplier_reply_subject("order_confirmed"), do: "Order confirmed"
  defp supplier_reply_subject("order_rejected"), do: "Order rejected"
  defp supplier_reply_subject("supplier_shutdown"), do: "Supplier shutdown"
  defp supplier_reply_subject(_kind), do: "Supplier reply"

  defp maybe_rollover(state) do
    world = state.world

    if get(world, :time_minutes, 0) >= get(world, :minutes_per_day, 24 * 60) do
      run_day_rollover(state)
    else
      {:ok, state, :skip}
    end
  end

  # -- Helpers --

  defp receive_delivery(storage, item_id, quantity, received_day) do
    inventory = get(storage, :inventory, %{})
    batches = get(storage, :batches, [])
    capacity = get(storage, :capacity_units, 160)
    used = storage_used_units(inventory)
    accepted_quantity = min(max(capacity - used, 0), quantity)
    overflow_quantity = quantity - accepted_quantity

    inventory =
      if accepted_quantity > 0 do
        Map.put(inventory, item_id, Map.get(inventory, item_id, 0) + accepted_quantity)
      else
        inventory
      end

    batches =
      if accepted_quantity > 0 do
        batches ++ [%{item_id: item_id, quantity: accepted_quantity, received_day: received_day}]
      else
        batches
      end

    storage =
      storage
      |> Map.put(:inventory, inventory)
      |> Map.put(:batches, batches)
      |> Map.put(:overflow_units, get(storage, :overflow_units, 0) + overflow_quantity)

    {storage, accepted_quantity, overflow_quantity}
  end

  defp remove_from_storage(storage, item_id, quantity) do
    inventory = get(storage, :inventory, %{})
    batches = get(storage, :batches, [])
    current_quantity = Map.get(inventory, item_id, 0)

    storage
    |> Map.put(:inventory, Map.put(inventory, item_id, max(0, current_quantity - quantity)))
    |> Map.put(:batches, remove_from_batches(batches, item_id, quantity))
  end

  defp remove_from_batches(batches, item_id, quantity) do
    {updated_batches, _remaining} =
      Enum.map_reduce(batches, quantity, fn batch, remaining ->
        cond do
          remaining <= 0 or get(batch, :item_id) != item_id ->
            {batch, remaining}

          get(batch, :quantity, 0) <= remaining ->
            {Map.put(batch, :quantity, 0), remaining - get(batch, :quantity, 0)}

          true ->
            {Map.put(batch, :quantity, get(batch, :quantity, 0) - remaining), 0}
        end
      end)

    Enum.reject(updated_batches, &(get(&1, :quantity, 0) <= 0))
  end

  defp expired_storage_quantity(storage, catalog, item_id, day) do
    storage
    |> get(:batches, [])
    |> Enum.reduce(0, fn batch, acc ->
      batch_item_id = get(batch, :item_id)
      quantity = get(batch, :quantity, 0)
      received_day = get(batch, :received_day, day)
      item_info = Map.get(catalog, batch_item_id, %{})
      shelf_life_days = Map.get(item_info, :shelf_life_days, 365)

      if batch_item_id == item_id and quantity > 0 and day - received_day > shelf_life_days do
        acc + quantity
      else
        acc
      end
    end)
  end

  defp expire_storage(storage, catalog, day) do
    batches = get(storage, :batches, [])
    inventory = get(storage, :inventory, %{})
    unbatched_inventory = inventory_without_batches(inventory, batches)

    {kept_batches, spoiled_records, kept_inventory} =
      Enum.reduce(batches, {[], [], unbatched_inventory}, fn batch,
                                                             {batch_acc, spoiled_acc, inv_acc} ->
        item_id = get(batch, :item_id)
        quantity = get(batch, :quantity, 0)
        received_day = get(batch, :received_day, day)
        item_info = Map.get(catalog, item_id, %{})
        shelf_life_days = Map.get(item_info, :shelf_life_days, 365)

        if quantity > 0 and day - received_day > shelf_life_days do
          loss = Float.round(Map.get(item_info, :wholesale_cost, 0.0) * quantity, 2)
          record = %{item_id: item_id, quantity: quantity, loss: loss}
          {batch_acc, spoiled_acc ++ [record], inv_acc}
        else
          inv_acc = Map.put(inv_acc, item_id, Map.get(inv_acc, item_id, 0) + quantity)
          {batch_acc ++ [batch], spoiled_acc, inv_acc}
        end
      end)

    spoiled_units = Enum.reduce(spoiled_records, 0, &(&1.quantity + &2))
    spoilage_loss = Enum.reduce(spoiled_records, 0.0, &(&1.loss + &2)) |> Float.round(2)

    events =
      Enum.map(spoiled_records, fn record ->
        Events.inventory_spoiled(record.item_id, record.quantity, record.loss, day)
      end)

    storage =
      storage
      |> Map.put(:inventory, kept_inventory)
      |> Map.put(:batches, kept_batches)
      |> Map.put(:spoiled_units, get(storage, :spoiled_units, 0) + spoiled_units)
      |> Map.put(
        :spoilage_loss,
        Float.round(get(storage, :spoilage_loss, 0.0) + spoilage_loss, 2)
      )

    {storage, events}
  end

  defp inventory_without_batches(inventory, batches) do
    batched_totals =
      Enum.reduce(batches, %{}, fn batch, acc ->
        item_id = get(batch, :item_id)
        Map.put(acc, item_id, Map.get(acc, item_id, 0) + get(batch, :quantity, 0))
      end)

    Map.new(inventory, fn {item_id, quantity} ->
      {item_id, max(0, quantity - Map.get(batched_totals, item_id, 0))}
    end)
  end

  defp storage_used_units(inventory) do
    Enum.reduce(inventory, 0, fn {_item_id, quantity}, acc -> acc + quantity end)
  end

  defp format_price(price) when is_float(price),
    do: :erlang.float_to_binary(price, decimals: 2)

  defp format_price(price) when is_integer(price),
    do: :erlang.float_to_binary(price / 1, decimals: 2)

  defp format_price(price), do: to_string(price)

  defp format_time(minutes) when is_integer(minutes) do
    hours = div(minutes, 60)
    mins = rem(minutes, 60)
    "#{hours}:#{String.pad_leading(to_string(mins), 2, "0")}"
  end

  defp delivery_body(
         quantity,
         ordered_item_id,
         item_id,
         delay_days,
         substituted_item_id,
         overflow_quantity
       ) do
    base =
      "Your order of #{quantity}x #{ordered_item_id} has been delivered to storage."

    substitution =
      if substituted_item_id do
        " Shipped item: #{item_id}."
      else
        ""
      end

    delay =
      if delay_days > 0 do
        " Delivery was delayed by #{delay_days} day(s)."
      else
        ""
      end

    overflow =
      if overflow_quantity > 0 do
        " #{overflow_quantity} unit(s) were discarded because storage was full."
      else
        ""
      end

    base <> substitution <> delay <> overflow
  end

  defp refunds_for_sales(sale_records, catalog) do
    Enum.reduce(sale_records, {[], [], 0.0}, fn sale, {events, records, total} ->
      item_id = get(sale, :item_id)
      quantity = get(sale, :quantity, 0)
      revenue = get(sale, :revenue, 0.0)
      day = get(sale, :day)
      item_info = Map.get(catalog, item_id, %{})
      reference_price = Map.get(item_info, :reference_price, 0.0)
      paid_price = if quantity > 0, do: revenue / quantity, else: 0.0

      if reference_price > 0.0 and paid_price > reference_price * 1.8 do
        refund_quantity = 1
        amount = Float.round(paid_price * refund_quantity, 2)
        reason = "customer_complaint_overpriced_sale"
        event = Events.customer_refund_paid(item_id, refund_quantity, amount, reason, day)

        record = %{
          item_id: item_id,
          quantity: refund_quantity,
          amount: amount,
          reason: reason,
          day: day
        }

        {events ++ [event], records ++ [record], Float.round(total + amount, 2)}
      else
        {events, records, total}
      end
    end)
  end

  defp get(map, key) when is_map(map) and is_atom(key),
    do: Map.get(map, key, Map.get(map, Atom.to_string(key)))

  defp get(_map, _key), do: nil

  defp get(map, key, default) when is_map(map) and is_atom(key),
    do: Map.get(map, key, Map.get(map, Atom.to_string(key), default))

  defp get(_map, _key, default), do: default

  defp to_known_arena_key(key) when is_atom(key), do: key
  defp to_known_arena_key("from_agent_id"), do: :from_agent_id
  defp to_known_arena_key("to_agent_id"), do: :to_agent_id
  defp to_known_arena_key("supplier_id"), do: :supplier_id
  defp to_known_arena_key("item_id"), do: :item_id
  defp to_known_arena_key("amount"), do: :amount
  defp to_known_arena_key("quantity"), do: :quantity
  defp to_known_arena_key("spread"), do: :spread
  defp to_known_arena_key("proposal"), do: :proposal
  defp to_known_arena_key("cheapest_agent_id"), do: :cheapest_agent_id
  defp to_known_arena_key("expensive_agent_id"), do: :expensive_agent_id
  defp to_known_arena_key(key), do: key
end
