#!/usr/bin/env python3
"""
Setup a Telegram bot via BotFather and configure lemon gateway.
Usage: uv run --with telethon python scripts/setup_telegram_bot.py
"""

import asyncio
import os
import re
import time
from pathlib import Path

from telethon import TelegramClient
from telethon.sessions import StringSession

# Load credentials
creds_path = Path.home() / ".zeebot/api_keys/telegram.txt"
creds = {}
for line in creds_path.read_text().strip().split("\n"):
    if "=" in line:
        key, val = line.split("=", 1)
        creds[key.strip()] = val.strip()

API_ID = int(creds["TELEGRAM_API_ID"])
API_HASH = creds["TELEGRAM_API_HASH"]
SESSION_STRING = creds["TELEGRAM_SESSION_STRING"]

BOTFATHER_USERNAME = "BotFather"


async def main():
    print("Connecting to Telegram...")
    client = TelegramClient(StringSession(SESSION_STRING), API_ID, API_HASH)
    await client.start()

    me = await client.get_me()
    print(f"Logged in as: {me.first_name} (@{me.username}, ID: {me.id})")

    # Generate a unique bot name
    timestamp = int(time.time())
    bot_name = f"Lemon Assistant {timestamp}"
    bot_username = f"lemon_{timestamp}_bot"

    print(f"\nCreating bot: {bot_name} (@{bot_username})")

    # Send /newbot to BotFather
    print("Sending /newbot to BotFather...")
    await client.send_message(BOTFATHER_USERNAME, "/newbot")
    await asyncio.sleep(2)

    # Send the bot name
    print(f"Sending bot name: {bot_name}")
    await client.send_message(BOTFATHER_USERNAME, bot_name)
    await asyncio.sleep(2)

    # Send the bot username
    print(f"Sending bot username: {bot_username}")
    await client.send_message(BOTFATHER_USERNAME, bot_username)
    await asyncio.sleep(3)

    # Get the response with the token
    print("Waiting for BotFather response...")
    messages = await client.get_messages(BOTFATHER_USERNAME, limit=5)

    bot_token = None
    for msg in messages:
        if msg.text and "HTTP API" in msg.text:
            # Extract token - format is like 123456789:ABCdefGHIjklMNOpqrsTUVwxyz
            match = re.search(r'(\d+:[A-Za-z0-9_-]+)', msg.text)
            if match:
                bot_token = match.group(1)
                print(f"\nBot token: {bot_token}")
                break

    if not bot_token:
        print("ERROR: Could not extract bot token from BotFather response")
        print("Last messages from BotFather:")
        for msg in messages[:3]:
            print(f"  - {msg.text[:200] if msg.text else '(no text)'}...")
        await client.disconnect()
        return

    # Create the gateway.toml config
    config_dir = Path.home() / ".lemon"
    config_dir.mkdir(exist_ok=True)
    config_path = config_dir / "gateway.toml"

    # Check if config already exists
    if config_path.exists():
        backup_path = config_dir / f"gateway.toml.backup.{int(time.time())}"
        print(f"\nBacking up existing config to {backup_path}")
        config_path.rename(backup_path)

    config_content = f'''# Lemon Gateway Configuration
# Generated by setup_telegram_bot.py

[gateway]
default_engine = "lemon"
max_concurrent_runs = 4

[telegram]
bot_token = "{bot_token}"
allowed_chat_ids = [{me.id}]
poll_interval_ms = 1000
debounce_ms = 1000
allow_queue_override = true

# Project bindings - maps chat IDs to project directories
[[bindings]]
transport = "telegram"
chat_id = {me.id}
project = "default"
default_engine = "lemon"

# Projects define working directories for the agent
[projects.default]
name = "default"
root = "~"
'''

    config_path.write_text(config_content)
    print(f"\nConfig written to: {config_path}")
    print("\n" + "=" * 50)
    print("SETUP COMPLETE!")
    print("=" * 50)
    print(f"\nBot: @{bot_username}")
    print(f"Your chat ID: {me.id}")
    print(f"Config: {config_path}")
    print("\nNext steps:")
    print("1. Start a chat with your bot: https://t.me/{bot_username}")
    print("2. Send /start to your bot")
    print("3. Start lemon gateway: cd ~/dev/lemon && iex -S mix")
    print("\nThe bot will then respond to your messages!")

    await client.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
