defmodule CodingAgent.Project.Codexignore do
  @moduledoc """
  Auto-generates a `.codexignore` file for managed projects to prevent
  Codex from ingesting large directories and hitting context limits.
  """

  require Logger

  @default_patterns [
    "# Auto-generated by Lemon — customize as needed",
    "",
    "# Dependencies",
    "node_modules/",
    "vendor/",
    "deps/",
    "_build/",
    ".elixir_ls/",
    "",
    "# Build artifacts",
    "build/",
    "dist/",
    "out/",
    "target/",
    "",
    "# Version control",
    ".git/",
    "",
    "# Logs and environment",
    "*.log",
    ".env",
    ".env.*",
    "",
    "# Large binary files",
    "*.zip",
    "*.tar.gz",
    "*.tgz",
    "*.jar",
    "*.war"
  ]

  @spec ensure_codexignore(String.t()) :: :ok | {:error, term()}
  def ensure_codexignore(cwd) when is_binary(cwd) do
    path = Path.join(cwd, ".codexignore")

    if File.exists?(path) do
      Logger.debug("Codexignore already exists at #{path}, skipping")
      :ok
    else
      content = Enum.join(@default_patterns, "\n") <> "\n"

      case File.write(path, content) do
        :ok ->
          Logger.info("Created .codexignore at #{path}")
          :ok

        {:error, reason} ->
          Logger.warning("Failed to create .codexignore at #{path}: #{inspect(reason)}")
          {:error, reason}
      end
    end
  rescue
    e ->
      Logger.warning("Error creating .codexignore: #{inspect(e)}")
      {:error, e}
  end

  def ensure_codexignore(_), do: :ok
end
