defmodule LemonCore.Doctor.SupportBundle do
  alias LemonCore.Config.Modular
  alias LemonCore.Doctor.Report

  @sensitive_terms ~w(
    access_key
    api_key
    apikey
    authorization
    bearer
    bot_token
    credential
    master_key
    oauth
    password
    private
    private_key
    secret
    session
    token
    wallet_key
  )

  @env_allowlist ~w(
    LANG
    LEMON_CONTROL_PLANE_PORT
    LEMON_PATH
    LEMON_SIM_UI_PORT
    LEMON_STORE_PATH
    LEMON_WEB_HOST
    LEMON_WEB_PORT
    MIX_ENV
    PHX_HOST
    TERM
  )

  @spec write(Report.t(), keyword()) :: {:ok, String.t()} | {:error, term()}
  def write(%Report{} = report, opts \\ []) do
    path = bundle_path(opts)
    File.mkdir_p!(Path.dirname(path))

    entries = [
      {~c"README.txt", readme()},
      {~c"manifest.json", json(manifest(opts))},
      {~c"doctor_report.json", Report.to_json(report)},
      {~c"environment.json", json(environment())}
      | config_entries(opts)
    ]

    case :zip.create(String.to_charlist(path), entries, []) do
      {:ok, _zip_path} -> {:ok, path}
      {:error, reason} -> {:error, reason}
    end
  end

  @spec redact_text(String.t()) :: String.t()
  def redact_text(text) when is_binary(text) do
    text
    |> redact_assignments()
    |> redact_inline_secrets()
  end

  defp bundle_path(opts) do
    case Keyword.get(opts, :bundle_path) do
      nil ->
        bundle_dir = Keyword.get(opts, :bundle_dir, "tmp/lemon-support-bundles")
        timestamp = DateTime.utc_now() |> Calendar.strftime("%Y%m%d-%H%M%S")
        Path.expand(Path.join(bundle_dir, "lemon-doctor-bundle-#{timestamp}.zip"))

      path ->
        Path.expand(path)
    end
  end

  defp manifest(opts) do
    project_dir = Keyword.get(opts, :project_dir, File.cwd!())

    Map.merge(LemonCore.BuildInfo.current(cwd: project_dir), %{
      generated_at: DateTime.utc_now() |> DateTime.to_iso8601(),
      bundle_version: 1,
      project_dir: project_dir |> Path.expand(),
      cwd: File.cwd!()
    })
  end

  defp environment do
    @env_allowlist
    |> Enum.sort()
    |> Map.new(fn name ->
      value = System.get_env(name)
      {name, env_value(name, value)}
    end)
  end

  defp env_value(_name, nil), do: %{present: false, value: nil}

  defp env_value(name, value) do
    if sensitive_name?(name) do
      %{present: true, value: "[redacted]"}
    else
      %{present: true, value: value}
    end
  end

  defp config_entries(opts) do
    project_dir = Keyword.get(opts, :project_dir, File.cwd!())

    [
      {~c"config/global_config.toml", Modular.global_path()},
      {~c"config/project_config.toml", Modular.project_path(project_dir)}
    ]
    |> Enum.map(fn {entry_name, path} ->
      expanded = Path.expand(path)

      content =
        if File.exists?(expanded) do
          File.read!(expanded) |> redact_text()
        else
          "missing: #{expanded}\n"
        end

      {entry_name, content}
    end)
  end

  defp json(data), do: Jason.encode!(data, pretty: true)

  defp readme do
    """
    Lemon doctor support bundle

    This archive is generated by `mix lemon.doctor --bundle` or the release
    support-bundle command.
    It includes the doctor report, runtime metadata, selected environment shape,
    and redacted Lemon config files.

    Review before sharing. It should not contain provider keys, tokens, passwords,
    private prompts, memory contents, or tool outputs.
    """
  end

  defp redact_assignments(text) do
    Regex.replace(
      ~r/^(\s*[^#\n=\[]*?(?:#{sensitive_pattern()})[^=\n]*=\s*).+$/imu,
      text,
      "\\1\"[redacted]\""
    )
  end

  defp redact_inline_secrets(text) do
    text
    |> then(&Regex.replace(~r/sk-[A-Za-z0-9_\-]{8,}/, &1, "[redacted]"))
    |> then(&Regex.replace(~r/(?i)bearer\s+[A-Za-z0-9._\-]+/, &1, "Bearer [redacted]"))
    |> then(&Regex.replace(~r/0x[a-fA-F0-9]{64}/, &1, "[redacted]"))
  end

  defp sensitive_name?(name) do
    downcased = String.downcase(to_string(name))
    Enum.any?(@sensitive_terms, &String.contains?(downcased, &1))
  end

  defp sensitive_pattern do
    Enum.map_join(@sensitive_terms, "|", &Regex.escape/1)
  end
end
