defmodule CodingAgent.Project.CodexignoreTest do
  @moduledoc """
  Tests for the Codexignore module.

  These tests verify that .codexignore files are created correctly
  with default patterns and that existing files are not overwritten.
  """
  use ExUnit.Case, async: true

  alias CodingAgent.Project.Codexignore

  @tag :tmp_dir
  test "creates .codexignore file with default patterns", %{tmp_dir: tmp_dir} do
    assert :ok = Codexignore.ensure_codexignore(tmp_dir)

    codexignore_path = Path.join(tmp_dir, ".codexignore")
    assert File.exists?(codexignore_path)

    content = File.read!(codexignore_path)
    assert content =~ "Auto-generated by Lemon"
    assert content =~ "node_modules/"
    assert content =~ "deps/"
    assert content =~ ".git/"
    assert content =~ ".env"
    assert content =~ "*.log"
  end

  @tag :tmp_dir
  test "does not overwrite existing .codexignore file", %{tmp_dir: tmp_dir} do
    codexignore_path = Path.join(tmp_dir, ".codexignore")
    File.write!(codexignore_path, "# Custom ignore file\n*.secret\n")

    assert :ok = Codexignore.ensure_codexignore(tmp_dir)

    content = File.read!(codexignore_path)
    assert content == "# Custom ignore file\n*.secret\n"
    refute content =~ "Auto-generated by Lemon"
  end

  @tag :tmp_dir
  test "handles non-string input gracefully" do
    # The function accepts any input but only processes strings
    assert :ok = Codexignore.ensure_codexignore(nil)
    assert :ok = Codexignore.ensure_codexignore(123)
    assert :ok = Codexignore.ensure_codexignore([])
  end

  @tag :tmp_dir
  test "created file contains all expected pattern categories", %{tmp_dir: tmp_dir} do
    assert :ok = Codexignore.ensure_codexignore(tmp_dir)

    content = File.read!(Path.join(tmp_dir, ".codexignore"))

    # Dependencies
    assert content =~ "node_modules/"
    assert content =~ "vendor/"
    assert content =~ "deps/"
    assert content =~ "_build/"

    # Build artifacts
    assert content =~ "build/"
    assert content =~ "dist/"
    assert content =~ "out/"

    # Version control
    assert content =~ ".git/"

    # Logs and environment
    assert content =~ "*.log"
    assert content =~ ".env"

    # Large binary files
    assert content =~ "*.zip"
    assert content =~ "*.tar.gz"
  end

  @tag :tmp_dir
  test "created file ends with newline", %{tmp_dir: tmp_dir} do
    assert :ok = Codexignore.ensure_codexignore(tmp_dir)

    content = File.read!(Path.join(tmp_dir, ".codexignore"))
    assert String.ends_with?(content, "\n")
  end

  @tag :tmp_dir
  test "returns :ok for empty string cwd" do
    # Empty string is a valid path (current directory)
    # The function will try to create .codexignore in current directory
    assert :ok = Codexignore.ensure_codexignore("")
  end
end
